In [1]:
%pip -q install duckdb pyarrow aiohttp

from google.colab import drive, userdata
from pathlib import Path
import asyncio
import json
import os
import random
import time

import aiohttp
import duckdb
import pandas as pd

if not Path("/content/drive/MyDrive").exists():
    drive.mount("/content/drive")

PARQUET_PATH = Path(
    "/content/drive/MyDrive/Language Detection/"
    "sessions_lang_transcript_2026-08-23_2026-08-24.parquet"
)

if not PARQUET_PATH.is_file():
    raise FileNotFoundError(PARQUET_PATH)

OPENROUTER_API_KEY = userdata.get("OPENROUTER_API_KEY")

if not OPENROUTER_API_KEY:
    raise RuntimeError("OPENROUTER_API_KEY is missing from Colab Secrets")

OPENROUTER_CHAT_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_GENERATION_URL = "https://openrouter.ai/api/v1/generation"

MODELS = {
    "gpt_oss_120b": "openai/gpt-oss-120b",
    "hermes_4_70b": "nousresearch/hermes-4-70b",
    "llama_3_3_70b": "meta-llama/llama-3.3-70b-instruct",
}

LANGUAGE_NAMES = {
    "en": "English",
    "de": "German",
    "fr": "French",
    "pt": "Portuguese",
    "es": "Spanish",
    "ru": "Russian",
}

ALLOWED_CODES = tuple(LANGUAGE_NAMES)
SEGMENTS_PER_LANGUAGE = 25
REQUEST_TIMEOUT_SECONDS = 120
MAX_RETRIES = 4

HEADERS = {
    "Authorization": f"Bearer {OPENROUTER_API_KEY}",
    "Content-Type": "application/json",
}

con = duckdb.connect()
con.execute("SET threads TO 4")
con.execute("SET preserve_insertion_order = false")

def load_language_segments(language_code):
    if language_code not in LANGUAGE_NAMES:
        raise ValueError(language_code)

    frame = con.execute(
        """
        WITH sessions AS (
            SELECT
                gamesession_id,
                url,
                TRY_CAST(created_at AS TIMESTAMP) AS created_at,
                transcript_segments
            FROM read_parquet(?)
            WHERE
                lang_detected = ?
                AND transcript_segments IS NOT NULL
                AND len(transcript_segments) > 0
        ),
        exploded AS (
            SELECT
                gamesession_id,
                url,
                created_at,
                generate_subscripts(transcript_segments, 1) AS segment_index,
                UNNEST(transcript_segments) AS segment
            FROM sessions
        ),
        eligible AS (
            SELECT
                gamesession_id,
                url,
                created_at,
                segment_index,
                TRIM(segment.text) AS segment_text,
                len(
                    regexp_extract_all(
                        TRIM(segment.text),
                        '[\\p{L}\\p{N}]+'
                    )
                ) AS word_count
            FROM exploded
            WHERE
                segment.text IS NOT NULL
                AND TRIM(segment.text) <> ''
        ),
        ranked_sessions AS (
            SELECT
                gamesession_id,
                MAX(created_at) AS created_at,
                COUNT(*) AS eligible_segments
            FROM eligible
            WHERE word_count >= 4
            GROUP BY gamesession_id
            HAVING COUNT(*) >= ?
            ORDER BY created_at DESC NULLS LAST, gamesession_id DESC
            LIMIT 1
        )
        SELECT
            ? AS dataset_language,
            e.gamesession_id,
            e.url,
            e.segment_index,
            e.segment_text
        FROM eligible e
        INNER JOIN ranked_sessions s USING (gamesession_id)
        WHERE e.word_count >= 4
        ORDER BY e.segment_index
        LIMIT ?
        """,
        [
            PARQUET_PATH.as_posix(),
            language_code,
            SEGMENTS_PER_LANGUAGE,
            language_code,
            SEGMENTS_PER_LANGUAGE,
        ],
    ).df()

    if len(frame) != SEGMENTS_PER_LANGUAGE:
        raise RuntimeError(
            f"{language_code}: expected {SEGMENTS_PER_LANGUAGE} segments, found {len(frame)}"
        )

    frame.insert(0, "benchmark_row_id", range(len(frame)))
    return frame

def normalize_prediction(value):
    if not isinstance(value, str):
        return None

    value = value.strip().lower()
    aliases = {
        "english": "en",
        "german": "de",
        "deutsch": "de",
        "french": "fr",
        "français": "fr",
        "francais": "fr",
        "portuguese": "pt",
        "português": "pt",
        "portugues": "pt",
        "spanish": "es",
        "español": "es",
        "espanol": "es",
        "russian": "ru",
        "русский": "ru",
    }

    if value in ALLOWED_CODES:
        return value

    if value in aliases:
        return aliases[value]

    cleaned = value.replace("`", "").replace('"', "").replace("'", "").strip()

    if cleaned in ALLOWED_CODES:
        return cleaned

    if cleaned in aliases:
        return aliases[cleaned]

    for code in ALLOWED_CODES:
        if cleaned.startswith(code + " ") or cleaned.startswith(code + "\n"):
            return code

    return None

def build_payload(model_id, text):
    payload = {
        "model": model_id,
        "messages": [
            {
                "role": "system",
                "content": (
                    "Detect the language of the transcript. "
                    "Return exactly one ISO 639-1 code from: "
                    "en, de, fr, pt, es, ru. No explanation."
                ),
            },
            {
                "role": "user",
                "content": text,
            },
        ],
        "temperature": 0,
    }

    if model_id == "openai/gpt-oss-120b":
        payload["reasoning"] = {"effort": "low"}

    return payload

async def post_chat(session, model_name, model_id, row):
    last_error = None

    for attempt in range(1, MAX_RETRIES + 1):
        started = time.perf_counter()

        try:
            async with session.post(
                OPENROUTER_CHAT_URL,
                headers=HEADERS,
                json=build_payload(model_id, row.segment_text),
            ) as response:
                elapsed = time.perf_counter() - started
                data = await response.json(content_type=None)

                if response.status == 200:
                    message = ((data.get("choices") or [{}])[0].get("message") or {})
                    content = message.get("content")
                    usage = data.get("usage") or {}

                    return {
                        "benchmark_row_id": row.benchmark_row_id,
                        "model_name": model_name,
                        "model_id": model_id,
                        "prediction": normalize_prediction(content),
                        "raw_prediction": content,
                        "generation_id": data.get("id"),
                        "http_status": response.status,
                        "request_duration_seconds": elapsed,
                        "prompt_tokens": usage.get("prompt_tokens"),
                        "completion_tokens": usage.get("completion_tokens"),
                        "total_tokens": usage.get("total_tokens"),
                        "response_cost_usd": usage.get("cost"),
                        "error": None,
                    }

                error = data.get("error")
                last_error = error.get("message") if isinstance(error, dict) else str(error or data)

                if response.status not in {408, 409, 429, 500, 502, 503, 504}:
                    break

                retry_after = response.headers.get("Retry-After")
                delay = float(retry_after) if retry_after else min(30.0, 2 ** attempt + random.random())
                await asyncio.sleep(delay)

        except Exception as exc:
            elapsed = time.perf_counter() - started
            last_error = f"{type(exc).__name__}: {exc}"
            if attempt < MAX_RETRIES:
                await asyncio.sleep(min(30.0, 2 ** attempt + random.random()))

    return {
        "benchmark_row_id": row.benchmark_row_id,
        "model_name": model_name,
        "model_id": model_id,
        "prediction": None,
        "raw_prediction": None,
        "generation_id": None,
        "http_status": None,
        "request_duration_seconds": elapsed,
        "prompt_tokens": None,
        "completion_tokens": None,
        "total_tokens": None,
        "response_cost_usd": None,
        "error": last_error,
    }

async def benchmark_language(language_code):
    segments = load_language_segments(language_code)
    timeout = aiohttp.ClientTimeout(total=REQUEST_TIMEOUT_SECONDS)
    records = []

    async with aiohttp.ClientSession(timeout=timeout) as session:
        for row in segments.itertuples(index=False):
            for model_name, model_id in MODELS.items():
                record = await post_chat(session, model_name, model_id, row)
                records.append(record)

    raw = pd.DataFrame(records)

    predictions = (
        raw.pivot(
            index="benchmark_row_id",
            columns="model_name",
            values="prediction",
        )
        .rename(columns=lambda name: f"openrouter_{name}_language")
        .reset_index()
    )

    result = segments.merge(predictions, on="benchmark_row_id", how="left")
    return result, raw

async def fetch_generation(session, generation_id):
    started = time.perf_counter()

    try:
        async with session.get(
            OPENROUTER_GENERATION_URL,
            headers=HEADERS,
            params={"id": generation_id},
        ) as response:
            lookup_duration = time.perf_counter() - started
            payload = await response.json(content_type=None)

            if response.status != 200:
                return {
                    "generation_id": generation_id,
                    "generation_lookup_http_status": response.status,
                    "generation_lookup_seconds": lookup_duration,
                    "generation_error": str(payload),
                }

            data = payload.get("data") or payload
            return {
                "generation_id": generation_id,
                "generation_lookup_http_status": response.status,
                "generation_lookup_seconds": lookup_duration,
                "generation_model": data.get("model"),
                "generation_provider": data.get("provider_name") or data.get("provider"),
                "generation_prompt_tokens": data.get("tokens_prompt"),
                "generation_completion_tokens": data.get("tokens_completion"),
                "generation_total_cost_usd": data.get("total_cost"),
                "generation_latency_ms": data.get("latency"),
                "generation_generation_time_ms": data.get("generation_time"),
                "generation_error": None,
            }

    except Exception as exc:
        return {
            "generation_id": generation_id,
            "generation_lookup_http_status": None,
            "generation_lookup_seconds": time.perf_counter() - started,
            "generation_error": f"{type(exc).__name__}: {exc}",
        }

async def build_accounting(raw_results):
    source = raw_results[
        raw_results["generation_id"].notna()
    ].copy()

    timeout = aiohttp.ClientTimeout(total=REQUEST_TIMEOUT_SECONDS)
    metadata = []

    async with aiohttp.ClientSession(timeout=timeout) as session:
        for generation_id in source["generation_id"].drop_duplicates():
            metadata.append(await fetch_generation(session, generation_id))

    metadata = pd.DataFrame(metadata)

    if metadata.empty:
        detailed = source.copy()
    else:
        detailed = source.merge(metadata, on="generation_id", how="left")

    summary = (
        detailed.groupby(["model_name", "model_id"], as_index=False)
        .agg(
            api_calls=("generation_id", "size"),
            successful_predictions=("prediction", lambda x: x.notna().sum()),
            prompt_tokens=("prompt_tokens", "sum"),
            completion_tokens=("completion_tokens", "sum"),
            total_tokens=("total_tokens", "sum"),
            response_cost_usd=("response_cost_usd", "sum"),
            request_duration_seconds=("request_duration_seconds", "sum"),
            avg_request_duration_seconds=("request_duration_seconds", "mean"),
            official_generation_cost_usd=("generation_total_cost_usd", "sum"),
            avg_official_latency_ms=("generation_latency_ms", "mean"),
            avg_official_generation_time_ms=("generation_generation_time_ms", "mean"),
        )
    )

    return detailed, summary

print("Ready")
print("Parquet:", PARQUET_PATH)
print("Models :", ", ".join(MODELS))
print("Flow   : run language cells one by one, then accounting cells one by one")

Mounted at /content/drive
Ready
Parquet: /content/drive/MyDrive/Language Detection/sessions_lang_transcript_2026-08-23_2026-08-24.parquet
Models : gpt_oss_120b, hermes_4_70b, llama_3_3_70b
Flow   : run language cells one by one, then accounting cells one by one

In [2]:
english_benchmark, english_raw = await benchmark_language("en")

print("English")
print("Segments:", len(english_benchmark))
print("API calls:", len(english_raw))
print("Successful predictions:", int(english_raw["prediction"].notna().sum()))
print("Failed predictions:", int(english_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(english_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

English
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,en,141268501,https://www.twitch.tv/videos/2854311727,2,"Don't be talking, shut my door.",en,en,en
1,1,en,141268501,https://www.twitch.tv/videos/2854311727,3,We'll start it.,en,en,en
2,2,en,141268501,https://www.twitch.tv/videos/2854311727,4,We'll start with the basics.,en,en,en
3,3,en,141268501,https://www.twitch.tv/videos/2854311727,5,actually showed up. You guys owe me ten bucks.,en,en,en
4,4,en,141268501,https://www.twitch.tv/videos/2854311727,6,"personal. It's just, uh, we're stuck in Groundhog Day out here.",en,en,en
5,5,en,141268501,https://www.twitch.tv/videos/2854311727,7,"trying to, you know, not go crazy..",en,en,en
6,6,en,141268501,https://www.twitch.tv/videos/2854311727,8,"Okay, it's simple really, shout next and the guys will let the survivor in.",en,en,en
7,7,en,141268501,https://www.twitch.tv/videos/2854311727,9,"Next survivor. First, do a simple inspection.",en,en,en
8,8,en,141268501,https://www.twitch.tv/videos/2854311727,10,Take the flashlight from the table.,en,en,en
9,9,en,141268501,https://www.twitch.tv/videos/2854311727,11,Take your time. Match what you see against the symptom chart.,en,en,en
10,10,en,141268501,https://www.twitch.tv/videos/2854311727,12,devil's in the details. Identify the particular ailment and click symptom locked.,en,en,en
11,11,en,141268501,https://www.twitch.tv/videos/2854311727,13,"If you mark most symptoms correctly, you'll get a reward.",en,en,en
12,12,en,141268501,https://www.twitch.tv/videos/2854311727,14,"Once you've recorded the symptoms, time to decide their fate.",en,en,en
13,13,en,141268501,https://www.twitch.tv/videos/2854311727,15,Let's switch to the distribution tab. You are in a quarantine zone.,en,en,en
14,14,en,141268501,https://www.twitch.tv/videos/2854311727,16,Stay calm and wait for your turn. Remove your outer clothing.,en,en,en
15,15,en,141268501,https://www.twitch.tv/videos/2854311727,17,Still not sure. No worries. Just send them into quarantine.,en,en,en
16,16,en,141268501,https://www.twitch.tv/videos/2854311727,18,"Let them sit for a few days, the virus will reveal itself.",en,en,en
17,17,en,141268501,https://www.twitch.tv/videos/2854311727,19,Like a friend of mine used to say. Can't piss in the gas tank.,en,en,en
18,18,en,141268501,https://www.twitch.tv/videos/2854311727,20,"I'm not sure what he meant exactly, your choice may have consequences for the whole camp.",en,en,en
19,19,en,141268501,https://www.twitch.tv/videos/2854311727,21,If you let the wrong one in. What's,en,en,en
20,20,en,141268501,https://www.twitch.tv/videos/2854311727,22,the point of all this? We're all dead already.,en,en,en
21,21,en,141268501,https://www.twitch.tv/videos/2854311727,23,In four days we will be evacuating the survivor's block.,en,en,en
22,22,en,141268501,https://www.twitch.tv/videos/2854311727,24,The top brass will be very upset with us if we don't move a adequate number of healthy people.,en,en,en
23,23,en,141268501,https://www.twitch.tv/videos/2854311727,25,Carefully examine the survivors in the line and send the unaffected on to the block.,en,en,en
24,24,en,141268501,https://www.twitch.tv/videos/2854311727,26,What's the point? Don't make me wait.,en,en,en

In [3]:
german_benchmark, german_raw = await benchmark_language("de")

print("German")
print("Segments:", len(german_benchmark))
print("API calls:", len(german_raw))
print("Successful predictions:", int(german_raw["prediction"].notna().sum()))
print("Failed predictions:", int(german_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(german_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

German
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,de,141192575,https://www.twitch.tv/videos/2852368077,1,"Der kann mich gar nicht erwischt, nie im Leben.",de,de,de
1,1,de,141192575,https://www.twitch.tv/videos/2852368077,2,ich hab's gerade gesehen.,de,de,de
2,2,de,141192575,https://www.twitch.tv/videos/2852368077,3,"Eigentlich hat das Gebäude, als wir offiziell in der Zwiebel waren.",de,de,de
3,3,de,141192575,https://www.twitch.tv/videos/2852368077,4,"Ich seh' halt nicht, keine Ahnung, wo der ist.",de,de,de
4,4,de,141192575,https://www.twitch.tv/videos/2852368077,5,"Irgendwo Richtung Turm drin, irgendwo da hinten, so ein bisschen weiter links.",de,de,de
5,5,de,141192575,https://www.twitch.tv/videos/2852368077,6,"einen haben wir am Tachel, einer ist noch unten drin ja ja da snipet er die Lachen",de,de,de
6,6,de,141192575,https://www.twitch.tv/videos/2852368077,7,"traurige ja gib mir ein Bredi ja ein richtiger Lack jetzt habe ich gepisst das, ich hätte dich geholt",de,de,de
7,7,de,141192575,https://www.twitch.tv/videos/2852368077,8,"ich weiß nicht, hier haben die die selber gibt's das das war das, was du deinen eigenen Strömen liebst warte mal ich schau mal Das ist jetzt Beste.",de,de,de
8,8,de,141192575,https://www.twitch.tv/videos/2852368077,10,"Die hat ja noch einer, jetzt können sie Tank und Psych nochmal.",de,de,de
9,9,de,141192575,https://www.twitch.tv/videos/2852368077,11,"Oh nein, ja er snipet immer noch wo da oben.",de,de,de
10,10,de,141192575,https://www.twitch.tv/videos/2852368077,12,"Kommt der Bresi auf mich? Was bist du nur für ein Hundesohn, echt?",de,de,de
11,11,de,141192575,https://www.twitch.tv/videos/2852368077,13,"Der schaut bei dir aus, bitte. Ich bin hier.",de,de,de
12,12,de,141192575,https://www.twitch.tv/videos/2852368077,14,"Hier, vor überall. Im Turm und so.",de,de,de
13,13,de,141192575,https://www.twitch.tv/videos/2852368077,15,"Ah und eines ist aus der Kirche oben, da war es auch safe. Kein Kind, der den Dinger hat.",de,de,de
14,14,de,141192575,https://www.twitch.tv/videos/2852368077,16,"Müssen wir schauen, dass wir es gleich hier so nachher kriegen.",de,de,de
15,15,de,141192575,https://www.twitch.tv/videos/2852368077,17,"Na! Ja, aber die warten nicht gut. Aber was soll ich machen? Ich halte einen von oben und würde ihn vom Schub fallen.",de,de,de
16,16,de,141192575,https://www.twitch.tv/videos/2852368077,18,werde ihn nicht oft ausschüssen.,de,de,de
17,17,de,141192575,https://www.twitch.tv/videos/2852368077,19,Jetzt ist es dir frei.,de,de,de
18,18,de,141192575,https://www.twitch.tv/videos/2852368077,20,Ich nix zu tun. So ein Pisser echt. Der da da oben umeinander.,de,de,de
19,19,de,141192575,https://www.twitch.tv/videos/2852368077,21,Es dürfte also irgendwie zu irgendwas kommen. Wenn wir kurz beieinander sind.,de,de,de
20,20,de,141192575,https://www.twitch.tv/videos/2852368077,22,"Einer hat nix mehr, der sitzt bei, das hat's unten, das hat's oben scheiße versucht, dass ich aufbekommen.",de,de,de
21,21,de,141192575,https://www.twitch.tv/videos/2852368077,23,"das ja das, ja, hab jetzt versucht zum Ovi-Snipern, aber ich hab den scheiß Sniper unten.",de,de,de
22,22,de,141192575,https://www.twitch.tv/videos/2852368077,24,"Ja, das war klar, das ist nicht mehr scharf jetzt, ich hab, mein, das hat's unten drin.",de,de,de
23,23,de,141192575,https://www.twitch.tv/videos/2852368077,25,"Deswegen hab ich da schon zwei geholt, aber ja, hab ich nicht mitgekriegt.",de,de,de
24,24,de,141192575,https://www.twitch.tv/videos/2852368077,26,"Ich hab, mein, das kommt jetzt Richtung mir, weißt schon, weil ich schon da war. Aber ist ja geil, macht nix.",de,de,de

In [4]:
french_benchmark, french_raw = await benchmark_language("fr")

print("French")
print("Segments:", len(french_benchmark))
print("API calls:", len(french_raw))
print("Successful predictions:", int(french_raw["prediction"].notna().sum()))
print("Failed predictions:", int(french_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(french_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

French
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,fr,141267561,https://www.twitch.tv/videos/2854116559,2,What you guys doing ?,en,en,en
1,1,fr,141267561,https://www.twitch.tv/videos/2854116559,6,What you guys doing ?,en,en,en
2,2,fr,141267561,https://www.twitch.tv/videos/2854116559,7,"Allez mec Attendez Yo Damien, t le premier ?",fr,fr,fr
3,3,fr,141267561,https://www.twitch.tv/videos/2854116559,8,"Ouais sur tiktak t le premier, même sur Twitch je pense En tout cas le premier message Euh, y'en perd pas de temps Aujourd'hui on essaie d'avancer putain de capa de merde Comme ça c'est fait, il nous manquera quoi ?",fr,fr,fr
4,4,fr,141267561,https://www.twitch.tv/videos/2854116559,9,"Là, il'on y s'extraire avec l'autre un, ça nous donnera la peluche, et après il manquera juste l'achantique, et problème de l'achantique, c que je sais pas comment je vais le pour la trouver, mais on va tenter, on va tenter.",fr,fr,fr
5,5,fr,141267561,https://www.twitch.tv/videos/2854116559,10,"Yo Pilouf,'as va ou quoi ? Comment va le Pilouf ?",fr,fr,fr
6,6,fr,141267561,https://www.twitch.tv/videos/2854116559,11,"Allez, ça part comme ça les gars. Un second. Ça raconte quoi Pilouf ?",fr,fr,fr
7,7,fr,141267561,https://www.twitch.tv/videos/2854116559,12,"J'espère que tu vas bien Damien. Ah d'ailleurs, je voulais te faire un truc.",fr,fr,fr
8,8,fr,141267561,https://www.twitch.tv/videos/2854116559,13,"Ah bah tranquille mon Pilouf. J'peux pas t'entendre, j'suis au taf, moi un pouce avec un grand sourire pour me dire bonjour La petit pouce Putain, travailler un dimanche, terrible",fr,fr,fr
9,9,fr,141267561,https://www.twitch.tv/videos/2854116559,14,"Mais putain, Pilouf alors Pilouf tu reprends lundi, enfin demain les cours",fr,fr,fr
10,10,fr,141267561,https://www.twitch.tv/videos/2854116559,15,"Non la semaine pro, putain ok, j'pensais que vous repreniez, mais comment ça se fait La France ils reprennent pas demain ?",fr,fr,fr
11,11,fr,141267561,https://www.twitch.tv/videos/2854116559,16,"Du hommade, ça va ou combat ? Ça ou cobbg ?",fr,fr,fr
12,12,fr,141267561,https://www.twitch.tv/videos/2854116559,17,Attendez vais juste checker un truc Mais je pensais que vous les français vous repreniez déjà demain,fr,fr,fr
13,13,fr,141267561,https://www.twitch.tv/videos/2854116559,18,Je vais voir si ça ça marche,fr,fr,fr
14,14,fr,141267561,https://www.twitch.tv/videos/2854116559,19,Ah nique sa mère je vais juste checker un truc mette à pied Allez go Merci pour le follow mon petit mat Ah c'est mon frère 1 septembre en Putain Putain mais là on déglandeur jusqu'à...,fr,fr,fr
15,15,fr,141267561,https://www.twitch.tv/videos/2854116559,20,Oh mais les la game va être très chiante hein parce que c ici mon extract C'est ici mon extract les gars putain Je dois attendre 20 minutes avant que le train arrive Je tuer les rogues je vais aller me faire les rogues et je vais goûter un peu la zone.,fr,fr,fr
16,16,fr,141267561,https://www.twitch.tv/videos/2854116559,21,"êtes vraiment dégueulasses, pile ouf vous les français, et c'est pour toute la France le 1er septembre ou vous vous avez par zone A baissé là,'autrui de con là.",fr,fr,fr
17,17,fr,141267561,https://www.twitch.tv/videos/2854116559,22,"Je jamais comment ça marche, j'attends que le train arrive les gars, ouais toute la France ok.",fr,fr,fr
18,18,fr,141267561,https://www.twitch.tv/videos/2854116559,23,"C'est terrible là, parce que je peux me faire fumer à tout moment. Attendez.",fr,fr,fr
19,19,fr,141267561,https://www.twitch.tv/videos/2854116559,24,"Waouh, tu vois ? Terrible.",fr,fr,fr
20,20,fr,141267561,https://www.twitch.tv/videos/2854116559,26,Il combien d'heures de jeu ? 7000. 7000 hommes mon petit mate.,fr,fr,fr
21,21,fr,141267561,https://www.twitch.tv/videos/2854116559,27,"En gros chat, si je m'extrais ici, bon ça me donnera une couronne initiale mais c pas ça, ça me donnera l'ourson.",fr,fr,fr
22,22,fr,141267561,https://www.twitch.tv/videos/2854116559,28,"Et après il manquera que le, regardez, que la hache antique.",fr,fr,fr
23,23,fr,141267561,https://www.twitch.tv/videos/2854116559,29,que la chantique et a la capa bon après il juste prendre la voiture et tout les zones c que pour les vacances pas grande ok putain mais le 3 septembre c dingue de reprendre le 3 septembre,fr,fr,fr
24,24,fr,141267561,https://www.twitch.tv/videos/2854116559,30,d'ailleurs faut que'envoie un mille Matt t'es déjà passé sur Twitch toi non?,fr,fr,fr

In [5]:
portuguese_benchmark, portuguese_raw = await benchmark_language("pt")

print("Portuguese")
print("Segments:", len(portuguese_benchmark))
print("API calls:", len(portuguese_raw))
print("Successful predictions:", int(portuguese_raw["prediction"].notna().sum()))
print("Failed predictions:", int(portuguese_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(portuguese_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Portuguese
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,pt,141268410,https://www.twitch.tv/videos/2854267348,1,FUERTA DE RAHIM Ta,es,es,es
1,1,pt,141268410,https://www.twitch.tv/videos/2854267348,2,de pé E Fui FUERTA RAHIM E ASSISTA FUERTA FAZ FUERTA RAHIM FUERTA RAHIM,pt,pt,pt
2,2,pt,141268410,https://www.twitch.tv/videos/2854267348,3,FUERTA RAHIM porta aberta e isso,pt,pt,pt
3,3,pt,141268410,https://www.twitch.tv/videos/2854267348,4,ok então estou bebendo um café hoje seria o dia do chill stream mas essa semana eu não joguei a LoL eu queria jogar a LoL eu queria jogar a LoL o chill stream significa que eu decido então se eu quero jogar LoL eu a LoL e vocês pegam no cu aquele eu mais alto talvez,pt,pt,pt
4,4,pt,141268410,https://www.twitch.tv/videos/2854267348,5,Como você Como você Galaxi?,pt,pt,pt
5,5,pt,141268410,https://www.twitch.tv/videos/2854267348,6,"Você fazendo tudo, você está certo. Como você Pasta?",pt,pt,pt
6,6,pt,141268410,https://www.twitch.tv/videos/2854267348,7,"Como você está? Shadow? Tudo bem, garotos? Razy, como você Tchau garotos, tchau a você bem?",pt,pt,pt
7,7,pt,141268410,https://www.twitch.tv/videos/2854267348,8,"O Urco desde esta manhã, oh Deus, desta manhã...",es,pt,pt
8,8,pt,141268410,https://www.twitch.tv/videos/2854267348,9,"Eu não estava. E saiu também no meu schedule, não sei se você viu.",pt,pt,pt
9,9,pt,141268410,https://www.twitch.tv/videos/2854267348,10,"Que é feito, não mais a Dorari. Mas é a...",pt,pt,pt
10,10,pt,141268410,https://www.twitch.tv/videos/2854267348,12,"Não sei se vocês viram. Período, horário da noite, Não sei se vocês viram.",pt,pt,pt
11,11,pt,141268410,https://www.twitch.tv/videos/2854267348,13,"O vocês pensam? Pensam que é muito mais descomodado, ou pode ficar?",pt,pt,pt
12,12,pt,141268410,https://www.twitch.tv/videos/2854267348,14,"Em sua opinião. Para mim é melhor, porque menos...",pt,pt,pt
13,13,pt,141268410,https://www.twitch.tv/videos/2854267348,15,"Por como eu eu, me ajuda mais com a minha desabilidade, porque eu um pouco desabelhado.",pt,pt,pt
14,14,pt,141268410,https://www.twitch.tv/videos/2854267348,16,"Não, ainda tem a resposta! Caramba!",pt,pt,pt
15,15,pt,141268410,https://www.twitch.tv/videos/2854267348,17,"Era, porque na passada era a resposta. Eu me esqueci de modificar ela.",pt,pt,pt
16,16,pt,141268410,https://www.twitch.tv/videos/2854267348,18,Ah resposta de novo. Porra de Eu me de a resposta por sempre.,pt,pt,pt
17,17,pt,141268410,https://www.twitch.tv/videos/2854267348,19,"Mas por sempre, eu já Porque depois eu me identificarei na semana próxima e deixarei aqui.",pt,pt,pt
18,18,pt,141268410,https://www.twitch.tv/videos/2854267348,20,"Ai meu Residência Residência, residência Ai meu Deus",pt,pt,pt
19,19,pt,141268410,https://www.twitch.tv/videos/2854267348,21,"Apreciamos o que você sabe, eu sei Eu sei, eu sei Eu um pouco estranho",pt,pt,pt
20,20,pt,141268410,https://www.twitch.tv/videos/2854267348,22,"Mas com o domingo sério, entende a durada? uma das duas?",pt,pt,pt
21,21,pt,141268410,https://www.twitch.tv/videos/2854267348,23,"Não, a durada Porque tipo...",pt,pt,pt
22,22,pt,141268410,https://www.twitch.tv/videos/2854267348,24,"Era domingo tarde Mas eu sei como escrever O início da manhã, o início da manhã era a 19h, que eu sei, manhã, na Poderia escrever a manhã,",pt,pt,pt
23,23,pt,141268410,https://www.twitch.tv/videos/2854267348,25,Mas sim. sim. Dois stream de fila.,pt,pt,pt
24,24,pt,141268410,https://www.twitch.tv/videos/2854267348,26,"Bem, é a domenical. Ah, você diz por dois dias de fila.",pt,pt,pt

In [6]:
spanish_benchmark, spanish_raw = await benchmark_language("es")

print("Spanish")
print("Segments:", len(spanish_benchmark))
print("API calls:", len(spanish_raw))
print("Successful predictions:", int(spanish_raw["prediction"].notna().sum()))
print("Failed predictions:", int(spanish_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(spanish_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Spanish
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,es,141268448,https://www.twitch.tv/videos/2853628924,1,hola hola que tal gente silla estamos aquí otra vez un día más vamos al charlando,es,es,es
1,1,es,141268448,https://www.twitch.tv/videos/2853628924,2,hello como estáis como estáis ahora estoy bastante cansada pero tengo una cosa aquí estamos aquí cumplimos vale pues hoy vamos a jugar a los dinosaurios que me apetece un ratito aunque sea y ya luego vamos al balo en un ratito hoy no me quedaré mucho porque me apetece estar más en la gama todo esto me hecho una siesta cuando he llegado,es,es,es
2,2,es,141268448,https://www.twitch.tv/videos/2853628924,3,de tres horas y claro una mañana que hay que trabajar entonces prefiero irme tempranito que sabemos como acaba de irse tempranito pero bueno lo cuento igual.,es,es,es
3,3,es,141268448,https://www.twitch.tv/videos/2853628924,4,eh... Vale. ¿Dónde está? ¿Dónde está?,es,es,es
4,4,es,141268448,https://www.twitch.tv/videos/2853628924,6,"Let's go. Vamos allá, continúen.",es,es,es
5,5,es,141268448,https://www.twitch.tv/videos/2853628924,7,"Vale, voy limpiar un momentito rápido el teclado.",es,es,es
6,6,es,141268448,https://www.twitch.tv/videos/2853628924,9,"Pero no lo que tenía que hacer, tipo, las dos canastas y los ladrillos de piedra vale,",es,es,es
7,7,es,141268448,https://www.twitch.tv/videos/2853628924,10,"ehm, los de piedra y las dos canastas, tengo que hacer nooo, una planta por la puta,",es,es,es
8,8,es,141268448,https://www.twitch.tv/videos/2853628924,11,"falta una planta ah ya tengo las dos vale, ok, eh vamos a reunirnos con Bryce",es,es,es
9,9,es,141268448,https://www.twitch.tv/videos/2853628924,12,"¿Por qué hay emisiones? ¿Qué más tenían? Aumentar la población, pero eso lo vas diciendo poco a",es,es,es
10,10,es,141268448,https://www.twitch.tv/videos/2853628924,13,Vamos... ¡Eh! ¡Estamos en invierno! ¿Por qué por el primavera ya está nevando?,es,es,es
11,11,es,141268448,https://www.twitch.tv/videos/2853628924,14,"Enchiendo. ¿Vamos dónde, Bryce?",es,es,es
12,12,es,141268448,https://www.twitch.tv/videos/2853628924,15,"Vale, esto de que...",es,es,es
13,13,es,141268448,https://www.twitch.tv/videos/2853628924,16,Pero ¿por qué está nevando? una pregunta muy sería,es,es,es
14,14,es,141268448,https://www.twitch.tv/videos/2853628924,17,vale vamos para arriba,es,es,es
15,15,es,141268448,https://www.twitch.tv/videos/2853628924,18,a la monta de las sierras altas ahora pensé que podía haberte peado ok vale pero me escucho una cosa madre mía,es,es,es
16,16,es,141268448,https://www.twitch.tv/videos/2853628924,19,esto que seguir subiendo que locura este buenos días che,es,es,es
17,17,es,141268448,https://www.twitch.tv/videos/2853628924,20,creo que no nos habíamos hasta ahora. Soy Mina.,es,es,es
18,18,es,141268448,https://www.twitch.tv/videos/2853628924,21,"Mina Fotazas. Este juego me vacila, pero grandes rasgos.",es,es,es
19,19,es,141268448,https://www.twitch.tv/videos/2853628924,22,La verdad. El objetivo más rápido de todo el archipiélago.,es,es,es
20,20,es,141268448,https://www.twitch.tv/videos/2853628924,23,"Tengo que ser de hablar de mí, pero eso es porque se me da requetiría en mi trabajo. Soy súper sigilosa.",es,es,es
21,21,es,141268448,https://www.twitch.tv/videos/2853628924,24,"Me expedizo en fotos analógicas de piezos, espontáneos desmedidos, fated, así decirlo.",es,es,es
22,22,es,141268448,https://www.twitch.tv/videos/2853628924,25,"Potentes auténticas para los profanos, la vida real, vaya. Y ahora, si me disculpas, tengo que esperar a ciertos sitios.",es,es,es
23,23,es,141268448,https://www.twitch.tv/videos/2853628924,26,"Esta isla está lista para la cosecha. No olvides llamar a tíos a algún contratiempo, ché.",es,es,es
24,24,es,141268448,https://www.twitch.tv/videos/2853628924,27,"Coño 18. Ok, vamos a hablar con Bryce.",es,es,es

In [7]:
russian_benchmark, russian_raw = await benchmark_language("ru")

print("Russian")
print("Segments:", len(russian_benchmark))
print("API calls:", len(russian_raw))
print("Successful predictions:", int(russian_raw["prediction"].notna().sum()))
print("Failed predictions:", int(russian_raw["prediction"].isna().sum()))

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(russian_benchmark)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

Russian
Segments: 25
API calls: 75
Successful predictions: 75
Failed predictions: 0

,benchmark_row_id,dataset_language,gamesession_id,url,segment_index,segment_text,openrouter_gpt_oss_120b_language,openrouter_hermes_4_70b_language,openrouter_llama_3_3_70b_language
0,0,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,2,"ДИНАМИЧНАЯ Ooh-ooh, kiss my shit, kiss my",ru,ru,ru
1,1,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,3,"shit I heard you were talking shit And you didn't think that I would hear it People hear you talking, like",en,en,en
2,2,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,6,"Так я не понимаю, нахуй он сначала девочек за бодашкой врубил?",ru,ru,ru
3,3,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,7,"Чад, всем дарова, всем... Ты что, реально врубил, придурок? Блять, ты ебла нахуй, нахуй ты меня трахаешь, ебанашка Ростян, он реально врубил, Ростян?",ru,ru,ru
4,4,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,8,"Да, я врубил Да Короче, дарова, Чад, привет, всем Ну вот, так вам скажу, нас сегодня распаковка анимешных фигурок, анимешных фигурок из магазина popo-man или popo-ma popo-me-me-me вот",ru,ru,ru
5,5,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,9,"а, оффот? пишут, пишут, оффот, не надо стримить всё, тогда оффо, нахуй, чад, спасибо, всем пока короче, взяли конструктивного компотика, ну, такого рационального правильного, вкусного собрались в небольшой компании рациональных людей это окей Юра окей вот Юра вот Леша вот",ru,ru,ru
6,6,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,10,Рациональный Леша нас сегодня Леша нас сегодня диджей Леша диджей и Растян с танком Растян с танком я тебя могу вот что будет так что то попьем пивка распакуем игрушки и ляжем спать вот все не знаю кто спать сегодня денечек такой не сбылся,ru,ru,ru
7,7,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,11,спирит проебали блять моя ставка проебала блять сколько 30 6 тысяч 136 тысяч,ru,ru,ru
8,8,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,12,"Да, Санька, Санька, займись, Саша, займись.",ru,ru,ru
9,9,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,13,"Вот, потихоньку кое-что, пивасик сейчас поглушим и распакуем.",ru,ru,ru
10,10,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,14,"Ну, пожалуй, я думаю сейчас надо самое главное это обсудить...",ru,ru,ru
11,11,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,15,"Бля, давайте может столик поставим, чтобы можно... Обсудить, что ты сказал в моем тиктоке за предку?",ru,ru,ru
12,12,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,16,"Мы можем сейчас обсудить игру, прошлую игру.",ru,ru,ru
13,13,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,17,"А чемодан на хуя? Эту камеру слабо стоять не надо ходить, Ээээ из-за кадра поставь Вот, там будем сидеть Нет?",ru,ru,ru
14,14,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,18,"Или пусть не так-то старей стоит? Не, ну всё это туда ладно, подологично Как это называется?",ru,ru,ru
15,15,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,19,"Соджу Соджу Нормально или в руках будем держать? Не, туда Вместо одного держать в руках Чё, короче, вот тут посидите",ru,ru,ru
16,16,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,20,"Блядь, Лёшка нахуй Ну ты вообще блядь диджей ебучий, блядь, Лёш Ну ты вообще Какой засрали нет не бать все тебе респект кидают тут тебе все все все респект кидают",ru,ru,ru
17,17,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,21,"Тут тебе все все тут тебе все кидают респекта блядь жесткий Все я поставил я поставил камеру так чтобы танка тоже было видно Смотрите нормальную музыку Ха-ха-ха Напишите как видно меня, нормально?",ru,ru,ru
18,18,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,22,"Вот руку поднимаю Видно нормально там? Давайте пока въебём Вот как въебём А, выпить Господи, ебаные завозы Дура, вообще как въебутая Давай, давай сейчас въебём",ru,ru,ru
19,19,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,23,"Постопаливай Не, не, не Стой!",ru,ru,ru
20,20,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,25,Тут даже я разъят! Чем глоток выпил?,ru,ru,ru
21,21,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,26,"Глоток! Глоток! Расфибала, сокай! Красава!",ru,ru,ru
22,22,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,27,"Красава! Сокай тебя разфибала, понимаешь? Так, хочу себе в сокачки пиво налить, ладно?",ru,ru,ru
23,23,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,28,"Смотрите, со самого прочести я, блядь, замолвался! Стой, стой, стой.",ru,ru,ru
24,24,ru,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,29,"Стой, стой. Стой, Так, ладно, давайте, вытем за то, чтобы здесь, прочим, подлечилась задача.",ru,ru,ru

In [8]:
english_accounting, english_accounting_summary = await build_accounting(english_raw)

print("English accounting")
display(english_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        english_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

English accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,2851,861,3712,0.000443,28.721710,1.148868,0.000443,713.72,1378.16
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,1525,50,1575,0.000218,7.567468,0.302699,0.000218,86.64,90.72
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,1608,50,1658,0.000309,34.270741,1.370830,0.000309,474.48,563.64

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715906-3UQDdIb0GsGcdmlVMw7n,112,47,159,0.000022,1.164887,DigitalOcean,39,40,0.000022,501,1971,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715908-KAopK5LePcuYUjpDNnPZ,57,2,59,0.000008,0.436420,Nebius,39,1,0.000008,85,88,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715909-4WZQrzUa2zJbFq2Xtaa9,57,2,59,0.000006,0.377182,DeepInfra,82,1,0.000006,268,296,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715909-GSPiwGbglJwm6b8TcarY,111,22,133,0.000015,1.235745,SiliconFlow,35,19,0.000015,1163,3127,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715913-ABBzfTzDkOcA7jV4sThw,53,2,55,0.000008,0.330974,Nebius,35,1,0.000008,78,79,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715913-lmrbGOQfOJh1F2tJUYMH,53,2,55,0.000006,5.619453,DeepInfra,78,1,0.000006,363,399,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715919-ZKNa39jDMxXvCOe4HE3N,113,30,143,0.000008,1.060940,AkashML,38,21,0.000008,536,1016,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715921-MMESpiHwTIDpI97MrSYy,55,2,57,0.000008,0.289083,Nebius,38,1,0.000008,85,86,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715923-bAxvblmotrB5XRHIp9qu,55,2,57,0.000006,2.563894,DeepInfra,81,1,0.000006,519,555,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715924-igPWWniXmf85wy1odAQQ,118,34,152,0.000021,1.199970,SiliconFlow,42,35,0.000021,1047,2343,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715927-6qVi626pwVTCpgA0yWy4,59,2,61,0.000008,0.279889,Nebius,42,1,0.000008,79,82,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715927-k1qJUorFpTPDJjWPgAsx,79,2,81,0.000048,0.272907,Groq,85,1,0.000048,75,75,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715927-EzIiwQYmGvRgbURXTk8e,122,57,179,0.000020,2.005108,Novita,47,46,0.000020,471,996,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715930-Xr4jsYvwDyOVJB09q4iq,66,2,68,0.000009,0.301344,Nebius,47,1,0.000009,92,96,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715930-nBC3CYeElAI1CfTINJX7,66,2,68,0.000007,5.610141,DeepInfra,90,1,0.000007,474,516,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715936-RX60A09SnoCs6HejmBb0,104,41,145,0.000011,0.475743,DeepInfra,40,28,0.000011,771,1584,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715938-caM0GceAIteKBOUixA24,58,2,60,0.000008,0.298355,Nebius,40,1,0.000008,83,84,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715938-3qZsWoPeLixu83WT8miB,58,2,60,0.000006,0.376970,DeepInfra,83,1,0.000006,445,495,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715939-oPlUjszmVzsTMofs0nc3,123,41,164,0.000016,2.022117,Novita,50,30,0.000016,474,882,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715941-XdFz91gY9wByGno3Iy9I,66,2,68,0.000009,0.275363,Nebius,50,1,0.000009,81,85,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715942-2IkViuMNyjfZ1aQilbcI,67,2,69,0.000018,0.421696,Crusoe,93,1,0.000018,251,377,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715942-sxtXwPY0YxUOvWA1AVXh,104,37,141,0.000010,0.522397,DeepInfra,42,30,0.000010,561,1497,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715944-BQgoJBc8QqCEKVdtoVoi,58,2,60,0.000008,0.269555,Nebius,42,1,0.000008,76,78,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715944-uMUB3KHVY8OISXSamI6y,58,2,60,0.000006,0.359379,DeepInfra,85,1,0.000006,765,797,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715945-YFiaC86PYyljSCAXPVTX,113,40,153,0.000016,0.659009,Novita,40,31,0.000016,493,662,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715946-vgSDAQrfom4gQX40OB4B,55,2,57,0.000008,0.286299,Nebius,40,1,0.000008,82,84,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715947-LBkfE1evDBiUOsx9YGF6,55,2,57,0.000006,0.359898,DeepInfra,83,1,0.000006,404,451,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715947-gyK1GxQpWn4SRh4JS8Gs,120,39,159,0.000010,1.666718,AkashML,46,32,0.000010,1501,1998,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715950-pB92qw8ACxE0HCeuODG2,61,2,63,0.000009,0.376434,Nebius,46,1,0.000009,150,150,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715950-4fYppKwnRgf73V793lBb,81,2,83,0.000028,0.367870,Cloudflare,89,1,0.000028,235,235,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715950-p9HaBkO0JpdZi7MLCPnZ,124,46,170,0.000012,0.820393,AkashML,51,41,0.000012,638,1375,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715952-anfzFbHngdAtnUIgC2Qr,64,2,66,0.000009,0.342048,Nebius,51,1,0.000009,137,188,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715953-EpmLIGkJfmixjDKZatEy,64,2,66,0.000007,1.148839,DeepInfra,94,1,0.000007,2777,2885,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715956-0owuIdDsQMoExaxqWA7H,106,25,131,0.000008,0.442991,DeepInfra,45,17,0.000008,502,1030,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715957-UHZaUkmteSilxww6ZyCg,61,2,63,0.000009,0.284495,Nebius,45,1,0.000009,84,88,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715957-JO9iLFQehMFCZviuTCLo,61,2,63,0.000007,0.363214,DeepInfra,88,1,0.000007,299,360,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715958-wzqtYvvcUG8aR2a23UuD,106,44,150,0.000011,2.111911,DeepInfra,46,36,0.000011,439,1718,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715962-vpJ4y6KJo21nJQJH1Y7W,61,2,63,0.000009,0.300063,Nebius,46,1,0.000009,90,90,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715962-snXUA6wm8iVbB89rS5vF,61,2,63,0.000007,0.355438,DeepInfra,89,1,0.000007,728,935,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715963-3bGMj9q14cyaU51Ue0KO,118,20,138,0.000030,0.771083,Nebius,48,10,0.000030,218,257,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715964-cOBEvyDHeoB9sbNZTOCi,63,2,65,0.000009,0.279102,Nebius,48,1,0.000009,79,81,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715964-7FndafZ2NoKnwqkoGUMA,63,2,65,0.000007,0.358747,DeepInfra,91,1,0.000007,214,240,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715965-ATUZtyxnrBPyiGDG8Nxk,120,33,153,0.000021,1.576332,SiliconFlow,46,31,0.000021,1685,3657,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715969-GcfZWUC8r2atVvTyqIxd,61,2,63,0.000009,0.300207,Nebius,46,1,0.000009,83,83,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715969-qCYddfzTqnceclPCi3J3,61,2,63,0.000007,6.982052,DeepInfra,89,1,0.000007,739,1600,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715977-hYAPEQoDuAkKFZFoq4Pq,107,45,152,0.000012,0.448987,DeepInfra,46,35,0.000012,601,2052,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715980-e4b2exI5cRRoiTMQ5bhO,61,2,63,0.000009,0.368011,Nebius,46,1,0.000009,82,82,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715980-AqOL5K9bK4Tf031DIarv,61,2,63,0.000007,0.356403,DeepInfra,89,1,0.000007,478,696,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715981-bf2c1vqsLPEACzdzhJVC,104,46,150,0.000026,0.554045,Google,45,36,0.000026,347,416,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715982-509d6f9CsPDK3v3X7PGd,62,2,64,0.000009,0.274392,Nebius,45,1,0.000009,82,86,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715982-BmhQmZNhsW5DiTNLPGeX,63,2,65,0.000017,0.408387,Crusoe,88,1,0.000017,250,321,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715982-jHR6mFyhV8cwOpvSuSKy,123,25,148,0.000033,0.289291,Groq,46,18,0.000033,75,100,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715983-pIE2ctHVh1ffRvQt8Yk6,65,2,67,0.000009,0.269030,Nebius,46,1,0.000009,76,79,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715983-h5as4LMlyL71cc1j99vp,65,2,67,0.000007,0.372898,DeepInfra,89,1,0.000007,522,574,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715984-cysCKIBVhWdqHLdOxwN2,125,25,150,0.000020,3.809604,Google,53,18,0.000020,3599,3610,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715988-l1l81fUrS1dH4dnkz1P5,67,2,69,0.000010,0.309492,Nebius,53,1,0.000010,90,92,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715988-54jgHJQV1VFR6UtNbBm1,68,2,70,0.000018,0.407359,Crusoe,96,1,0.000018,260,366,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715989-DSO1SbW546dDpWamGkCq,103,19,122,0.000027,0.351530,DeepInfra,40,9,0.000027,474,655,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715989-OjJjzyoesz0wLKTT8fA0,58,2,60,0.000008,0.305141,Nebius,40,1,0.000008,90,93,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715990-3X0hxIDN3TE3hK0RGpm1,58,2,60,0.000006,5.582235,DeepInfra,83,1,0.000006,248,274,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715996-ITp4qbwUQtKRfln17mdy,115,18,133,0.000028,0.291780,Nebius,42,8,0.000028,89,126,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715996-kcB07X69yb9IRchxw1Gj,60,2,62,0.000009,0.279193,Nebius,42,1,0.000009,72,76,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715996-QGJU0FQrTT7XkUBTbtEk,80,2,82,0.000028,0.261600,Cloudflare,85,1,0.000028,180,180,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787715997-2TzjQK4JbbmX4hu5FnG7,120,26,146,0.000029,2.078004,Parasail,45,18,0.000029,242,357,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787715999-KVz2jlHnckvUArZGFjuh,61,2,63,0.000009,0.275251,Nebius,45,1,0.000009,80,82,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787715999-PRWTKZa2mEvUTlytm7Jg,61,2,63,0.000007,0.352697,DeepInfra,88,1,0.000007,375,412,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716000-eV1wH0ktuVGPqE3Qzqlx,126,61,187,0.000022,2.238319,Novita,54,54,0.000022,476,1262,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716003-rSLwj7pzKDaeMojZ4L3g,69,2,71,0.000010,0.277326,Nebius,54,1,0.000010,79,82,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716003-53jTqLgB6gKpUnnIVjGI,89,2,91,0.000031,0.260692,Cloudflare,97,1,0.000031,158,158,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716004-P7r7yHjDT1LRBzfxZoe8,111,20,131,0.000008,0.431567,DeepInfra,52,10,0.000008,455,807,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716005-lsFZMWfswq7xkIJoqLUj,65,2,67,0.000009,0.291636,Nebius,52,1,0.000009,76,76,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716005-Nly9S4xqjRvSwDdWDGcZ,65,2,67,0.000007,0.354444,DeepInfra,95,1,0.000007,383,409,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716005-jUcTBXYpw64eTzzPtkl9,103,20,123,0.000007,0.493238,DeepInfra,40,10,0.000007,485,956,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716007-1HxApzcmlvRUsYsgAhWV,59,2,61,0.000008,0.268362,Nebius,40,1,0.000008,75,78,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716007-eTdayGmDJdIRytwNYNWb,59,2,61,0.000007,0.376346,DeepInfra,83,1,0.000007,452,485,None

In [9]:
german_accounting, german_accounting_summary = await build_accounting(german_raw)

print("German accounting")
display(german_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        german_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

German accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,2972,819,3791,0.000487,19.207319,0.768293,0.000487,598.44,1339.16
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,1716,50,1766,0.000243,7.539199,0.301568,0.000243,97.88,105.04
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,1961,50,2011,0.000456,14.492114,0.579685,0.000456,572.08,639.44

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716042-PAfll9sLyc2SuoIq8fD1,119,25,144,0.000040,0.949155,SambaNova,43,17,0.000040,740,746,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716043-ggN7DAXP7ueOB68PjN68,61,2,63,0.000009,0.275257,Nebius,43,1,0.000009,85,88,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716044-lr1bqrYdnMRSJi6OLHAn,81,2,83,0.000016,0.988406,AkashML,86,1,0.000016,461,768,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716045-qZUcnWScZ4rikuFsScXr,112,39,151,0.000015,2.113512,Novita,37,29,0.000015,446,752,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716047-h7WvbcgXo9srsh3GPMDz,55,2,57,0.000008,0.259877,Nebius,37,1,0.000008,77,84,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716048-ibOLMuK2gsPJgvt34GXK,56,2,58,0.000016,0.410431,Crusoe,80,1,0.000016,258,354,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716048-yD2W3vfQu2lvbIRCcAXr,123,49,172,0.000028,1.576066,SiliconFlow,48,49,0.000028,1157,3853,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716053-rAF7V8ohQoCr1eSZ7h1w,69,2,71,0.000010,0.272042,Nebius,48,1,0.000010,79,85,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716053-BxvgAoSmcBh63zZwMtUn,69,2,71,0.000008,0.337635,DeepInfra,91,1,0.000008,341,376,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716054-PmVDeSd3G3nQLgkKtZ7f,117,54,171,0.000025,0.665131,DigitalOcean,42,41,0.000025,536,1729,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716056-t9kJceQsgQHXRkQ8gL5d,62,2,64,0.000009,0.638440,Nebius,42,1,0.000009,121,137,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716056-uAhJz0LGZn0DaUMxXtKT,62,2,64,0.000007,0.671708,DeepInfra,85,1,0.000007,228,252,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716057-bwEKmaPfvh8IqFfO6iI4,113,21,134,0.000008,0.779229,DeepInfra,50,11,0.000008,580,1018,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716058-rbNPwkZynKtI6BJ8ubXV,73,2,75,0.000010,0.303596,Nebius,50,1,0.000010,109,113,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716059-FitpAwe9jQ4uPUWrZWm9,74,2,76,0.000054,0.350957,CoreWeave,93,1,0.000054,206,206,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716059-IeoaVWDgsUREm861IxD8,117,26,143,0.000009,0.488428,DeepInfra,51,16,0.000009,712,1216,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716060-pwESXwVmV8aipOsLVBJr,72,2,74,0.000010,0.273357,Nebius,51,1,0.000010,75,81,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716061-aZz8RQ0S8YsKTDNyCa2g,92,2,94,0.000031,0.473264,Cloudflare,94,1,0.000031,375,378,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716061-8MfkxggvWXP9di4gHkm7,120,13,133,0.000007,0.569458,DeepInfra,57,3,0.000007,590,825,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716062-5kaAAoQepbvDUd0EjZAU,75,2,77,0.000011,0.267652,Nebius,57,1,0.000011,83,88,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716063-VNSbFeX6CMy67sSsvTG8,75,2,77,0.000008,0.346158,DeepInfra,100,1,0.000008,3646,4465,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716067-vjneJuiwZhPTiHRfNpt2,131,30,161,0.000010,0.410908,DeepInfra,68,18,0.000010,666,1434,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716069-LL7gO87rZz3BL6dIdsHW,86,2,88,0.000012,0.348316,Nebius,68,1,0.000012,164,168,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716069-NuI5BvxQKytBB7hBnQhs,106,2,108,0.000021,0.869006,AkashML,111,1,0.000021,693,848,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716070-Dvf1c9IXnzL9l05BEBr0,104,26,130,0.000019,1.113492,Google,47,17,0.000019,568,620,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716072-bekVkLtCrYU97SWqukwn,63,2,65,0.000009,0.272126,Nebius,47,1,0.000009,73,76,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716072-rXqP90542bCxgjoMotop,83,2,85,0.000013,1.362565,AkashML,90,1,0.000013,1186,1188,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716073-T9TGLh0UAz06Rh4NiX6s,108,48,156,0.000012,0.588682,DeepInfra,42,34,0.000012,638,1614,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716075-ljCBGsoZrYJhUa3PhDX7,63,2,65,0.000009,0.267791,Nebius,42,1,0.000009,81,86,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716075-UQmBDq0gimFJumj97NNY,64,2,66,0.000015,0.582091,Parasail,85,1,0.000015,422,422,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716076-RW9jd4XQgVcva0pMnpxa,114,30,144,0.000009,0.717580,DeepInfra,48,18,0.000009,796,1631,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716078-wQM1lHXhRL1wAyFOo4EJ,68,2,70,0.000010,0.557362,Nebius,48,1,0.000010,359,366,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716078-qrkNx3gjlqNt6mGogq37,69,2,71,0.000016,0.545444,Parasail,91,1,0.000016,360,360,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716079-s8uMRaAZqYx6eBwcN2EJ,106,30,136,0.000009,0.524801,DeepInfra,42,18,0.000009,529,1286,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716081-Fg6ELQWErj7pnwJCyKEa,61,2,63,0.000009,0.274262,Nebius,42,1,0.000009,85,90,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716081-4xAkiXjMyk6oMwLDxEqP,81,2,83,0.000028,0.307249,Cloudflare,85,1,0.000028,240,240,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716081-55yhIZhq9jtHvZkTEcPo,118,43,161,0.000025,1.506816,SiliconFlow,40,42,0.000025,1086,2927,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716085-CTiWvZjQFVuUArMw6MXw,60,2,62,0.000009,0.273077,Nebius,40,1,0.000009,76,81,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716085-7ZTl89hoWkau6HvyewFw,80,2,82,0.000012,0.851284,AkashML,83,1,0.000012,673,673,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716086-sGELjRaIyPvKaBsLNy7V,118,13,131,0.000007,0.503890,DeepInfra,53,3,0.000007,471,698,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716087-zuNAnkv3TLpZWxGKZZDt,74,2,76,0.000010,0.265699,Nebius,53,1,0.000010,77,82,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716087-b1XMYMzDm9mWdur0ljvL,94,2,96,0.000015,0.537421,AkashML,96,1,0.000015,364,364,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716088-vzlrfGaIJQgGLG3KsiCs,121,13,134,0.000026,0.298021,Nebius,47,3,0.000026,108,137,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716088-2H9y3q5f2iU0cOO7PA4G,66,2,68,0.000009,0.261388,Nebius,47,1,0.000009,76,129,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716088-9XIarV4UQlgqUId4giVF,66,2,68,0.000007,0.343979,DeepInfra,90,1,0.000007,377,422,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716089-eDKq0bvdREFvOc0bAu18,133,43,176,0.000022,0.592583,DigitalOcean,61,28,0.000022,504,1523,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716091-q3NjyaX6snS4xt1p5CJS,79,2,81,0.000011,0.280038,Nebius,61,1,0.000011,89,94,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716091-3LZm2EukQpMptH5nu4Zh,79,2,81,0.000009,0.361487,DeepInfra,104,1,0.000009,432,508,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716092-4uOMXy9AGvKtNq8lZHpr,103,25,128,0.000008,0.430350,DeepInfra,40,11,0.000008,421,987,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716093-EC76muNybKLUFY9835rS,57,2,59,0.000008,0.281435,Nebius,40,1,0.000008,86,92,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716093-107vNNbbhSwipekNjhId,57,2,59,0.000006,0.351805,DeepInfra,83,1,0.000006,403,433,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716094-xjglwe10XJwxESRR5527,113,30,143,0.000035,0.247538,Groq,36,20,0.000035,45,90,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716094-IpYaPzwp6SErSp6J9S6L,55,2,57,0.000008,0.266263,Nebius,36,1,0.000008,74,79,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716094-WlJze9ksrkhspJlaMrcm,75,2,77,0.000011,0.935685,AkashML,79,1,0.000011,653,655,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716095-o3tVPMTFRwmnTwdAkUlm,125,25,150,0.000028,0.547990,Parasail,46,16,0.000028,360,484,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716096-mneBjKkucQw4pswdePOt,69,2,71,0.000010,0.269971,Nebius,46,1,0.000010,77,84,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716096-mOY5ITu7mmmdbo1ZWbdg,70,2,72,0.000015,0.587460,Parasail,89,1,0.000015,413,413,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716097-POhIqHky5XKZZD1L8qh8,124,52,176,0.000030,1.370592,SiliconFlow,51,55,0.000030,1227,2435,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716100-JMZGJrPlBxA0cPIPEhJ9,68,2,70,0.000010,0.268791,Nebius,51,1,0.000010,85,86,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716100-HRqhDLPTdgBZtVYXjceC,68,2,70,0.000007,0.337270,DeepInfra,94,1,0.000007,254,283,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716100-zlG38HArrzVYLbZIih3C,120,25,145,0.000020,0.559048,Google,58,16,0.000020,411,466,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716101-KG4fslheSKKvDkxKqNKJ,81,2,83,0.000011,0.272720,Nebius,58,1,0.000011,82,85,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716102-dCVgiYxBZFH2qnBmh4KG,101,2,103,0.000016,0.860530,AkashML,101,1,0.000016,692,692,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716102-vHxSiZDuHf3aiFWNiPFR,120,29,149,0.000009,0.452233,DeepInfra,54,16,0.000009,519,1387,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716104-Mgga1HsFuNOtdFGb6Njb,74,2,76,0.000010,0.280303,Nebius,54,1,0.000010,83,86,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716104-rBA3NcyXEP3K5EUuHMt3,94,2,96,0.000069,0.428425,Google,97,1,0.000069,234,259,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716105-jd41D7ZsAMLxJwGKVF7X,132,55,187,0.000031,1.132243,SiliconFlow,53,48,0.000031,1056,3490,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716109-e8cKJvwhC6MabqTTO17L,75,2,77,0.000011,0.279723,Nebius,53,1,0.000011,88,93,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716109-OrOOyi9pJtXKpK8SHR6T,95,2,97,0.000032,0.368296,Cloudflare,96,1,0.000032,273,273,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716109-cvdHhs8wgfGcNGUvFfCD,125,45,170,0.000022,0.571364,DigitalOcean,49,32,0.000022,461,1600,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716111-UeTA5yZCNvCoIaiG9UDf,71,2,73,0.000010,0.265872,Nebius,49,1,0.000010,83,88,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716111-UnjCwvU3tVmdtGEkXRsp,91,2,93,0.000014,0.936195,AkashML,92,1,0.000014,761,761,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,de,gen-1787716112-YHdFx29mG27090AjGjfw,136,30,166,0.000033,0.498211,Parasail,59,18,0.000033,334,531,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,de,gen-1787716113-WD37wKnEfFEbxvrEqClG,79,2,81,0.000011,0.263841,Nebius,59,1,0.000011,80,85,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,de,gen-1787716113-CpARR0oKnDKvzzr5WmQu,79,2,81,0.000009,0.347361,DeepInfra,102,1,0.000009,357,393,None

In [10]:
french_accounting, french_accounting_summary = await build_accounting(french_raw)

print("French accounting")
display(french_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        french_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

French accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,3239,777,4016,0.000415,28.326166,1.133047,0.000415,757.00,1358.48
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,1946,50,1996,0.000273,9.139899,0.365596,0.000273,147.40,152.52
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,1975,48,2023,0.000359,34.557636,1.382305,0.000359,761.92,804.76

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716140-pZAUFP8xovY6W17zARsp,109,34,143,0.000017,0.843087,DigitalOcean,36,24,0.000017,668,1479,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716142-vrh3FCN8y5XOn1PAokkg,53,2,55,0.000008,0.626319,Nebius,36,1,0.000008,420,425,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716143-M9BIB76DctYXpaKjqyBU,54,2,56,0.000013,5.918475,Parasail,79,1,0.000013,459,459,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716149-RQKzMVGcI6mv84b8bbGE,109,34,143,0.000017,0.804269,DigitalOcean,36,21,0.000017,665,1612,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716151-3ODYDIlGKyWB5JZbCgQP,53,2,55,0.000008,0.704097,Nebius,36,1,0.000008,169,171,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716151-BS3UOXd33rGgfcZabvFY,53,2,55,0.000006,5.610390,DeepInfra,79,1,0.000006,244,268,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716157-LA6OPhkTp7FtD54YiwXk,106,40,146,0.000011,0.869716,DeepInfra,42,30,0.000011,521,1766,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716159-26bFnDZpf5g0mvl2vhee,60,2,62,0.000009,0.302204,Nebius,42,1,0.000009,78,78,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716160-xEHMyIgEMlNbnrCIeu0R,61,2,63,0.000013,3.012991,Parasail,85,1,0.000013,420,420,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716163-gTnvNIHnui4d1vC0KpKW,163,37,200,0.000017,0.779961,Novita,85,26,0.000017,586,767,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716164-XQUyHtdewHjBmYGapgIc,110,2,112,0.000015,0.359603,Nebius,85,1,0.000015,153,154,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716164-KzrIbxm8XVPn3OOIve9R,110,2,112,0.000012,0.712874,DeepInfra,128,1,0.000012,403,441,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716165-5sMJPNAmyDOkzx1KyfQ0,159,25,184,0.000010,0.901030,DeepInfra,88,16,0.000010,814,1650,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716167-y0lA58PEKmLzJOsyIcQ6,118,2,120,0.000016,0.290574,Nebius,88,1,0.000016,82,87,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716167-AjZRmyZjalV3KEDw5LZJ,118,2,120,0.000012,0.347107,DeepInfra,131,1,0.000012,303,333,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716168-kGPWGGzk0pkXfjUy5Gpy,121,57,178,0.000020,1.300522,Novita,43,42,0.000020,501,930,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716170-CqYAkw25J2hBYTMTw7BQ,65,2,67,0.000009,0.287935,Nebius,43,1,0.000009,79,82,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716170-tqTbr5w7ksrdKj0HIPYr,65,2,67,0.000007,1.216167,DeepInfra,86,1,0.000007,913,964,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716172-PumlUSQQuGRaiTGZ7rNg,123,13,136,0.000026,0.430635,Amazon Bedrock,49,3,0.000026,218,246,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716173-Vx7TbLjDrIijIseGvBWE,71,2,73,0.000010,0.292246,Nebius,49,1,0.000010,87,92,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716173-MJevgaahFcmjzXcB9kWo,71,2,73,0.000008,0.353902,DeepInfra,92,1,0.000008,349,384,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716174-YTd2FR3OOSvm34TEn8vj,126,13,139,0.000006,1.591067,AkashML,51,3,0.000006,1426,1519,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716175-x1rhaBwWoST1KkwhDc2q,74,2,76,0.000010,0.285220,Nebius,51,1,0.000010,83,86,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716176-Bfwj3GhUREnnpNLrF0R2,75,2,77,0.000016,0.577167,Parasail,94,1,0.000016,372,372,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716176-9luZlWc5G1iT3m172J7a,154,25,179,0.000009,2.210344,AkashML,76,16,0.000009,2014,2272,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716179-21eVSDM7VVTZqnQgnHUp,103,2,105,0.000014,0.277962,Nebius,76,1,0.000014,80,82,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716179-DoNsfpPi7JxYUyOvDnPi,103,2,105,0.000011,0.391106,DeepInfra,119,1,0.000011,406,456,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716180-egHlUtbmANK3xnOOS13m,124,61,185,0.000021,0.663180,Novita,49,49,0.000021,467,893,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716181-hDzGYkhGwhGAgLhTnQVq,72,2,74,0.000010,0.280634,Nebius,49,1,0.000010,84,86,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716181-nd3uMAlo0fMv8r76igLL,73,2,75,0.000015,0.527426,Parasail,92,1,0.000015,337,337,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716182-Xtfi5Pb5yUNgbrwDqfvI,139,25,164,0.000008,0.997269,AkashML,62,16,0.000008,824,1222,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716183-MnL4KLgqbVfCqNYOSgd3,84,2,86,0.000012,0.346485,Nebius,62,1,0.000012,135,138,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716184-jNehxDzS4cBdJG6RJlg6,85,2,87,0.000018,0.759264,Parasail,105,1,0.000018,594,594,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716184-Xu9HOtRiZnzLy2tbOGv1,121,29,150,0.000009,1.066181,AkashML,42,20,0.000009,888,1143,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716186-8bOiHZNcr1yq0MMbmcRc,63,2,65,0.000009,0.275916,Nebius,42,1,0.000009,81,85,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716186-UBYZVUGBTnUw4i9FRI8T,63,2,65,0.000007,0.701945,DeepInfra,85,1,0.000007,204,229,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716187-CC9KNQyq530iDgU5g8Vl,114,28,142,0.000009,1.894677,DeepInfra,57,15,0.000009,787,1838,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716190-9YnkXikmgvKjD9t9aFTx,71,2,73,0.000010,0.309665,Nebius,57,1,0.000010,100,104,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716191-S4Y7MpVU7KdbNDgJ34e9,71,2,73,0.000008,0.347182,DeepInfra,100,1,0.000008,372,485,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716191-A4gl8vik2IEPliu1WHWw,101,35,136,0.000010,2.664645,DeepInfra,38,24,0.000010,623,1443,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716195-sapujejhCoqH3qA9N3pr,56,2,58,0.000008,0.280753,Nebius,38,1,0.000008,81,83,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716195-wU0W58lCRRNIilDeLImZ,56,1,57,0.000026,0.656400,SambaNova,81,1,0.000026,475,475,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716196-6Xxb7PWbi0RbxX3rSrpd,153,25,178,0.000009,1.427387,AkashML,78,16,0.000009,1390,1605,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716198-sXAP5E2aFSQUhjvzeMy3,100,2,102,0.000014,0.292840,Nebius,78,1,0.000014,87,87,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716198-Bi0oAKH1N49NW920lgHJ,120,2,122,0.000040,0.544209,Cloudflare,121,1,0.000040,442,442,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716199-vm1xu7XJkpq0c03oFzk6,167,25,192,0.000033,1.881568,Parasail,95,16,0.000033,339,405,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716201-5A0lSaJEcv9pxxm06A3X,113,2,115,0.000015,0.293938,Nebius,95,1,0.000015,88,88,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716201-4MuvefK7hh3BvhH1US6h,113,2,115,0.000012,0.357612,DeepInfra,138,1,0.000012,407,618,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716202-L8crDYO6RixuFDAzMZZZ,137,20,157,0.000008,0.454784,DeepInfra,72,9,0.000008,441,773,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716203-LIcQlBOh8AwgqFak84KJ,93,2,95,0.000013,0.299004,Nebius,72,1,0.000013,86,86,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716203-jX9N4bhGJt3Vx772cCLA,93,2,95,0.000010,1.707311,DeepInfra,115,1,0.000010,1745,1854,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716205-3E1PUSyWBpLrVx8YZjmq,117,25,142,0.000009,1.857962,DeepInfra,55,11,0.000009,551,1047,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716208-805gHNwq2Ddk2Q8uE8IA,74,2,76,0.000010,0.278500,Nebius,55,1,0.000010,83,85,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716208-JSfhChYvKYGthT7y8EgG,74,2,76,0.000008,0.353100,DeepInfra,98,1,0.000008,875,1041,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716210-8mUDAQsEATICy8Cf5XUN,127,31,158,0.000068,0.390340,Cerebras,50,18,0.000068,181,200,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716210-5zZKbW7VxP7xY21hwuuT,68,2,70,0.000010,0.296214,Nebius,50,1,0.000010,86,88,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716210-Ehew0YGJWU5f6BfFT0vK,69,2,71,0.000014,0.766866,Parasail,93,1,0.000014,594,594,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716211-rRdzOXVKDamn7ftlqnvL,117,36,153,0.000022,1.255309,SiliconFlow,37,33,0.000022,1260,5009,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716216-fAY8yOaKLY3AViMzpU2t,58,2,60,0.000008,0.637255,Nebius,37,1,0.000008,434,438,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716217-cV8eYnmKzi2LkSo54zAO,59,2,61,0.000016,0.429627,Crusoe,80,1,0.000016,266,411,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716218-3hT4zXraJuHzjT06vzyX,128,25,153,0.000008,1.751704,AkashML,46,16,0.000008,1596,2093,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716220-1R9bhKkx3m2ZX8qAiKn9,70,2,72,0.000010,0.931121,Nebius,46,1,0.000010,727,793,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716221-VcYGso6k6HoDJStxw05B,70,2,72,0.000008,0.363143,DeepInfra,89,1,0.000008,247,290,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716222-6PhD8GPuJPs0OEAZZ6W3,128,20,148,0.000008,0.457720,DeepInfra,60,9,0.000008,688,979,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716223-o3pIWZIqmrtwnx66DRLo,84,2,86,0.000012,0.333385,Nebius,60,1,0.000012,127,131,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716223-pKrFj8OgJ2Kj7GzcesAl,85,2,87,0.000020,4.464248,Parasail,103,1,0.000020,4446,4446,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716228-8BfOJGOAiHGLcM4Bk7hC,121,54,175,0.000025,0.588802,DigitalOcean,47,42,0.000025,443,1594,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716230-tteu3gtqsaGVc3rz8fSZ,67,2,69,0.000010,0.275399,Nebius,47,1,0.000010,83,87,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716230-zdSluv8uSlv8ouRU183W,67,2,69,0.000007,0.356098,DeepInfra,90,1,0.000007,321,352,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716230-xxXDVB0leVP89BxPt246,150,30,180,0.000010,0.671850,AkashML,78,22,0.000010,499,771,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716231-tEI1IfxwZ05r58M47Tna,95,2,97,0.000013,0.287275,Nebius,78,1,0.000013,84,84,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716232-oN8owjdftENODOqJAN0R,96,2,98,0.000020,3.469615,Parasail,121,1,0.000020,3427,3427,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,fr,gen-1787716235-ihxmgvUhmAmkqFw9oEuw,125,30,155,0.000025,0.572158,Mancer 2,51,18,0.000025,535,706,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,fr,gen-1787716236-6i4stq21f2qKvYISHQtx,71,2,73,0.000010,0.295354,Nebius,51,1,0.000010,88,93,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,fr,gen-1787716237-9BOu4wwMKpVwIplwnrZx,71,1,72,0.000033,0.613409,SambaNova,94,1,0.000033,427,427,None

In [11]:
portuguese_accounting, portuguese_accounting_summary = await build_accounting(portuguese_raw)

print("Portuguese accounting")
display(portuguese_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        portuguese_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

Portuguese accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,3083,700,3783,0.000403,17.689171,0.707567,0.000403,514.96,1144.16
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,1729,50,1779,0.000245,7.521223,0.300849,0.000245,98.08,100.08
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,1877,50,1927,0.000352,16.536202,0.661448,0.000352,572.40,593.52

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716258-JHcZAv5ctOnjxc4X6wOz,101,41,142,0.000011,0.462326,DeepInfra,35,28,0.000011,432,1339,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716259-CX1EE3SwWu37mhZ5Bscz,56,2,58,0.000008,0.283467,Nebius,35,1,0.000008,82,82,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716260-YEVgCCJLdk0DFIsh3hGc,57,2,59,0.000008,1.853985,Novita,78,1,0.000008,1349,1349,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716262-JHxlzrhF7ttHeD70GtEQ,121,44,165,0.000012,0.511076,DeepInfra,49,34,0.000012,556,1817,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716264-ag8D0vH1BH7UKkhRrTBF,79,2,81,0.000011,0.508863,Nebius,49,1,0.000011,314,314,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716264-yGoXrEWMjbzqAU2i18IO,99,2,101,0.000034,0.276920,Cloudflare,92,1,0.000034,188,188,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716265-2Wa3esZaCn3XnESDMPEz,116,36,152,0.000010,1.396646,AkashML,39,27,0.000010,1127,1685,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716267-yANmOZ4BLfkjuLNMOggV,59,2,61,0.000008,0.304254,Nebius,39,1,0.000008,88,90,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716267-V1tqfIVYQNgxYIcRreuz,59,2,61,0.000007,0.362785,DeepInfra,82,1,0.000007,268,319,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716267-GXhhuJKjjaa46W5XSVAa,173,18,191,0.000008,0.728556,AkashML,99,7,0.000008,529,708,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716268-u2EwfcFvPTWWDdeDNtNL,125,2,127,0.000017,0.299694,Nebius,99,1,0.000017,97,102,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716269-yMhFUBj1XdCSU7ipkOG4,145,2,147,0.000028,0.704797,AkashML,142,1,0.000028,520,520,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716269-ulrXDKYmYEZdlVf95sOV,114,30,144,0.000009,0.496523,CoreWeave,38,19,0.000009,472,1332,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716271-3tX9g5wwGj2LkDeHYaJW,56,2,58,0.000008,0.316861,Nebius,38,1,0.000008,108,108,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716271-8qdJxFxYnEVhITturWKS,57,2,59,0.000012,0.557156,Parasail,81,1,0.000012,383,383,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716272-43J4W89JP4Mfmr8dLOAH,119,30,149,0.000009,0.511328,CoreWeave,45,19,0.000009,498,1198,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716273-omZb2HBlsgyScyIErDww,61,2,63,0.000009,0.300613,Nebius,45,1,0.000009,96,96,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716274-GV3y3EXtcmDxbf7U4xGc,81,2,83,0.000016,0.937093,AkashML,88,1,0.000016,747,749,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716275-2G5B6EP51wCeBbkWnPV1,139,22,161,0.000025,1.180451,BaseTen,55,17,0.000025,315,390,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716276-0Hd6wyezN3iWiTbxBHl4,79,2,81,0.000011,0.287715,Nebius,55,1,0.000011,86,90,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716277-QBWYFyQuoXHHw17bT1Wy,80,2,82,0.000012,0.703685,Novita,98,1,0.000012,504,505,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716277-i1jGU4p10T60gxLjI6ww,124,9,133,0.000017,0.414579,BaseTen,43,2,0.000017,219,236,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716278-Swvosx9YvxYrAihM4C0y,65,2,67,0.000009,0.301127,Nebius,43,1,0.000009,92,95,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716278-FAV5Oft1a1mKiMc5maVj,66,2,68,0.000014,0.605071,Parasail,86,1,0.000014,722,722,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716279-hXWxiSCIhTYGO7WTJNly,124,15,139,0.000019,0.478749,Parasail,48,5,0.000019,301,390,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716280-yU3RzH9kYVe5oL5uTGMU,67,2,69,0.000010,0.294855,Nebius,48,1,0.000010,94,95,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716280-6htFMqmiYXkkN6r9Z4AM,67,2,69,0.000007,0.361346,DeepInfra,91,1,0.000007,484,544,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716281-fkEFqsdfajByra6JFUtt,121,30,151,0.000036,0.278307,Groq,43,19,0.000036,76,109,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716281-ddqGnSmWdCVUH7FHguOc,63,2,65,0.000009,0.274336,Nebius,43,1,0.000009,81,83,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716281-cmf3P1bRUu6qB1q84qXk,63,2,65,0.000007,0.358660,DeepInfra,86,1,0.000007,512,573,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716282-y7Nsre3VVj8JYPhhgpbi,116,25,141,0.000009,0.454474,DeepInfra,51,12,0.000009,602,1502,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716284-TD5BlzehRXNTZjiV1jio,74,2,76,0.000010,0.290135,Nebius,51,1,0.000010,83,87,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716284-THeSAwD5A8S3j6KUpSWx,94,2,96,0.000015,2.627886,AkashML,94,1,0.000015,2783,2793,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716287-TszlfmEL4jZ6iY5Ve5hy,126,33,159,0.000009,0.479706,CoreWeave,48,24,0.000009,421,1166,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716289-heyVZyCzp9V4GMGG0wUZ,70,2,72,0.000010,0.303551,Nebius,48,1,0.000010,87,88,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716289-LWrbR7NHnnBvInIrXOLt,70,2,72,0.000008,0.363327,DeepInfra,91,1,0.000008,282,333,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716289-0QsRgLcJcCnLbgaWc9SM,119,30,149,0.000009,0.470564,CoreWeave,44,19,0.000009,430,1468,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716291-gLR7QT1vPDGkMnHpC4tV,62,2,64,0.000009,0.274778,Nebius,44,1,0.000009,85,87,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716291-qFSOwQa8KM8A8LnEW5xP,62,2,64,0.000007,0.425682,DeepInfra,87,1,0.000007,421,455,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716292-81cKpXXkkds3S3KRSoKM,129,16,145,0.000007,0.721038,AkashML,53,6,0.000007,523,1057,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716293-H2xzuHWs1fkLQzi6CKsi,72,2,74,0.000010,0.292595,Nebius,53,1,0.000010,88,91,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716294-Wq10u86xfiaNgCzuT98g,73,2,75,0.000011,0.717332,Novita,96,1,0.000011,521,521,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716294-dgeVbBb8u7elOwnMactK,117,43,160,0.000025,1.202746,SiliconFlow,40,45,0.000025,1079,2878,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716297-NdwTGXryUROZ1YyNu3Th,59,2,61,0.000008,0.283507,Nebius,40,1,0.000008,86,87,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716298-gGjGBYFhhhJ39yB4IQen,79,2,81,0.000012,1.283226,AkashML,83,1,0.000012,1095,1100,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716299-YBTjYUlK2r2gEe4PFLFr,124,17,141,0.000007,0.711146,AkashML,48,6,0.000007,514,936,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716300-ZZLTYllaIjNa1Xf4uEFq,68,2,70,0.000010,0.281448,Nebius,48,1,0.000010,83,84,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716301-PDSCa1orDoPHYy6EC0M9,68,2,70,0.000007,0.353405,DeepInfra,91,1,0.000007,268,334,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716301-OruyeNjvo0DKIsU73f49,123,21,144,0.000024,0.481502,Parasail,46,11,0.000024,285,368,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716302-A2BkbNhky2Ld9WuuHRyD,64,2,66,0.000009,0.297428,Nebius,46,1,0.000009,90,90,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716302-BFSCQaxSAEzn98A93AFF,64,2,66,0.000007,0.358947,DeepInfra,89,1,0.000007,363,389,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716303-ay3xmtFPekuT59fhfM7K,127,17,144,0.000034,1.958155,SambaNova,54,7,0.000034,339,343,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716305-myolXrAV7aLNO1vtqMuf,72,2,74,0.000010,0.286349,Nebius,54,1,0.000010,80,82,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716305-XXeNTFBso30u5BcRmyzz,72,2,74,0.000008,0.388421,DeepInfra,97,1,0.000008,377,411,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716306-ytTReIBxXgPmpfZkfSHj,118,38,156,0.000010,0.487051,CoreWeave,45,33,0.000010,500,1767,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716308-ljfZEgcejvm7DzJnvdEX,62,2,64,0.000009,0.279266,Nebius,45,1,0.000009,77,81,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716308-ez6pDnFl6CCKbctloXJX,82,2,84,0.000050,0.276570,Groq,88,1,0.000050,77,77,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716308-T67ALMZhBhUKoddGT1oc,130,11,141,0.000018,0.570326,BaseTen,49,4,0.000018,338,425,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716309-OokoPtJsE3MhyxAZE0BR,70,2,72,0.000010,0.286586,Nebius,49,1,0.000010,86,89,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716309-I0OtSNTQOPNtZw3RWAig,70,2,72,0.000008,0.364226,DeepInfra,92,1,0.000008,243,272,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716310-4jJBmDcFZkwjYRGbaF34,122,49,171,0.000028,1.498511,SiliconFlow,46,50,0.000028,991,1592,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716312-YhIgjVvRzlNSYEXj3oq2,65,2,67,0.000009,0.286975,Nebius,46,1,0.000009,92,94,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716312-WBBjT8S2wMNLvKZt0Dza,85,2,87,0.000029,0.421003,Cloudflare,89,1,0.000029,281,281,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716313-6UHMhm7F0RhJYMwMBL3l,112,45,157,0.000021,0.893623,DigitalOcean,39,34,0.000021,753,1867,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716315-lnKFXbCp1taapu6tVN2T,57,2,59,0.000008,0.305474,Nebius,39,1,0.000008,93,96,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716315-Cs593fzrhGCF6WeYlCLw,58,2,60,0.000009,0.696610,Novita,82,1,0.000009,506,506,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716316-xWJ2nVkuL0YRN8Gy0Tct,130,31,161,0.000010,0.401470,DeepInfra,67,19,0.000010,717,1188,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716318-NU4L6VbFuKM6PfD1QvQE,98,2,100,0.000014,0.310618,Nebius,67,1,0.000014,115,117,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716318-mABUra23qg8k6qAtUjqQ,99,2,101,0.000014,0.705075,Novita,110,1,0.000014,513,513,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716319-EdgJNA5qkRjCPXuOBCzX,114,19,133,0.000029,0.434768,Amazon Bedrock,39,8,0.000029,226,273,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716319-tQ47q1DQV8rjK474SMP8,59,2,61,0.000008,0.275844,Nebius,39,1,0.000008,79,83,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716319-AdssIpOXDHAiyegR6pGv,60,2,62,0.000017,0.462161,Crusoe,82,1,0.000017,300,396,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,pt,gen-1787716320-G8NTmWCWXlK7i838bFBF,124,30,154,0.000009,0.465550,CoreWeave,45,19,0.000009,631,2570,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,pt,gen-1787716323-m37I9tmbg2mH59kpnElR,67,2,69,0.000010,0.294886,Nebius,45,1,0.000010,90,91,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,pt,gen-1787716323-pdGrmIKyiwP44J7nSUkV,67,2,69,0.000007,0.370836,DeepInfra,88,1,0.000007,603,605,None

In [12]:
spanish_accounting, spanish_accounting_summary = await build_accounting(spanish_raw)

print("Spanish accounting")
display(spanish_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        spanish_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

Spanish accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,3091,825,3916,0.000457,29.211812,1.168472,0.000457,912.20,1594.96
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,1780,50,1830,0.000251,19.625432,0.785017,0.000251,658.16,684.96
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,1850,50,1900,0.000356,13.899291,0.555972,0.000356,457.24,493.60

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716344-e2FeZkSd1fIPvn1cZwgg,123,59,182,0.000021,2.604990,Novita,52,52,0.000021,2408,3189,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716347-j4LVDmLmkHaiekUvo8jB,68,2,70,0.000010,10.014108,Nebius,52,1,0.000010,11884,12274,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716360-s6QrgMKQSBHikWYFxUbU,68,2,70,0.000007,0.355911,DeepInfra,95,1,0.000007,388,465,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716360-YIVi5aXYPHCaRA13ECFu,185,13,198,0.000008,1.654626,AkashML,117,3,0.000008,1480,1570,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716362-V1KMQa9LcH1igYr6nCST,129,2,131,0.000018,0.295121,Nebius,117,1,0.000018,102,132,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716362-mXId9Q3LkODJ3ogubmeE,130,2,132,0.000018,0.683618,Novita,160,1,0.000018,505,505,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716363-mBHCiJGYzJN7pZZwButF,142,25,167,0.000009,0.478681,CoreWeave,71,17,0.000009,515,903,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716364-sMZnp5qp19YJaoN1hX4R,88,2,90,0.000012,0.306572,Nebius,71,1,0.000012,106,111,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716365-dScVnNhx2RjtJbLUQNcO,88,2,90,0.000009,0.352142,DeepInfra,114,1,0.000009,482,674,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716365-wZIvIChf8eUR2nj9UPIl,102,44,146,0.000025,0.546750,Google,42,31,0.000025,347,463,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716366-R4S0voFlyqiGlnULDER6,64,2,66,0.000009,0.283354,Nebius,42,1,0.000009,88,94,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716366-r3lWxiZgjFpzCddxeJ2o,65,2,67,0.000015,1.105380,Parasail,85,1,0.000015,586,586,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716368-i0UiBrNfqGydKpJJLvAT,117,24,141,0.000039,0.543344,SambaNova,39,17,0.000039,355,363,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716368-VQXnHRLb7huEcPElVYcS,61,2,63,0.000009,0.282846,Nebius,39,1,0.000009,90,144,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716369-Qdn8bLsNrtvQG3RL5uAk,61,2,63,0.000007,0.359645,DeepInfra,82,1,0.000007,458,520,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716369-skW36sXOe9GB21kBQBxE,118,14,132,0.000006,0.465608,CoreWeave,44,5,0.000006,354,691,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716370-WroFZN22WWlsqjaf4oUX,62,2,64,0.000009,0.327813,Nebius,44,1,0.000009,125,132,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716371-p0HF2SAuyikDzfPpQYWj,62,2,64,0.000007,0.361257,DeepInfra,87,1,0.000007,230,259,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716371-frNxhWajPbp6zSGxNm2g,116,15,131,0.000007,0.797042,DeepInfra,53,5,0.000007,657,968,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716373-pnS3oiYS4rMKA5BtEIeY,74,2,76,0.000010,0.292168,Nebius,53,1,0.000010,93,103,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716373-3oqNsZmIkn7e0si9VyxL,74,2,76,0.000008,0.602768,DeepInfra,96,1,0.000008,902,1092,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716374-johMoGVzLRVjWUQUoDXl,128,78,206,0.000035,1.153739,DigitalOcean,52,59,0.000035,931,2812,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716377-7oca52HWDpixfjC428p5,74,2,76,0.000010,0.298066,Nebius,52,1,0.000010,94,101,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716378-GFvZTnXQTqFK35ZWBDdA,74,2,76,0.000008,0.357773,DeepInfra,95,1,0.000008,326,350,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716378-HBZObDhY2EIX2KFPoZXy,127,31,158,0.000025,0.954271,Mancer 2,50,18,0.000025,432,731,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716380-qtjLLhyZsAwHEJnmejGf,69,2,71,0.000010,0.312479,Nebius,50,1,0.000010,99,107,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716380-Lq8uxhBRviE4caW8fmWZ,89,2,91,0.000014,0.989211,AkashML,93,1,0.000014,808,811,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716381-1PmBilLGSHfdDOxi18Ql,130,15,145,0.000006,0.473248,CoreWeave,57,5,0.000006,330,514,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716382-vRbqSQlVPOZfaYGxckll,77,2,79,0.000011,0.295471,Nebius,57,1,0.000011,90,97,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716382-ht1sgpQs8oRbYPMBnprN,77,2,79,0.000082,0.518213,Together,100,1,0.000082,306,368,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716383-8LSG3MCr0fHrP7vbJLC8,115,25,140,0.000009,0.455834,DeepInfra,52,11,0.000009,491,1149,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716384-KBjLYY4CuprJMNu373zW,76,2,78,0.000011,0.326981,Nebius,52,1,0.000011,119,127,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716384-dagETigqG0lkhKY0HvwO,77,2,79,0.000021,0.438651,Crusoe,95,1,0.000021,287,393,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716385-Ey7XpQuoq68yke6iIUbQ,114,13,127,0.000025,0.503757,Amazon Bedrock,39,3,0.000025,307,351,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716386-pRMs3ltMkjSjPDebmeG5,60,2,62,0.000009,0.322275,Nebius,39,1,0.000009,111,118,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716386-PN9eHIXQFAx2y0U2Th2U,61,2,63,0.000009,0.717161,Novita,82,1,0.000009,510,510,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716387-Q8QJPLBp47kujUOLdvz1,110,13,123,0.000024,1.019157,Amazon Bedrock,36,3,0.000024,481,516,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716388-NAIcAySASQ5M5Mt4EqIz,55,2,57,0.000008,0.311084,Nebius,36,1,0.000008,102,112,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716388-ijiFcEocQ1HizyZzQg8A,55,2,57,0.000006,0.357304,DeepInfra,79,1,0.000006,316,350,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716389-U5EBoyd9vdGwX1nVGWZb,106,31,137,0.000009,1.857862,DeepInfra,44,18,0.000009,736,1733,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716392-h5BykEZNDaS5u47J0tWL,62,2,64,0.000009,0.294454,Nebius,44,1,0.000009,92,95,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716392-qDzly8BEJAUbdpKp9XhK,62,2,64,0.000007,0.414533,DeepInfra,87,1,0.000007,276,311,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716393-qayGcvn2cWzyPAfsBjm9,111,51,162,0.000055,4.800962,Mara,36,42,0.000055,4614,4614,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716398-KHr4gM10Ptdr0VD8sJtm,53,2,55,0.000008,0.306338,Nebius,36,1,0.000008,108,108,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716398-xws3YjPzKqfFEKq8AM5U,73,2,75,0.000026,0.288740,Cloudflare,79,1,0.000026,175,175,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716398-bYkOSG23Xw2VgGoVOL8L,134,25,159,0.000008,1.905715,AkashML,60,17,0.000008,1460,1856,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716401-DzedkDG1iYa5Tnt3E4b3,80,2,82,0.000011,0.300273,Nebius,60,1,0.000011,87,93,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716401-1igSMH5yZxqmVQBblB8J,81,2,83,0.000012,0.685298,Novita,103,1,0.000012,496,496,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716402-39WdVvsyR8n9vr9AjVxB,119,45,164,0.000011,0.495830,CoreWeave,46,35,0.000011,539,2806,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716405-8OK8vL2fQpoSMaKxZbZA,61,2,63,0.000009,0.656010,Nebius,46,1,0.000009,446,448,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716406-gGC2xiul2HLucIrK7I2L,62,2,64,0.000013,0.629073,Parasail,89,1,0.000013,446,446,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716406-r0MJUaOP4HGYfS5UKDXI,120,37,157,0.000023,1.684441,SiliconFlow,43,36,0.000023,1600,3135,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716410-ozaAXJR2ANIlm0e4hfI1,63,2,65,0.000009,0.481667,Nebius,43,1,0.000009,87,101,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716410-WcyKGF1jrhQfIVTgFD94,64,2,66,0.000013,0.596948,Parasail,86,1,0.000013,390,390,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716411-aBZFmVHCXjnVPQanbR4E,123,47,170,0.000012,1.814685,CoreWeave,45,33,0.000012,364,1550,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716414-wAgt8ObFTkDSIbxkSeEp,65,2,67,0.000009,0.344089,Nebius,45,1,0.000009,144,148,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716414-EuCJmqyjKWaBqAJJAhYZ,66,2,68,0.000014,0.508843,Parasail,88,1,0.000014,316,316,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716415-V72scGR4aaGvRJJIi193,122,39,161,0.000024,1.166857,SiliconFlow,47,39,0.000024,1032,2120,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716417-TR0rqa20w31QJ26YfU37,63,2,65,0.000009,0.348922,Nebius,47,1,0.000009,147,206,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716418-VGF46QoSHB40mPK2cyK0,83,2,85,0.000013,0.947285,AkashML,90,1,0.000013,766,769,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716419-rKBqIjgueono9voG2y1i,136,25,161,0.000008,0.489987,AkashML,58,17,0.000008,308,662,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716420-s8vDEj0rCe7AZuo514zc,80,2,82,0.000011,0.285526,Nebius,58,1,0.000011,90,116,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716420-M4WbqVQtIQZ4fC3SFAqE,80,2,82,0.000009,0.368587,DeepInfra,101,1,0.000009,499,524,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716421-uW9CPwYor1hxJEgg8KKh,131,62,193,0.000022,0.695143,Novita,54,48,0.000022,543,1388,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716422-kf9QuBWZa2jukqYt0L0g,76,2,78,0.000011,0.288449,Nebius,54,1,0.000011,91,95,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716423-w9Ezo1usdGiI7VHG1sdJ,77,2,79,0.000011,0.868670,Novita,97,1,0.000011,709,709,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716423-VKxoRWVPj18Vmk1ZrTkb,124,13,137,0.000007,0.862840,DeepInfra,62,3,0.000007,711,1192,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716425-hVU8Xp0FDSuxd3LZiByB,84,2,86,0.000012,0.421773,Nebius,62,1,0.000012,227,227,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716426-3Og0XiPMqWXOuNmWkRCN,84,2,86,0.000009,0.344966,DeepInfra,105,1,0.000009,413,449,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716426-Ht9prfSy8p7brzUTOLbU,131,56,187,0.000032,1.227001,SiliconFlow,54,53,0.000032,1113,3101,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716430-FTqJVAPRniFIgwYejv2d,75,2,77,0.000011,0.283837,Nebius,54,1,0.000011,81,84,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716430-Zn30QsdvGP2smFwykW6R,76,2,78,0.000011,0.685796,Novita,97,1,0.000011,510,510,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,es,gen-1787716431-mGjcIxupKmXR7gL2LHqv,107,25,132,0.000008,0.559444,DeepInfra,41,17,0.000008,697,1497,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,es,gen-1787716432-gXedqP3UyRF75Rv7x1Ot,61,2,63,0.000009,1.945757,Nebius,41,1,0.000009,1751,1751,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,es,gen-1787716434-dIzmOjqRu5aphKG9QIuo,61,2,63,0.000007,0.361518,DeepInfra,84,1,0.000007,331,362,None

In [13]:
russian_accounting, russian_accounting_summary = await build_accounting(russian_raw)

print("Russian accounting")
display(russian_accounting_summary)

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(
        russian_accounting[
            [
                "benchmark_row_id",
                "model_name",
                "model_id",
                "prediction",
                "generation_id",
                "prompt_tokens",
                "completion_tokens",
                "total_tokens",
                "response_cost_usd",
                "request_duration_seconds",
                "generation_provider",
                "generation_prompt_tokens",
                "generation_completion_tokens",
                "generation_total_cost_usd",
                "generation_latency_ms",
                "generation_generation_time_ms",
                "generation_error",
            ]
        ]
    )

Russian accounting

,model_name,model_id,api_calls,successful_predictions,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,avg_request_duration_seconds,official_generation_cost_usd,avg_official_latency_ms,avg_official_generation_time_ms
0,gpt_oss_120b,openai/gpt-oss-120b,25,25,3312,850,4162,0.000511,19.920296,0.796812,0.000511,717.04,1643.88
1,hermes_4_70b,nousresearch/hermes-4-70b,25,25,2158,50,2208,0.000301,7.554907,0.302196,0.000301,112.24,117.52
2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,25,25,2250,50,2300,0.000348,15.520276,0.620811,0.000348,596.88,634.56

,benchmark_row_id,model_name,model_id,prediction,generation_id,prompt_tokens,completion_tokens,total_tokens,response_cost_usd,request_duration_seconds,generation_provider,generation_prompt_tokens,generation_completion_tokens,generation_total_cost_usd,generation_latency_ms,generation_generation_time_ms,generation_error
0,0,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716461-jFLkglb3WPGIDfHKhnKG,112,32,144,0.000036,0.365763,DeepInfra,44,25,0.000036,309,579,None
1,0,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716462-8ApVIymHu7CTEP0l9TsE,67,2,69,0.000010,0.481010,Nebius,44,1,0.000010,295,301,None
2,0,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716463-DygF6UzV3hPMYiYiSJA2,68,2,70,0.000010,0.699448,Novita,87,1,0.000010,523,523,None
3,1,gpt_oss_120b,openai/gpt-oss-120b,en,gen-1787716463-8wnqx4DuvMtUnN7NIWuz,116,26,142,0.000009,0.523361,DeepInfra,57,17,0.000009,700,1489,None
4,1,hermes_4_70b,nousresearch/hermes-4-70b,en,gen-1787716465-lcHLbeXRQjFp46WfSmyC,71,2,73,0.000010,0.287063,Nebius,57,1,0.000010,99,104,None
5,1,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,en,gen-1787716465-8sO9gp1l2uCYnsrmOd8q,91,2,93,0.000014,1.118761,AkashML,100,1,0.000014,935,953,None
6,2,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716466-GUugEqUyP9M5M27Y4AtJ,113,30,143,0.000009,0.420216,DeepInfra,59,18,0.000009,596,1587,None
7,2,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716468-Xh7uKaK4Tw98uEdKXDGK,71,2,73,0.000010,0.282322,Nebius,59,1,0.000010,91,93,None
8,2,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716469-agoVlDQaElA84EnfHnGl,91,2,93,0.000018,0.960527,AkashML,102,1,0.000018,791,793,None
9,3,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716470-xsJUrLdeAGUoKGkS81Mf,149,29,178,0.000010,0.505623,DeepInfra,97,17,0.000010,1008,1501,None
10,3,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716471-nzQVtKnOGO6Q1n6INtk7,112,2,114,0.000015,0.288091,Nebius,97,1,0.000015,103,110,None
11,3,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716472-1oqQIerkBf0walXARYg8,113,2,115,0.000030,0.398652,Crusoe,140,1,0.000030,261,344,None
12,4,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716472-9I2RZOB8VyMOoEV4TvNZ,155,29,184,0.000011,0.542540,DeepInfra,107,17,0.000011,595,1378,None
13,4,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716474-ARkAmWV4E5KV2WrSqLRr,119,2,121,0.000016,0.325386,Nebius,107,1,0.000016,142,149,None
14,4,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716474-FtwaWEzEJLyuvaRlMZUE,120,2,122,0.000017,0.713340,Novita,150,1,0.000017,621,621,None
15,5,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716475-1RUH36o9dipT7FenlZ5u,189,111,300,0.000059,3.051166,SiliconFlow,154,108,0.000059,1118,7903,None
16,5,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716485-s9QU4vIIqsqHo2YqnNfi,143,2,145,0.000019,0.292781,Nebius,154,1,0.000019,90,94,None
17,5,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716485-lJEd60t0lw3GCoVFx2jb,143,2,145,0.000015,1.433802,DeepInfra,197,1,0.000015,1391,1612,None
18,6,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716487-dzfdB8FF5RDVj6rp0C4B,167,25,192,0.000010,0.523341,DeepInfra,140,11,0.000010,596,1745,None
19,6,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716489-AJNxnWnZ87mYMPzUJP66,130,2,132,0.000018,0.278608,Nebius,140,1,0.000018,91,95,None
20,6,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716489-Ym8uUAM6fwJamNFcupwT,150,2,152,0.000026,0.862955,AkashML,183,1,0.000026,688,688,None
21,7,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716490-jAclrU8yzvFNHaGEixjB,118,20,138,0.000008,1.145628,DeepInfra,64,10,0.000008,1195,1656,None
22,7,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716492-658Z4O8bVmwSseogB7cJ,73,2,75,0.000010,0.450617,Nebius,64,1,0.000010,254,257,None
23,7,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716492-N7UMOHigWbAr25A2gThU,73,2,75,0.000008,0.342883,DeepInfra,107,1,0.000008,227,258,None
24,8,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716493-50VxlTt45JgZu4UiUmlj,113,30,143,0.000009,0.434252,DeepInfra,50,18,0.000009,620,1339,None
25,8,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716494-E5AXKvxrOuLjciC8lBDq,70,2,72,0.000010,0.277120,Nebius,50,1,0.000010,89,94,None
26,8,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716495-pvSVc1VDemF6BBho0Qgr,70,2,72,0.000008,0.338023,DeepInfra,93,1,0.000008,553,590,None
27,9,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716495-uJjGvVsrHAI1DkTTyzVQ,117,25,142,0.000009,0.507072,DeepInfra,59,11,0.000009,666,1595,None
28,9,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716497-CRgMoMREaPWDESY7ShEc,74,2,76,0.000010,0.413768,Nebius,59,1,0.000010,217,222,None
29,9,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716498-IgCdgCEZkFml7XNQF90l,75,2,77,0.000020,0.393128,Crusoe,102,1,0.000020,244,312,None
30,10,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716498-6zjIabVlyKvyg3j8nyZW,110,33,143,0.000010,0.876984,DeepInfra,58,22,0.000010,627,1517,None
31,10,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716500-eHCpnGHWLAPPNheF0uEJ,68,2,70,0.000010,0.279986,Nebius,58,1,0.000010,84,90,None
32,10,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716501-Q5iVw5DHkb6k95h2lurf,69,2,71,0.000010,0.707692,Novita,101,1,0.000010,534,535,None
33,11,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716501-e1zBoBzmuzJv73073Qob,122,26,148,0.000020,0.557212,Google,75,17,0.000020,368,463,None
34,11,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716502-5MyocIYOXDeGlQk3vK5q,81,2,83,0.000011,0.276665,Nebius,75,1,0.000011,85,90,None
35,11,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716502-ulexkjd8i19R3JbOgkLR,82,2,84,0.000012,0.727176,Novita,118,1,0.000012,564,565,None
36,12,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716503-37szUZ4pulkjtwEG1WtU,116,50,166,0.000023,0.930210,DigitalOcean,51,48,0.000023,883,2152,None
37,12,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716505-Kenel6EQs1pBLzwsJGdZ,65,2,67,0.000009,0.277041,Nebius,51,1,0.000009,90,95,None
38,12,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716506-XbclJEuEw5xfd0WGklUH,85,2,87,0.000013,0.907803,AkashML,94,1,0.000013,725,726,None
39,13,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716507-7kCeoYXA5XuWeZ5x4D73,146,29,175,0.000044,3.088930,Mara,80,18,0.000044,2903,2903,None
40,13,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716510-a34bMTSGpiZgAgtHf6nn,89,2,91,0.000012,0.276445,Nebius,80,1,0.000012,88,97,None
41,13,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716510-On01U7Zn9aWQKpIbcvta,90,2,92,0.000024,0.397302,Crusoe,123,1,0.000024,259,343,None
42,14,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716511-JDKct3kxSXjjyaWzJcrl,120,25,145,0.000009,0.451419,DeepInfra,72,17,0.000009,553,1316,None
43,14,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716512-V3HGtzLcq7qQdNkR3iK5,79,2,81,0.000011,0.276851,Nebius,72,1,0.000011,84,90,None
44,14,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716512-FbM6fkFwmLaT5AeXOuDw,79,2,81,0.000009,0.355986,DeepInfra,115,1,0.000009,235,261,None
45,15,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716513-1nZBvPw5BMSdN9K9oHl9,142,37,179,0.000020,0.615724,DigitalOcean,84,24,0.000020,499,1333,None
46,15,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716514-PEMiaeZJJyD027mVmpvZ,89,2,91,0.000012,0.275055,Nebius,84,1,0.000012,87,92,None
47,15,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716515-3cVf3QtfxFH94FvTRx7c,89,2,91,0.000010,0.445355,DeepInfra,127,1,0.000010,284,310,None
48,16,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716515-tozuNkkUUrSV0HDAbG4M,152,33,185,0.000011,0.475826,DeepInfra,104,22,0.000011,661,1544,None
49,16,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716517-OZU0Ab284Eev914G1jQL,106,2,108,0.000015,0.271796,Nebius,104,1,0.000015,86,93,None
50,16,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716517-3EMS5YYP4Xn88yUagMwH,107,2,109,0.000015,0.719010,Novita,147,1,0.000015,546,547,None
51,17,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716518-7xwEw9A1n9LHct8U95ZO,157,49,206,0.000025,0.575562,DigitalOcean,121,41,0.000025,451,1603,None
52,17,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716520-tZjoTWlsZcHEd5eAHqXp,106,2,108,0.000015,0.284406,Nebius,121,1,0.000015,94,98,None
53,17,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716520-7xTi9uv9BR8xpZFixoJl,106,2,108,0.000011,0.357968,DeepInfra,164,1,0.000011,419,456,None
54,18,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716521-lPbUfmOZPGxsQVy8ibvK,147,26,173,0.000010,0.427629,DeepInfra,103,17,0.000010,497,1538,None
55,18,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716523-iMxLoL4jXP2JDtB2Nb3f,109,2,111,0.000015,0.305469,Nebius,103,1,0.000015,115,119,None
56,18,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716523-5U54kMkz9yADwGpdBl3S,109,2,111,0.000012,0.340452,DeepInfra,146,1,0.000012,338,361,None
57,19,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716523-vqgt83ATTG9D573h5iYH,107,30,137,0.000009,1.000348,DeepInfra,44,18,0.000009,814,1446,None
58,19,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716525-0xDLcm3yl2MxCSg0SRNj,61,2,63,0.000009,0.263537,Nebius,44,1,0.000009,81,86,None
59,19,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716525-XXeshSxLCPTSOXo1DFMu,62,2,64,0.000009,0.718414,Novita,87,1,0.000009,550,551,None
60,20,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716526-EeMTj04xpQlffwufbhaJ,122,31,153,0.000066,0.346681,Cerebras,47,18,0.000066,155,170,None
61,20,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716526-xlSyFEI2kIHuJkCiBqy8,63,2,65,0.000009,0.275150,Nebius,47,1,0.000009,90,95,None
62,20,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716527-k8zGpCtWKvnZemLTfxJf,64,2,66,0.000009,0.694824,Novita,90,1,0.000009,525,526,None
63,21,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716527-6Y53xJkYcIXj9xuAIRwH,125,13,138,0.000027,0.285338,Nebius,50,3,0.000027,101,136,None
64,21,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716528-DyqtGDPpE9WNuqaFqCh2,67,2,69,0.000010,0.282067,Nebius,50,1,0.000010,92,99,None
65,21,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716528-AiTkWj8R3nGFzB1O6LGs,68,2,70,0.000014,0.477687,Parasail,93,1,0.000014,311,311,None
66,22,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716529-NfJH4bUBWy7hEiz2wzd3,127,26,153,0.000009,0.528422,DeepInfra,69,17,0.000009,602,1291,None
67,22,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716530-KzOLNGAFdDnD2l1iW6Ci,82,2,84,0.000011,0.286660,Nebius,69,1,0.000011,86,91,None
68,22,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716530-yLLK3kOKU4a2ZjuuCz6s,82,2,84,0.000009,0.340813,DeepInfra,112,1,0.000009,264,308,None
69,23,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716531-I5gB1qY1eTWdB6mmE3Ge,131,52,183,0.000030,1.131497,SiliconFlow,61,58,0.000030,982,2190,None
70,23,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716533-WF7wZltoO3Au0E3k0Ixb,76,2,78,0.000011,0.272066,Nebius,61,1,0.000011,85,90,None
71,23,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716534-uNCIgD8whloau0YC6yaG,77,2,79,0.000016,0.724674,Parasail,104,1,0.000016,376,376,None
72,24,gpt_oss_120b,openai/gpt-oss-120b,ru,gen-1787716534-H4kkve3uqGgQPld2nyZW,139,33,172,0.000028,0.609552,Mancer 2,72,22,0.000028,427,723,None
73,24,hermes_4_70b,nousresearch/hermes-4-70b,ru,gen-1787716535-lrzk4yqvjMbgguDqew9W,87,2,89,0.000012,0.274948,Nebius,72,1,0.000012,88,94,None
74,24,llama_3_3_70b,meta-llama/llama-3.3-70b-instruct,ru,gen-1787716536-UPYeagZtDBb2Fqqks2VI,87,2,89,0.000009,0.343603,DeepInfra,115,1,0.000009,2758,2994,None