In [9]:
from __future__ import annotations

import json
import re
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import pandas as pd
import requests
from IPython.display import display
from google.colab import userdata

In [10]:
PARQUET_PATH = Path("/content/sessions_lang_transcript.parquet")

OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODEL = "tencent/hy-mt2-30b-a3b"

TARGET_SESSION_ID = 140595413
N_SEGMENTS = 30

REQUEST_TIMEOUT_SECONDS = 120
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 2
TEMPERATURE = 0
REASONING_ENABLED = True

TRANSIENT_STATUS_CODES = {408, 409, 429, 500, 502, 503, 504}

PARQUET_COLUMNS = [
    "gamesession_id",
    "game_name",
    "model_type",
    "lang_detected",
    "lang_probability",
    "transcript_segments",
]

LANGUAGE_ALIASES = {
    "english": "en",
    "russian": "ru",
    "indonesian": "id",
    "german": "de",
    "french": "fr",
    "spanish": "es",
    "portuguese": "pt",
    "ukrainian": "uk",
    "polish": "pl",
    "japanese": "ja",
    "korean": "ko",
    "chinese": "zh",
    "italian": "it",
    "dutch": "nl",
    "turkish": "tr",
    "arabic": "ar",
    "hindi": "hi",
    "thai": "th",
    "vietnamese": "vi",
    "malay": "ms",
}

In [11]:
def normalize_language(value: Any) -> str:
    language = str(value).strip().lower()
    return LANGUAGE_ALIASES.get(language, language)


def load_sessions(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Parquet file not found: {path}")

    try:
        return pd.read_parquet(path, columns=PARQUET_COLUMNS)
    except Exception as exc:
        raise RuntimeError(f"Failed to read parquet file: {exc}") from exc


def get_session_row(dataframe: pd.DataFrame, session_id: int) -> pd.Series:
    matches = dataframe.loc[dataframe["gamesession_id"] == session_id]

    if matches.empty:
        raise ValueError(f"Session {session_id} not found")

    if len(matches) != 1:
        raise ValueError(
            f"Expected one row for session {session_id}, found {len(matches)}"
        )

    return matches.iloc[0]


df = load_sessions(PARQUET_PATH)
session_row = get_session_row(df, TARGET_SESSION_ID)

segments = session_row["transcript_segments"]

if segments is None:
    raise ValueError("transcript_segments is empty")

internal_lang = normalize_language(session_row["lang_detected"])

print("Session ID          :", session_row["gamesession_id"])
print("Game                :", session_row["game_name"])
print("Internal model      :", session_row["model_type"])
print("Internal language   :", internal_lang)
print("Internal probability:", session_row["lang_probability"])
print("Total segments      :", len(segments))
print("Segments to analyze :", min(N_SEGMENTS, len(segments)))

Session ID          : 140595413
Game                : Counter Strike2
Internal model      : gen10
Internal language   : ru
Internal probability: 0.9873
Total segments      : 714
Segments to analyze : 30

In [12]:
def get_openrouter_api_key() -> str:
    api_key = userdata.get("OPENROUTER_API_KEY")

    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY is not available in Colab Secrets")

    return api_key


HTTP_SESSION = requests.Session()
HTTP_SESSION.headers.update(
    {
        "Authorization": f"Bearer {get_openrouter_api_key()}",
        "Content-Type": "application/json",
    }
)


def build_language_detection_prompt(text: str) -> str:
    return f"""
Analyze every lexical word in the transcript segment below.

For every word, identify its language using an ISO 639-1 code where possible.

Examples:
- en = English
- ru = Russian
- id = Indonesian
- de = German
- fr = French
- es = Spanish
- pt = Portuguese
- uk = Ukrainian
- pl = Polish
- ja = Japanese
- ko = Korean
- zh = Chinese

Rules:
1. Classify every lexical word.
2. Preserve the original word order.
3. Preserve each word as closely as possible to the transcript.
4. Do not add words.
5. Infer language only from the transcript text.
6. Do not use any external language label.
7. Ignore punctuation-only tokens.
8. Return only valid JSON.
9. Do not calculate percentages.

Transcript:
{text}

Return exactly this structure:

{{
  "words": [
    {{
      "word": "example",
      "language": "en"
    }}
  ]
}}
""".strip()


def extract_json_object(content: str) -> dict[str, Any]:
    cleaned = content.strip()
    cleaned = re.sub(r"^```json\s*", "", cleaned, flags=re.IGNORECASE)
    cleaned = re.sub(r"^```\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        match = re.search(r"\{.*\}", cleaned, flags=re.DOTALL)

        if not match:
            raise ValueError("LLM response does not contain a valid JSON object")

        parsed = json.loads(match.group(0))

    if not isinstance(parsed, dict):
        raise ValueError("LLM response must be a JSON object")

    return parsed


def validate_prediction(prediction: dict[str, Any]) -> list[dict[str, str]]:
    words = prediction.get("words")

    if not isinstance(words, list):
        raise ValueError("LLM response does not contain a valid words list")

    normalized = []

    for index, item in enumerate(words):
        if not isinstance(item, dict):
            raise ValueError(f"words[{index}] is not an object")

        word = str(item.get("word", "")).strip()
        language = normalize_language(item.get("language", ""))

        if not word:
            continue

        if not language:
            raise ValueError(f"words[{index}] has no language")

        normalized.append(
            {
                "word": word,
                "language": language,
            }
        )

    if not normalized:
        raise ValueError("LLM returned no lexical words")

    return normalized


def detect_word_languages(text: str) -> dict[str, Any]:
    text = str(text).strip()

    if not text:
        raise ValueError("Text cannot be empty")

    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {
                "role": "user",
                "content": build_language_detection_prompt(text),
            }
        ],
        "temperature": TEMPERATURE,
        "reasoning": {
            "enabled": REASONING_ENABLED,
        },
    }

    last_error = None

    for attempt in range(1, MAX_RETRIES + 1):
        try:
            response = HTTP_SESSION.post(
                OPENROUTER_API_URL,
                json=payload,
                timeout=REQUEST_TIMEOUT_SECONDS,
            )

            if response.status_code in TRANSIENT_STATUS_CODES:
                response.raise_for_status()

            response.raise_for_status()

            response_json = response.json()
            content = response_json["choices"][0]["message"]["content"]

            prediction = extract_json_object(content)
            words = validate_prediction(prediction)

            return {
                "words": words,
                "raw_content": content,
            }

        except (
            requests.RequestException,
            KeyError,
            IndexError,
            TypeError,
            ValueError,
            json.JSONDecodeError,
        ) as exc:
            last_error = exc

            if attempt == MAX_RETRIES:
                break

            time.sleep(RETRY_BACKOFF_SECONDS * (2 ** (attempt - 1)))

    raise RuntimeError(
        f"LLM request failed after {MAX_RETRIES} attempts: {last_error}"
    )

In [13]:
def calculate_language_stats(
    predicted_words: Iterable[dict[str, str]],
) -> tuple[dict[str, int], dict[str, float], dict[str, list[str]]]:
    words = list(predicted_words)

    if not words:
        return {}, {}, {}

    counts = Counter(item["language"] for item in words)
    total_words = len(words)

    percentages = {
        language: count / total_words * 100
        for language, count in counts.items()
    }

    words_by_language = defaultdict(list)

    for item in words:
        words_by_language[item["language"]].append(item["word"])

    return dict(counts), percentages, dict(words_by_language)


def analyze_session_segments(
    segments: Iterable[dict[str, Any]],
    internal_lang: str,
    n_segments: int,
) -> tuple[pd.DataFrame, dict[str, Any], pd.DataFrame]:
    internal_lang = normalize_language(internal_lang)

    all_results = []
    segment_details = {}
    errors = []

    segments_to_process = list(segments)[:n_segments]

    for segment_index, segment in enumerate(segments_to_process, start=1):
        segment_name = f"segment {segment_index}"
        segment_text = str(segment.get("text", "")).strip()

        if not segment_text:
            errors.append(
                {
                    "segment": segment_name,
                    "text": "",
                    "error": "Empty segment text",
                }
            )
            continue

        print(
            f"[{segment_index}/{len(segments_to_process)}] Processing {segment_name}"
        )

        try:
            prediction = detect_word_languages(segment_text)
            predicted_words = prediction["words"]

            counts, percentages, words_by_language = calculate_language_stats(
                predicted_words
            )

            segment_details[segment_name] = {
                "segment_index": segment_index,
                "text": segment_text,
                "words": predicted_words,
                "counts": counts,
                "percentages": percentages,
                "raw_llm_content": prediction["raw_content"],
            }

            for language, percentage in percentages.items():
                detected_words = words_by_language.get(language, [])
                is_internal_language = language == internal_lang

                all_results.append(
                    {
                        "segment_index": segment_index,
                        "segment": segment_name,
                        "text": segment_text,
                        "language": language,
                        "percentage": percentage,
                        "word_count": counts[language],
                        "detected_words": ", ".join(detected_words),
                        "is_internal_language": is_internal_language,
                        "mismatch_words": (
                            ""
                            if is_internal_language
                            else ", ".join(detected_words)
                        ),
                    }
                )

        except Exception as exc:
            errors.append(
                {
                    "segment": segment_name,
                    "text": segment_text,
                    "error": str(exc),
                }
            )

    result_df = pd.DataFrame(all_results)
    errors_df = pd.DataFrame(errors)

    if result_df.empty:
        return result_df, segment_details, errors_df

    result_df = (
        result_df.sort_values(
            by=[
                "is_internal_language",
                "language",
                "percentage",
                "segment_index",
            ],
            ascending=[
                True,
                True,
                False,
                True,
            ],
        )
        .reset_index(drop=True)
    )

    return result_df, segment_details, errors_df

In [14]:
result_df, segment_details, errors_df = analyze_session_segments(
    segments=segments,
    internal_lang=internal_lang,
    n_segments=N_SEGMENTS,
)

display_df = result_df.copy()

if not display_df.empty:
    display_df["percentage"] = display_df["percentage"].map(
        lambda value: f"{value:.1f}%"
    )

    display_df = display_df[
        [
            "segment",
            "text",
            "language",
            "percentage",
            "word_count",
            "mismatch_words",
        ]
    ]

print()
print("Session ID       :", session_row["gamesession_id"])
print("Internal language:", internal_lang)

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(display_df)

if not errors_df.empty:
    display(errors_df)

[1/30] Processing segment 1
[2/30] Processing segment 2
[3/30] Processing segment 3
[4/30] Processing segment 4
[5/30] Processing segment 5
[6/30] Processing segment 6
[7/30] Processing segment 7
[8/30] Processing segment 8
[9/30] Processing segment 9
[10/30] Processing segment 10
[11/30] Processing segment 11
[12/30] Processing segment 12
[13/30] Processing segment 13
[14/30] Processing segment 14
[15/30] Processing segment 15
[16/30] Processing segment 16
[17/30] Processing segment 17
[18/30] Processing segment 18
[19/30] Processing segment 19
[20/30] Processing segment 20
[21/30] Processing segment 21
[22/30] Processing segment 22
[23/30] Processing segment 23
[24/30] Processing segment 24
[25/30] Processing segment 25
[26/30] Processing segment 26
[27/30] Processing segment 27
[28/30] Processing segment 28
[29/30] Processing segment 29
[30/30] Processing segment 30

Session ID       : 140595413
Internal language: ru

,segment,text,language,percentage,word_count,mismatch_words
0,segment 14,"уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с",en,42.5%,31,"йоу, на, мемфисе, плюс, мы, спокойно, вступили, и, можем, все, вступить, в, семью, к, диману, и, с, ними, играть, я, считаю, плюс, даже, если, меня, что-то, не, сложится, вы, можете, с"
1,segment 9,"до свидания, я хочу поработать у вас 600 долларов на шахте!",en,18.2%,2,"600, долларов"
2,segment 10,"Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.",en,15.8%,6,"GTA, memphis, w, 5, 7, невипки"
3,segment 11,"Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?",en,14.3%,2,"600, долларов"
4,segment 3,"Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.",en,13.3%,2,"50, 50"
5,segment 4,"50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?",en,13.3%,2,"50, 50"
6,segment 2,"Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.",en,10.0%,1,Дэнс
7,segment 27,мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид,en,8.5%,6,"маджестик, мемфис, вайнот, матч, йоу, йоу"
8,segment 8,"Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное",en,6.4%,5,"GTA, GTA, GTA, GTA, GTA"
9,segment 13,Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что,en,5.3%,3,"Majestic, 7, скины"
10,segment 26,"Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты",en,5.1%,4,"w, 50, 7, f2"
11,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,en,4.4%,2,"гта, йоу"
12,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,ja,2.2%,1,хики
13,segment 5,"О, нифига себе. А подожди, зачем тебе дорожка? и так худая, я прям...",ru,100.0%,13,
14,segment 6,"Максимально я бы сказал, что ты худая. Подожди, где я должен был бы возродиться?",ru,100.0%,14,
15,segment 7,"Скорее всего, где-то здесь. нужно возродиться. Бля, ну если нет, нет, семейный офис.",ru,100.0%,12,
16,segment 12,"Подожди, а что там? Надо побежать, сейчас буду.",ru,100.0%,8,
17,segment 15,ними остаться и играть как бы мне не то что не жалко только лучше для ребят сделаю и все у пани уже бабочка а я помню бабочка имеет теперь мне надо ну я помню что он какую-то да хотел купить себе бабочку это было неплохо не ну конечно хрюндель это исчез и пиздец ну как будто бы и вот хрюндель как будто бы именно злыдня знаете ли,ru,100.0%,67,
18,segment 16,"Сын прараба, ну, прездорово. Да ничего, сойдёт ты, как горит.",ru,100.0%,10,
19,segment 17,"А чего у вас-то, когда хикиш, куда пойдёте вы? С вами гребазанами.",ru,100.0%,12,
20,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",ru,100.0%,14,
21,segment 19,"Как дела? Всё нормально, кепычи, у тебя как дела? Не, я вроде такого не говорил.",ru,100.0%,15,
22,segment 20,"Я говорил, как у этого, если что-то устроит, то пойду. Не, ты чего?",ru,100.0%,13,
23,segment 21,"Ё-у, здорово, Никси, как у тебя дела? У него кровавый Путин в это...",ru,100.0%,13,
24,segment 22,"О, прикольно, красная такая, я хочу фиолетовую.",ru,100.0%,7,
25,segment 23,"блин, фиолетовая, я помню, помню как выглядит фиолетовая, она выглядит намного лучше, честно говоря.",ru,100.0%,14,
26,segment 24,"Она выглядит... Бля, я забыл как поменять, например, раскладку бега, потому что здесь же если поменять походку, то будет намного быстрее идти.",ru,100.0%,22,
27,segment 25,"Ну ладно, я никуда и не тороплюсь в целом-то на самом деле.",ru,100.0%,13,
28,segment 28,"ходьбы настройки перса подожди вид ходьбы или прям именно дожди ну персонаж наверное ну не ну вот видите здесь просто очень много всего и здесь события как будто бы набор во фракцию фибов я бы сходил на самом деле аукцион контейнеров через но мне денег не хватит вагаса не хочу Я бы пошел либо в МАС, а может реально пойти МАС девочку, фемочку найти себе,",ru,100.0%,65,
29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",ru,100.0%,14,
30,segment 30,"Путь бомжика в ГТА, что Ну не то чтобы путь бомжика, мужики.",ru,100.0%,12,
31,segment 26,"Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты",ru,94.9%,74,
32,segment 13,Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что,ru,94.7%,54,
33,segment 8,"Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное",ru,93.6%,73,
34,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,ru,93.3%,42,
35,segment 27,мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид,ru,91.5%,65,
36,segment 2,"Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.",ru,90.0%,9,
37,segment 3,"Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.",ru,86.7%,13,
38,segment 4,"50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?",ru,86.7%,13,
39,segment 11,"Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?",ru,85.7%,12,
40,segment 10,"Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.",ru,84.2%,32,
41,segment 9,"до свидания, я хочу поработать у вас 600 долларов на шахте!",ru,81.8%,9,
42,segment 14,"уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с",ru,57.5%,42,

In [15]:
mismatch_df = result_df.loc[
    ~result_df["is_internal_language"]
].copy()

if not mismatch_df.empty:
    mismatch_df["percentage"] = mismatch_df["percentage"].map(
        lambda value: f"{value:.1f}%"
    )

    mismatch_df = mismatch_df[
        [
            "segment",
            "text",
            "language",
            "percentage",
            "word_count",
            "mismatch_words",
        ]
    ]

print("Internal language:", internal_lang)

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(mismatch_df)

Internal language: ru

,segment,text,language,percentage,word_count,mismatch_words
0,segment 14,"уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с",en,42.5%,31,"йоу, на, мемфисе, плюс, мы, спокойно, вступили, и, можем, все, вступить, в, семью, к, диману, и, с, ними, играть, я, считаю, плюс, даже, если, меня, что-то, не, сложится, вы, можете, с"
1,segment 9,"до свидания, я хочу поработать у вас 600 долларов на шахте!",en,18.2%,2,"600, долларов"
2,segment 10,"Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.",en,15.8%,6,"GTA, memphis, w, 5, 7, невипки"
3,segment 11,"Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?",en,14.3%,2,"600, долларов"
4,segment 3,"Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.",en,13.3%,2,"50, 50"
5,segment 4,"50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?",en,13.3%,2,"50, 50"
6,segment 2,"Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.",en,10.0%,1,Дэнс
7,segment 27,мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид,en,8.5%,6,"маджестик, мемфис, вайнот, матч, йоу, йоу"
8,segment 8,"Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное",en,6.4%,5,"GTA, GTA, GTA, GTA, GTA"
9,segment 13,Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что,en,5.3%,3,"Majestic, 7, скины"
10,segment 26,"Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты",en,5.1%,4,"w, 50, 7, f2"
11,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,en,4.4%,2,"гта, йоу"
12,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,ja,2.2%,1,хики

In [16]:
for segment_name, detail in segment_details.items():
    print("=" * 100)
    print(segment_name)
    print(detail["text"])
    print()

    words_df = pd.DataFrame(detail["words"])

    with pd.option_context(
        "display.max_columns", None,
        "display.max_colwidth", None,
        "display.width", None,
        "display.max_rows", None,
    ):
        display(words_df)

    print("Counts     :", detail["counts"])
    print("Percentages:", detail["percentages"])
    print()

====================================================================================================
segment 1
кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный

            word language
0         кушать       ru
1        готовил       ru
2          очень       ru
3     вкусненько       ru
4             но       ru
5      приходите       ru
6   присаживайся       ru
7        реально       ru
8           надо       ru
9       подождем       ru
10          блин       ru
11           гта       en
12            да       ru
13            ну       ru
14            на       ru
15          худа       ru
16          хики       ja
17           еще       ru
18       азиатик       ru
19       здорово       ru
20        привет       ru
21           моя       ru
22          киса       ru
23             я       ru
24          если       ru
25           что       ru
26       натурал       ru
27         сразу       ru
28        говорю       ru
29             я       ru
30             с       ru
31     азиатиком       ru
32            не       ru
33     заигрываю       ru
34       никогда       ru
35             я       ru
36       натурал       ru
37     уверенный       ru
38             в       ru
39          себе       ru
40       мужчина       ru
41           йоу       en
42             я       ru
43       натурал       ru
44     уверенный       ru

Counts     : {'ru': 42, 'en': 2, 'ja': 1}
Percentages: {'ru': 93.33333333333333, 'en': 4.444444444444445, 'ja': 2.2222222222222223}

====================================================================================================
segment 2
Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.

          word language
0          Вот       ru
1           он       ru
2        какой       ru
3    маленький       ru
4        сидит       ru
5   сладенький       ru
6  вкусненький       ru
7            и       ru
8          все       ru
9         Дэнс       en

Counts     : {'ru': 9, 'en': 1}
Percentages: {'ru': 90.0, 'en': 10.0}

====================================================================================================
segment 3
Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.

      word language
0      Зря       ru
1       ты       ru
2      так       ru
3        с       ru
4      ним       ru
5       Ну       ru
6       не       ru
7     знаю       ru
8       на       ru
9    самом       ru
10    деле       ru
11      50       en
12      на       ru
13      50       en
14  мужики       ru

Counts     : {'ru': 13, 'en': 2}
Percentages: {'ru': 86.66666666666667, 'en': 13.333333333333334}

====================================================================================================
segment 4
50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?

        word language
0         50       en
1         на       ru
2         50       en
3          я       ru
4         бы       ru
5     сказал       ru
6         бы       ru
7          А       ru
8          у       ru
9       тебя       ru
10       что       ru
11     дела?       ru
12       Нет       ru
13        на       ru
14  дорожке?       ru

Counts     : {'en': 2, 'ru': 13}
Percentages: {'en': 13.333333333333334, 'ru': 86.66666666666667}

====================================================================================================
segment 5
О, нифига себе. А подожди, зачем тебе дорожка? и так худая, я прям...

       word language
0         О       ru
1    нифига       ru
2      себе       ru
3         А       ru
4   подожди       ru
5     зачем       ru
6      тебе       ru
7   дорожка       ru
8         и       ru
9       так       ru
10    худая       ru
11        я       ru
12     прям       ru

Counts     : {'ru': 13}
Percentages: {'ru': 100.0}

====================================================================================================
segment 6
Максимально я бы сказал, что ты худая. Подожди, где я должен был бы возродиться?

           word language
0   Максимально       ru
1             я       ru
2            бы       ru
3        сказал       ru
4           что       ru
5            ты       ru
6         худая       ru
7       Подожди       ru
8           где       ru
9             я       ru
10       должен       ru
11          был       ru
12           бы       ru
13  возродиться       ru

Counts     : {'ru': 14}
Percentages: {'ru': 100.0}

====================================================================================================
segment 7
Скорее всего, где-то здесь. нужно возродиться. Бля, ну если нет, нет, семейный офис.

           word language
0        Скорее       ru
1         всего       ru
2        где-то       ru
3         здесь       ru
4         нужно       ru
5   возродиться       ru
6           Бля       ru
7            ну       ru
8          если       ru
9           нет       ru
10     семейный       ru
11         офис       ru

Counts     : {'ru': 12}
Percentages: {'ru': 100.0}

====================================================================================================
segment 8
Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное

              word language
0              Нет       ru
1              как       ru
2            будто       ru
3               бы       ru
4        начальник       ru
5             спал       ru
6            место       ru
7           выхода       ru
8               да       ru
9              мне       ru
10           нужно       ru
11          вместо       ru
12          выхода       ru
13         подожди       ru
14             что       ru
15              ты       ru
16          пишешь       ru
17        хрюндель       ru
18              ты       ru
19         долбоеб       ru
20        хрюндель       ru
21             вот       ru
22           скажи       ru
23             мне       ru
24          честно       ru
25              ты       ru
26         дурачок       ru
27             или       ru
28             что       ru
29             вот       ru
30            если       ru
31            тебе       ru
32              ну       ru
33              не       ru
34          купили       ru
35             GTA       en
36               в       ru
37         детстве       ru
38              ты       ru
39              не       ru
40      попробовал       ru
41             GTA       en
42             это       ru
43              не       ru
44          значит       ru
45             что       ru
46             GTA       en
47             его       ru
48              ну       ru
49              не       ru
50           очень       ru
51       согласись       ru
52              не       ru
53           может       ru
54            быть       ru
55             что       ru
56             GTA       en
57             для       ru
58            тебя       ru
59          полная       ru
60           фигня       ru
61               я       ru
62          вообще       ru
63         никогда       ru
64              не       ru
65          поверю       ru
66               я       ru
67            знаю       ru
68          только       ru
69            одно       ru
70             что       ru
71            тебе       ru
72        нравится       ru
73             GTA       en
74               в       ru
75           целом       ru
76             так       ru
77  Дополнительное       ru

Counts     : {'ru': 73, 'en': 5}
Percentages: {'ru': 93.58974358974359, 'en': 6.41025641025641}

====================================================================================================
segment 9
до свидания, я хочу поработать у вас 600 долларов на шахте!

          word language
0           до       ru
1     свидания       ru
2            я       ru
3         хочу       ru
4   поработать       ru
5            у       ru
6          вас       ru
7          600       en
8     долларов       en
9           на       ru
10       шахте       ru

Counts     : {'ru': 9, 'en': 2}
Percentages: {'ru': 81.81818181818183, 'en': 18.181818181818183}

====================================================================================================
segment 10
Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.

          word language
0      Здорово       ru
1       мужики       ru
2          как       ru
3            у       ru
4          вас       ru
5        дела?       ru
6         меня       ru
7          GTA       en
8          уже       ru
9    несколько       ru
10        лета       ru
11          ну       ru
12         так       ru
13      заходи       ru
14  немедленно       ru
15          на       ru
16     memphis       en
17          по       ru
18     правому       ru
19        коду       ru
20        плюс       ru
21           w       en
22           у       ru
23        тебя       ru
24       будет       ru
25        плюс       ru
26           5       en
27      тысячи       ru
28    долларов       ru
29        плюс       ru
30           у       ru
31        тебя       ru
32         еще       ru
33       будет       ru
34           7       en
35     невипки       en
36          не       ru
37    забывай.       ru

Counts     : {'ru': 32, 'en': 6}
Percentages: {'ru': 84.21052631578947, 'en': 15.789473684210526}

====================================================================================================
segment 11
Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?

             word language
0             Так       ru
1           ладно       ru
2   зарабатывайте       ru
3             600       en
4        долларов       en
5              на       ru
6           шахте       ru
7               а       ru
8               я       ru
9              же       ru
10          вроде       ru
11             бы       ru
12      заработал       ru
13            нет       ru

Counts     : {'ru': 12, 'en': 2}
Percentages: {'ru': 85.71428571428571, 'en': 14.285714285714285}

====================================================================================================
segment 12
Подожди, а что там? Надо побежать, сейчас буду.

       word language
0   Подожди       ru
1         а       ru
2       что       ru
3       там       ru
4      Надо       ru
5  побежать       ru
6    сейчас       ru
7      буду       ru

Counts     : {'ru': 8}
Percentages: {'ru': 100.0}

====================================================================================================
segment 13
Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что

          word language
0     Majestic       en
1       вперед       ru
2           ну       ru
3       мужики       ru
4       алгава       ru
5      джестик       ru
6   получается       ru
7            в       ru
8       штрихе       ru
9    плюсядера       ru
10           у       ru
11      мучачи       ru
12           с       ru
13         как       ru
14        дела       ru
15         жду       ru
16          не       ru
17   дождольсь       ru
18       когда       ru
19      пройду       ru
20           7       en
21        дней       ru
22        буду       ru
23  обменивать       ru
24       скины       en
25          на       ru
26     бабочку       ru
27      ручная       ru
28     роспись       ru
29          вы       ru
30     говнюки       ru
31          вы       ru
32         все       ru
33      сейчас       ru
34      будете       ru
35           с       ru
36   бабочками       ru
37           а       ru
38         мне       ru
39       когда       ru
40    подарите       ru
41          ну       ru
42     придать       ru
43        прит       ru
44        зузи       ru
45        лики       ru
46          ну       ru
47          не       ru
48       уходи       ru
49           у       ru
50        меня       ru
51      потери       ru
52        пока       ru
53         тут       ru
54          но       ru
55         нет       ru
56         что       ru

Counts     : {'en': 3, 'ru': 54}
Percentages: {'en': 5.263157894736842, 'ru': 94.73684210526315}

====================================================================================================
segment 14
уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с

          word language
0      уходить       ru
1           то       ru
2        какая       ru
3      разница       ru
4           то       ru
5       посиди       ru
6      посидим       ru
7      посидим       ru
8      посидим       ru
9          что       ru
10      мужики       ru
11         как       ru
12           у       ru
13         вас       ru
14        дела       ru
15         чем       ru
16  занимались       ru
17         это       ru
18           у       ru
19        меня       ru
20         вон       ru
21    хрюндель       ru
22         уже       ru
23        есть       ru
24    собирать       ru
25        жени       ru
26          го       ru
27       когда       ru
28           я       ru
29     приличу       ru
30       будем       ru
31      играть       ru
32      вместе       ru
33      вообще       ru
34      каждый       ru
35        день       ru
36       готов       ru
37      играть       ru
38           в       ru
39         эту       ru
40  прекрасную       ru
41        игру       ru
42         йоу       en
43          на       en
44     мемфисе       en
45        плюс       en
46          мы       en
47    спокойно       en
48    вступили       en
49           и       en
50       можем       en
51         все       en
52    вступить       en
53           в       en
54       семью       en
55           к       en
56      диману       en
57           и       en
58           с       en
59        ними       en
60      играть       en
61           я       en
62      считаю       en
63        плюс       en
64        даже       en
65        если       en
66        меня       en
67      что-то       en
68          не       en
69    сложится       en
70          вы       en
71      можете       en
72           с       en

Counts     : {'ru': 42, 'en': 31}
Percentages: {'ru': 57.534246575342465, 'en': 42.465753424657535}

====================================================================================================
segment 15
ними остаться и играть как бы мне не то что не жалко только лучше для ребят сделаю и все у пани уже бабочка а я помню бабочка имеет теперь мне надо ну я помню что он какую-то да хотел купить себе бабочку это было неплохо не ну конечно хрюндель это исчез и пиздец ну как будто бы и вот хрюндель как будто бы именно злыдня знаете ли

        word language
0       ними       ru
1   остаться       ru
2          и       ru
3     играть       ru
4        как       ru
5         бы       ru
6        мне       ru
7         не       ru
8         то       ru
9        что       ru
10        не       ru
11     жалко       ru
12    только       ru
13     лучше       ru
14       для       ru
15     ребят       ru
16    сделаю       ru
17         и       ru
18       все       ru
19         у       ru
20      пани       ru
21       уже       ru
22   бабочка       ru
23         а       ru
24         я       ru
25     помню       ru
26   бабочка       ru
27     имеет       ru
28    теперь       ru
29       мне       ru
30      надо       ru
31        ну       ru
32         я       ru
33     помню       ru
34       что       ru
35        он       ru
36  какую-то       ru
37        да       ru
38     хотел       ru
39    купить       ru
40      себе       ru
41   бабочку       ru
42       это       ru
43      было       ru
44   неплохо       ru
45        не       ru
46        ну       ru
47   конечно       ru
48  хрюндель       ru
49       это       ru
50     исчез       ru
51         и       ru
52    пиздец       ru
53        ну       ru
54       как       ru
55     будто       ru
56        бы       ru
57         и       ru
58       вот       ru
59  хрюндель       ru
60       как       ru
61     будто       ru
62        бы       ru
63    именно       ru
64    злыдня       ru
65    знаете       ru
66        ли       ru

Counts     : {'ru': 67}
Percentages: {'ru': 100.0}

====================================================================================================
segment 16
Сын прараба, ну, прездорово. Да ничего, сойдёт ты, как горит.

         word language
0         Сын       ru
1     прараба       ru
2          ну       ru
3  прездорово       ru
4          Да       ru
5      ничего       ru
6      сойдёт       ru
7          ты       ru
8         как       ru
9       горит       ru

Counts     : {'ru': 10}
Percentages: {'ru': 100.0}

====================================================================================================
segment 17
А чего у вас-то, когда хикиш, куда пойдёте вы? С вами гребазанами.

            word language
0              А       ru
1           чего       ru
2              у       ru
3         вас-то       ru
4          когда       ru
5          хикиш       ru
6           куда       ru
7        пойдёте       ru
8            вы?       ru
9              С       ru
10          вами       ru
11  гребазанами.       ru

Counts     : {'ru': 12}
Percentages: {'ru': 100.0}

====================================================================================================
segment 18
А кто-то говорил, я на матче, да не, да не, я такого не говорил.

       word language
0         А       ru
1    кто-то       ru
2   говорил       ru
3         я       ru
4        на       ru
5     матче       ru
6        да       ru
7        не       ru
8        да       ru
9        не       ru
10        я       ru
11   такого       ru
12       не       ru
13  говорил       ru

Counts     : {'ru': 14}
Percentages: {'ru': 100.0}

====================================================================================================
segment 19
Как дела? Всё нормально, кепычи, у тебя как дела? Не, я вроде такого не говорил.

          word language
0          Как       ru
1        дела?       ru
2          Всё       ru
3   нормально,       ru
4      кепычи,       ru
5            у       ru
6         тебя       ru
7          как       ru
8        дела?       ru
9          Не,       ru
10           я       ru
11       вроде       ru
12      такого       ru
13          не       ru
14    говорил.       ru

Counts     : {'ru': 15}
Percentages: {'ru': 100.0}

====================================================================================================
segment 20
Я говорил, как у этого, если что-то устроит, то пойду. Не, ты чего?

       word language
0         Я       ru
1   говорил       ru
2       как       ru
3         у       ru
4     этого       ru
5      если       ru
6    что-то       ru
7   устроит       ru
8        то       ru
9     пойду       ru
10       Не       ru
11       ты       ru
12     чего       ru

Counts     : {'ru': 13}
Percentages: {'ru': 100.0}

====================================================================================================
segment 21
Ё-у, здорово, Никси, как у тебя дела? У него кровавый Путин в это...

        word language
0        Ё-у       ru
1    здорово       ru
2      Никси       ru
3        как       ru
4          у       ru
5       тебя       ru
6       дела       ru
7          У       ru
8       него       ru
9   кровавый       ru
10     Путин       ru
11         в       ru
12       это       ru

Counts     : {'ru': 13}
Percentages: {'ru': 100.0}

====================================================================================================
segment 22
О, прикольно, красная такая, я хочу фиолетовую.

         word language
0           О       ru
1   прикольно       ru
2     красная       ru
3       такая       ru
4           я       ru
5        хочу       ru
6  фиолетовую       ru

Counts     : {'ru': 7}
Percentages: {'ru': 100.0}

====================================================================================================
segment 23
блин, фиолетовая, я помню, помню как выглядит фиолетовая, она выглядит намного лучше, честно говоря.

          word language
0         блин       ru
1   фиолетовая       ru
2            я       ru
3        помню       ru
4        помню       ru
5          как       ru
6     выглядит       ru
7   фиолетовая       ru
8          она       ru
9     выглядит       ru
10     намного       ru
11       лучше       ru
12      честно       ru
13      говоря       ru

Counts     : {'ru': 14}
Percentages: {'ru': 100.0}

====================================================================================================
segment 24
Она выглядит... Бля, я забыл как поменять, например, раскладку бега, потому что здесь же если поменять походку, то будет намного быстрее идти.

         word language
0         Она       ru
1    выглядит       ru
2         Бля       ru
3           я       ru
4       забыл       ru
5         как       ru
6    поменять       ru
7    например       ru
8   раскладку       ru
9        бега       ru
10     потому       ru
11        что       ru
12      здесь       ru
13         же       ru
14       если       ru
15   поменять       ru
16    походку       ru
17         то       ru
18      будет       ru
19    намного       ru
20    быстрее       ru
21       идти       ru

Counts     : {'ru': 22}
Percentages: {'ru': 100.0}

====================================================================================================
segment 25
Ну ладно, я никуда и не тороплюсь в целом-то на самом деле.

         word language
0          Ну       ru
1       ладно       ru
2           я       ru
3      никуда       ru
4           и       ru
5          не       ru
6   тороплюсь       ru
7           в       ru
8    целом-то       ru
9          на       ru
10      самом       ru
11       деле       ru
12         то       ru

Counts     : {'ru': 13}
Percentages: {'ru': 100.0}

====================================================================================================
segment 26
Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты

             word language
0              Но       ru
1               я       ru
2              на       ru
3   Сан-Дранциско       ru
4           играю       ru
5               и       ru
6              на       ru
7         мемписе       ru
8              Во       ru
9         немного       ru
10          чисто       ru
11          тачка       ru
12           есть       ru
13              и       ru
14            всё       ru
15              и       ru
16         второй       ru
17          левел       ru
18        лоперса       ru
19              и       ru
20          промо       ru
21          кодик       ru
22             не       ru
23         забудь       ru
24          вести       ru
25           плюс       ru
26              w       en
27              у       ru
28           тебя       ru
29          будет       ru
30             на       ru
31        третьем       ru
32         левеле       ru
33          перса       ru
34          вроде       ru
35             да       ru
36             на       ru
37        третьем       ru
38         левеле       ru
39          перса       ru
40              у       ru
41           тебя       ru
42          будет       ru
43             50       en
44          тысяч       ru
45         лишних       ru
46          денег       ru
47              и       ru
48              7       en
49             не       ru
50       премиума       ru
51             f2       en
52             на       ru
53         строке       ru
54            там       ru
55          будет       ru
56             да       ru
57              я       ru
58            это       ru
59              я       ru
60          понял       ru
61         просто       ru
62          долго       ru
63         искать       ru
64              я       ru
65         считаю       ru
66              я       ru
67            уже       ru
68          водил       ru
69          промо       ru
70         ошибка       ru
71         ошибка       ru
72         ошибка       ru
73          самая       ru
74        большая       ru
75         ошибка       ru
76        которая       ru
77             ты       ru

Counts     : {'ru': 74, 'en': 4}
Percentages: {'ru': 94.87179487179486, 'en': 5.128205128205128}

====================================================================================================
segment 27
мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид

          word language
0          мог       ru
1      сделать       ru
2           ну       ru
3           мы       ru
4      никогда       ru
5           не       ru
6       пойдем       ru
7            и       ru
8           не       ru
9         идем       ru
10       точно       ru
11           я       ru
12      вообще       ru
13           с       ru
14        если       ru
15          чё       ru
16           и       ru
17     бэкнусь       ru
18        блин       ru
19          ну       ru
20     грустно       ru
21          на       ru
22       самом       ru
23        деле       ru
24         что       ru
25      решили       ru
26      больше       ru
27     никакой       ru
28        пока       ru
29      проект       ru
30          вы       ru
31          не       ru
32        идти       ru
33          но       ru
34        если       ru
35          чё       ru
36   приходите       ru
37          на       ru
38   маджестик       en
39          на       ru
40        этот       ru
41          на       ru
42      мемфис       en
43      вайнот       en
44         как       ru
45   говорится       ru
46       ладно       ru
47           я       ru
48       папки       ru
49     поэтому       ru
50      отошел       ru
51       давай       ru
52         все       ru
53  наилучшего       ru
54           а       ru
55           я       ru
56          чё       ru
57        знаю       ru
58         что       ru
59          ты       ru
60          на       ru
61        матч       en
62     перешел       ru
63          ну       ru
64         йоу       en
65         йоу       en
66       женёк       ru
67          на       ru
68     церковь       ru
69        меня       ru
70         вид       ru

Counts     : {'ru': 65, 'en': 6}
Percentages: {'ru': 91.54929577464789, 'en': 8.450704225352112}

====================================================================================================
segment 28
ходьбы настройки перса подожди вид ходьбы или прям именно дожди ну персонаж наверное ну не ну вот видите здесь просто очень много всего и здесь события как будто бы набор во фракцию фибов я бы сходил на самом деле аукцион контейнеров через но мне денег не хватит вагаса не хочу Я бы пошел либо в МАС, а может реально пойти МАС девочку, фемочку найти себе,

           word language
0        ходьбы       ru
1     настройки       ru
2         перса       ru
3       подожди       ru
4           вид       ru
5        ходьбы       ru
6           или       ru
7          прям       ru
8        именно       ru
9         дожди       ru
10           ну       ru
11     персонаж       ru
12     наверное       ru
13           ну       ru
14           не       ru
15           ну       ru
16          вот       ru
17       видите       ru
18        здесь       ru
19       просто       ru
20        очень       ru
21        много       ru
22        всего       ru
23            и       ru
24        здесь       ru
25      события       ru
26          как       ru
27        будто       ru
28           бы       ru
29        набор       ru
30           во       ru
31      фракцию       ru
32        фибов       ru
33            я       ru
34           бы       ru
35       сходил       ru
36           на       ru
37        самом       ru
38         деле       ru
39      аукцион       ru
40  контейнеров       ru
41        через       ru
42           но       ru
43          мне       ru
44        денег       ru
45           не       ru
46       хватит       ru
47       вагаса       ru
48           не       ru
49         хочу       ru
50            я       ru
51           бы       ru
52        пошел       ru
53         либо       ru
54            в       ru
55          МАС       ru
56            а       ru
57        может       ru
58      реально       ru
59        пойти       ru
60          МАС       ru
61      девочку       ru
62      фемочку       ru
63        найти       ru
64         себе       ru

Counts     : {'ru': 65}
Percentages: {'ru': 100.0}

====================================================================================================
segment 29
которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?

         word language
0     которая       ru
1       будет       ru
2         мне       ru
3     мурчать       ru
4   постоянно       ru
5          ну       ru
6     Подожди       ru
7           а       ru
8          че       ru
9           я       ru
10        там       ru
11      че-то       ru
12         не       ru
13       взял       ru

Counts     : {'ru': 14}
Percentages: {'ru': 100.0}

====================================================================================================
segment 30
Путь бомжика в ГТА, что Ну не то чтобы путь бомжика, мужики.

       word language
0      Путь       ru
1   бомжика       ru
2         в       ru
3       ГТА       ru
4       что       ru
5        Ну       ru
6        не       ru
7        то       ru
8      быть       ru
9      путь       ru
10  бомжика       ru
11   мужики       ru

Counts     : {'ru': 12}
Percentages: {'ru': 100.0}