In [1]:
%pip -q install fasttext-wheel

In [2]:
from __future__ import annotations

import json
import math
import random
import re
import time
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any, Iterable

import fasttext
import pandas as pd
import requests
from IPython.display import display
from google.colab import userdata

In [3]:
PARQUET_PATH = Path("/content/sessions_lang_transcript.parquet")
FASTTEXT_MODEL_PATH = Path("/content/lid.176.ftz")
FASTTEXT_MODEL_URL = "https://dl.fbaipublicfiles.com/fasttext/supervised-models/lid.176.ftz"

OPENROUTER_API_URL = "https://openrouter.ai/api/v1/chat/completions"
OPENROUTER_MODEL = "openai/gpt-5.4"

TARGET_SESSION_ID = 140595413
SEGMENT_LIMIT = None

FASTTEXT_TOP_K = 3
FASTTEXT_WINDOW_SIZE = 8
FASTTEXT_WINDOW_STRIDE = 4
FASTTEXT_SEGMENT_CONFIDENCE = 0.80
FASTTEXT_WINDOW_CONFIDENCE = 0.80

MIN_MISMATCH_WORDS = 2
MIN_MISMATCH_PERCENTAGE = 10.0

REQUEST_TIMEOUT_SECONDS = 120
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 2

PARQUET_COLUMNS = [
    "gamesession_id",
    "game_name",
    "model_type",
    "lang_detected",
    "lang_probability",
    "transcript_segments",
]

LANGUAGE_ALIASES = {
    "english": "en",
    "russian": "ru",
    "indonesian": "id",
    "german": "de",
    "french": "fr",
    "spanish": "es",
    "portuguese": "pt",
    "ukrainian": "uk",
    "polish": "pl",
    "japanese": "ja",
    "korean": "ko",
    "chinese": "zh",
    "italian": "it",
    "dutch": "nl",
    "turkish": "tr",
    "arabic": "ar",
    "hindi": "hi",
    "thai": "th",
    "vietnamese": "vi",
    "malay": "ms",
}

In [4]:
def normalize_language(value: Any) -> str:
    language = str(value).strip().lower()
    return LANGUAGE_ALIASES.get(language, language)


def download_file(url: str, destination: Path) -> Path:
    if destination.exists() and destination.stat().st_size > 0:
        return destination

    response = requests.get(url, timeout=REQUEST_TIMEOUT_SECONDS)
    response.raise_for_status()
    destination.write_bytes(response.content)
    return destination


def load_sessions(path: Path) -> pd.DataFrame:
    if not path.exists():
        raise FileNotFoundError(f"Parquet file not found: {path}")

    try:
        dataframe = pd.read_parquet(path, columns=PARQUET_COLUMNS)
    except Exception as exc:
        raise RuntimeError(f"Failed to read parquet file: {exc}") from exc

    missing = set(PARQUET_COLUMNS) - set(dataframe.columns)
    if missing:
        raise ValueError(f"Missing parquet columns: {sorted(missing)}")

    return dataframe


def get_session_row(dataframe: pd.DataFrame, session_id: int) -> pd.Series:
    matches = dataframe.loc[dataframe["gamesession_id"] == session_id]

    if matches.empty:
        raise ValueError(f"Session {session_id} not found")

    if len(matches) != 1:
        raise ValueError(
            f"Expected one row for session {session_id}, found {len(matches)}"
        )

    return matches.iloc[0]


FASTTEXT_MODEL = fasttext.load_model(
    str(download_file(FASTTEXT_MODEL_URL, FASTTEXT_MODEL_PATH))
)

df = load_sessions(PARQUET_PATH)
session_row = get_session_row(df, TARGET_SESSION_ID)
segments = session_row["transcript_segments"]

if segments is None:
    raise ValueError("transcript_segments is empty")

internal_lang = normalize_language(session_row["lang_detected"])
segments_to_process = list(segments) if SEGMENT_LIMIT is None else list(segments)[:SEGMENT_LIMIT]

print("Session ID          :", session_row["gamesession_id"])
print("Game                :", session_row["game_name"])
print("Internal model      :", session_row["model_type"])
print("Internal language   :", internal_lang)
print("Internal probability:", session_row["lang_probability"])
print("Total segments      :", len(segments))
print("Segments to analyze :", len(segments_to_process))

Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.

Session ID          : 140595413
Game                : Counter Strike2
Internal model      : gen10
Internal language   : ru
Internal probability: 0.9873
Total segments      : 714
Segments to analyze : 714

In [5]:
def clean_fasttext_text(text: str) -> str:
    return re.sub(r"\s+", " ", str(text)).strip()


def fasttext_predict(
    text: str,
    k: int = FASTTEXT_TOP_K,
) -> list[dict[str, Any]]:
    text = clean_fasttext_text(text)

    if not text:
        return []

    labels_batch, probabilities_batch = FASTTEXT_MODEL.predict(
        [text],
        k=k,
    )

    labels = labels_batch[0]
    probabilities = probabilities_batch[0]

    return [
        {
            "language": normalize_language(
                label.replace("__label__", "")
            ),
            "confidence": float(probability),
        }
        for label, probability in zip(
            labels,
            probabilities,
        )
    ]


def extract_segment_tokens(segment: dict[str, Any]) -> list[dict[str, Any]]:
    raw_words = segment.get("words")

    if raw_words is None:
        text = str(segment.get("text", "")).strip()
        return [
            {"id": index, "text": token}
            for index, token in enumerate(text.split())
        ]

    tokens = []

    for index, item in enumerate(raw_words):
        if isinstance(item, dict):
            token = str(item.get("text", "")).strip()
        else:
            token = str(item).strip()

        if token:
            tokens.append({"id": index, "text": token})

    return tokens


def is_alphabetic_token(token: str) -> bool:
    return any(character.isalpha() for character in token)


def build_windows(tokens: list[dict[str, Any]]) -> list[str]:
    lexical = [item["text"] for item in tokens if is_alphabetic_token(item["text"])]

    if not lexical:
        return []

    if len(lexical) <= FASTTEXT_WINDOW_SIZE:
        return [" ".join(lexical)]

    windows = []

    for start in range(0, len(lexical), FASTTEXT_WINDOW_STRIDE):
        window = lexical[start : start + FASTTEXT_WINDOW_SIZE]

        if len(window) < max(3, FASTTEXT_WINDOW_SIZE // 2):
            break

        windows.append(" ".join(window))

    return windows


def screen_segment(segment: dict[str, Any], internal_language: str) -> dict[str, Any]:
    text = str(segment.get("text", "")).strip()
    tokens = extract_segment_tokens(segment)
    segment_predictions = fasttext_predict(text)

    primary = segment_predictions[0] if segment_predictions else {
        "language": "unknown",
        "confidence": 0.0,
    }

    window_hits = []

    for window_index, window_text in enumerate(build_windows(tokens), start=1):
        predictions = fasttext_predict(window_text)

        if not predictions:
            continue

        prediction = predictions[0]

        if (
            prediction["language"] != internal_language
            and prediction["confidence"] >= FASTTEXT_WINDOW_CONFIDENCE
        ):
            window_hits.append(
                {
                    "window": window_index,
                    "text": window_text,
                    "language": prediction["language"],
                    "confidence": prediction["confidence"],
                }
            )

    reasons = []

    if primary["language"] != internal_language:
        reasons.append("segment_language_mismatch")

    if primary["confidence"] < FASTTEXT_SEGMENT_CONFIDENCE:
        reasons.append("low_segment_confidence")

    if window_hits:
        reasons.append("foreign_window_detected")

    return {
        "text": text,
        "tokens": tokens,
        "fasttext_language": primary["language"],
        "fasttext_confidence": primary["confidence"],
        "fasttext_top_k": segment_predictions,
        "window_hits": window_hits,
        "needs_deep_audit": bool(reasons),
        "screening_reason": ", ".join(reasons),
    }


screen_rows = []
screen_details = {}

for segment_index, segment in enumerate(segments_to_process, start=1):
    segment_name = f"segment {segment_index}"
    result = screen_segment(segment, internal_lang)
    screen_details[segment_name] = result
    screen_rows.append(
        {
            "segment_index": segment_index,
            "segment": segment_name,
            "text": result["text"],
            "fasttext_language": result["fasttext_language"],
            "fasttext_confidence": result["fasttext_confidence"],
            "needs_deep_audit": result["needs_deep_audit"],
            "screening_reason": result["screening_reason"],
        }
    )

screen_df = pd.DataFrame(screen_rows)

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(screen_df)

,segment_index,segment,text,fasttext_language,fasttext_confidence,needs_deep_audit,screening_reason
0,1,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,ru,0.972242,False,
1,2,segment 2,"Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.",ru,0.804486,False,
2,3,segment 3,"Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.",ru,0.960608,False,
3,4,segment 4,"50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?",ru,0.989989,False,
4,5,segment 5,"О, нифига себе. А подожди, зачем тебе дорожка? и так худая, я прям...",ru,0.900059,False,
5,6,segment 6,"Максимально я бы сказал, что ты худая. Подожди, где я должен был бы возродиться?",ru,0.998536,False,
6,7,segment 7,"Скорее всего, где-то здесь. нужно возродиться. Бля, ну если нет, нет, семейный офис.",ru,0.992197,False,
7,8,segment 8,"Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное",ru,0.995237,False,
8,9,segment 9,"до свидания, я хочу поработать у вас 600 долларов на шахте!",ru,0.944353,False,
9,10,segment 10,"Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.",ru,0.953353,False,
10,11,segment 11,"Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?",ru,0.956126,False,
11,12,segment 12,"Подожди, а что там? Надо побежать, сейчас буду.",ru,0.994952,False,
12,13,segment 13,Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что,ru,0.984412,False,
13,14,segment 14,"уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с",ru,0.990377,False,
14,15,segment 15,ними остаться и играть как бы мне не то что не жалко только лучше для ребят сделаю и все у пани уже бабочка а я помню бабочка имеет теперь мне надо ну я помню что он какую-то да хотел купить себе бабочку это было неплохо не ну конечно хрюндель это исчез и пиздец ну как будто бы и вот хрюндель как будто бы именно злыдня знаете ли,ru,0.994211,False,
15,16,segment 16,"Сын прараба, ну, прездорово. Да ничего, сойдёт ты, как горит.",ru,0.965098,False,
16,17,segment 17,"А чего у вас-то, когда хикиш, куда пойдёте вы? С вами гребазанами.",ru,0.962045,False,
17,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",ru,0.741302,True,low_segment_confidence
18,19,segment 19,"Как дела? Всё нормально, кепычи, у тебя как дела? Не, я вроде такого не говорил.",ru,0.978846,False,
19,20,segment 20,"Я говорил, как у этого, если что-то устроит, то пойду. Не, ты чего?",ru,0.995941,False,
20,21,segment 21,"Ё-у, здорово, Никси, как у тебя дела? У него кровавый Путин в это...",ru,0.995161,False,
21,22,segment 22,"О, прикольно, красная такая, я хочу фиолетовую.",ru,0.964558,False,
22,23,segment 23,"блин, фиолетовая, я помню, помню как выглядит фиолетовая, она выглядит намного лучше, честно говоря.",ru,0.981564,False,
23,24,segment 24,"Она выглядит... Бля, я забыл как поменять, например, раскладку бега, потому что здесь же если поменять походку, то будет намного быстрее идти.",ru,0.996859,False,
24,25,segment 25,"Ну ладно, я никуда и не тороплюсь в целом-то на самом деле.",ru,0.938662,False,
25,26,segment 26,"Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты",ru,0.957575,False,
26,27,segment 27,мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид,ru,0.987567,False,
27,28,segment 28,"ходьбы настройки перса подожди вид ходьбы или прям именно дожди ну персонаж наверное ну не ну вот видите здесь просто очень много всего и здесь события как будто бы набор во фракцию фибов я бы сходил на самом деле аукцион контейнеров через но мне денег не хватит вагаса не хочу Я бы пошел либо в МАС, а может реально пойти МАС девочку, фемочку найти себе,",ru,0.974274,False,
28,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",ru,0.965840,True,foreign_window_detected
29,30,segment 30,"Путь бомжика в ГТА, что Ну не то чтобы путь бомжика, мужики.",ru,0.998546,False,
30,31,segment 31,"Плюс у меня пока нет брички, пока у меня нет брички, но у меня есть наш на раз курица для брички, мужики, йоу!",ru,0.968226,False,
31,32,segment 32,"Претик сладенький, лучший, вежливый, добрый, красивый, отважный, мужественный, благоподобный, Евгешенька, день 32, дай за попу потрогать, нет, райкош, заходи сюда и потрогаешь, йоу, на мемфисе можно всё, мужики, сами понимаете, и побрить, и за попу потрогать, ну сразу говорю, брить мне не надо, даже в шутку, мужики, брить меня не надо, спасибо, ошибка у фибов мало возможностей и они по дк работать не могут, Здарова патриотич, нууу",ru,0.981153,False,
32,33,segment 33,"тогда в емс идем к мурчалочкам Ебанулся емс это вообще рпшная хуйня, не подожди смотри Ай, ну а наху, ох, извини пожалуйста Не то что емс это рпшная штука это факт, но все же почему бы мне не по взаимодейству с женщинами Ты же там взаимодейству женщинами поня, ох Нихуя подожди ты че, не работай гора, начало не надо, не надо, ну вылезни из меня, вылезни",ru,0.992135,False,
33,34,segment 34,"f1, а там дальше сам ищи а понял, f1 в потом мужики как говорится, как пригодится дай, дай, дай, дай, завези, завези, завези надо на что-нибудь нажать не надо ебать он просто встал Джейм, ты через что захочешь, через их лаунчер стиль бегана быстро поменяй А там я не могу найти, чём дело райкоши, я не очень нашёл где стиль бега Как прям это всё",ru,0.989180,False,
34,35,segment 35,"пишется, типа f2, настройки, ну смотри f2 Ааа, на...",ru,0.980513,False,
35,36,segment 36,"Настройки, подожди, настройки Ааа, стиль бега Или как там дальше, подожди Стиль...",ru,0.971921,False,
36,37,segment 37,"Ну смотри вот, безопасность, настройки, прицелы, макросы, название клавиш, игровой чат, настройка звука Дополнительно Понимаешь?",ru,0.986207,False,
37,38,segment 38,"Быстрее начало идти, или мне кажется? Да мой маленький, не эту штуку, потому что нам нужно 600 долларов.",ru,0.993595,False,
38,39,segment 39,"Выбери, Вася. Так, я же выбрал. Подожди.",ru,0.978960,False,
39,40,segment 40,"Что, не выбрал? Подожди. Так, настройки дополните.",ru,0.958404,False,
40,41,segment 41,"Ну, быстро все. Не-не-не. У меня, короче, за вебкой я все выбрал.",ru,0.973289,False,
41,42,segment 42,"Я все выбрал. У меня за вебкой все выбрал. О, ты на матч пришел? Да, мужики.",ru,0.979552,False,
42,43,segment 43,"На Majestic, на Memphis можете заходить, если хотите. По промокоду plusw у вас будет плюс пятьдесят тысяч долларов на балансике на третьем левле плюс семь дней випочки вайноут как говорится как быстрее будет а ты не подтвердил так нет я все подтвердил анимации можешь да анимации могу Женя сделай магазин кейса Женя сделай магазин кейса это как то погоди магазин кейса а ты хочешь чтобы я щас какой нибудь кейсик отверл давай а реально мужики может",ru,0.967011,False,
43,44,segment 44,какой нибудь может быть машинку выбьем Клянись.,ru,0.997153,False,
44,45,segment 45,"-ха-ха! Мужики, может быть Олэнчик дадим?",ru,0.984993,False,
45,46,segment 46,Может быть Олэнчик дадим? Такой киберспортивный.,ru,0.981166,False,
46,47,segment 47,"Мужики, может быть кибера? А ты купил стартовую петель для персонажа?",ru,0.989939,False,
47,48,segment 48,Еще пока нет. Я думаю залудить на машину.,ru,0.948412,False,
48,49,segment 49,Да хватит стучать! Купи парочку. Прокачку персонажа купить?,ru,0.895996,False,
49,50,segment 50,"Давайте одну машинку Откроем, мужики, одну машинку сейчас.",ru,0.872783,False,
50,51,segment 51,"Ой-ой-ой-ой-ой-ой-ой-ой. Сю-ю-ю. Отдай какой-нибудь Gold, пожалуйста.",ru,0.985396,False,
51,52,segment 52,"О-о-о-о, вот вот это, вот это, вот это, вот это. Ну, какой лимузин.",ru,0.996318,False,
52,53,segment 53,"Подожди, патриот. Ха-ха-ха-ха. Ну, куда мне, подожди, ну, куда мне на нём ездить?",ru,0.906641,False,
53,54,segment 54,"Подожди, зря самуюбищный кейс. Подожди, ладно, продаю.",ru,0.986558,False,
54,55,segment 55,"А какой мне тогда кейс посоветую, чтобы выбить машину? Потому что я бы хотел бы как бы одну машинку выбить.",ru,0.998713,False,
55,56,segment 56,"У меня просто... Боже, это вот тоже...",ru,0.993589,False,
56,57,segment 57,"тиши тиши лодим лодим лодим может быть какой посоветуешь ладно патруот чокей окей послушаю тебя какой посоветуешь париря и просто мне бы хотелось машина просто я видел здесь премиум автомобиля выплата мне за эдиты выдаю и после стрима не забудьки нахуй выплаты за эдиты а за три эдита ты сделала три эдита точно сколько я тебе там обещал напомню пожалуйста,",ru,0.976124,False,
57,58,segment 58,"просто Короче, рассказываю полгода или год, короче, нет, полгода назад, я помню, что была зима, я Никсику говорю, Никсик, делаешь три видео и я тебе выплачиваю за это.",ru,0.991563,False,
58,59,segment 59,"Сколько я не помню, клянусь Через полгода Никсик течение полугода делал три видео, скидывал и говорит 6 что вы понимали я из них выставил только один я как сейчас помню",ru,0.989238,False,
59,60,segment 60,а сколько эти нахуй какая нахуй зима я зимой с тобой а сколько эти обещал подожди я даже не помню сколько эти обещал клянусь выпла выплато будет выплато будет просто я не помню сколько напомним мне пожалуйста клянусь я уже забыл что мы с тобой чем-то вообще договаривались пол месяца вы понимаете пол года делала 6 видосов ну ладно 2 месяца нормально вчера рик бабыч у меня на стриме проебал тысячой 4800 нормально эля здорово как дела кто пойдет стримера трогать за,ru,0.987791,False,
60,61,segment 61,"попу и брить не надо райкош меня брить 6 видосов 500 рублей нихуя я что-то загнул слышишь ну да выплачу выплачу шесть соток ой пять соток но что это хуя за такие Ну, без про...",ru,0.993491,False,
61,62,segment 62,"Не-не, всё нормально, выплачу, выплачу. После стрима.",ru,0.982938,False,
62,63,segment 63,"Я уж и забыл, блять. А ты только зайди, ты платишь и её не запросмотришь?",ru,0.996606,False,
63,64,segment 64,"Так там мужики, короче, рассказывают. Никсик начала всякие видосики делать, и нам скидывать в чате к ТГ-канала.",ru,0.977305,False,
64,65,segment 65,"И я решил её поддержать, такой, сделай мне пару видосиков, я тебе, денюшкой.",ru,0.986291,False,
65,66,segment 66,"Но кто знал, что она будет полгода видосов не делать?",ru,0.991527,False,
66,67,segment 67,"Клянусь, забыл. Я помню, что я её поддержать хотел, ну, начального, ну, типа, человека, который едет и делает.",ru,0.996708,False,
67,68,segment 68,"Она что-то училась в этот момент, и всё. Вот как она, говорит, что и сделала, всё.",ru,0.997377,False,
68,69,segment 69,"Вообще, проблем, всё нормально. Ну, блять, не за полгода же.",ru,0.962905,False,
69,70,segment 70,"Жень, купи снарягу, то у меня право... Ааа, подожди, прорабы и контракт возьми.",ru,0.936271,False,
70,71,segment 71,"Так, а мне нужно ещё два раза отнести, у меня, короче, задание за вебкой.",ru,0.963387,False,
71,72,segment 72,"Мужики, меня задание за вебкой, мне нужно заработать 6 соток. Я уже заработал 324, т.е.",ru,0.990003,False,
72,73,segment 73,"вот я сейчас отнесу и еще один раз отнесу, и мы идем дальше задания выполнять.",ru,0.969807,False,
73,74,segment 74,"Я как понимаю, мне нужно сначала сделать начальные задания, и потом мы просто берем, я не знаю, на второй или на третий день уже, просто беремся, собираемся и едем ту улицу.",ru,0.982481,False,
74,75,segment 75,Надо будет машинку и так далее. Ты на Мемфисе?,ru,0.952309,False,
75,76,segment 76,"Тот самый долбоеб, которому я напрямую сказал, мы идем на Мемфис.",ru,0.974319,False,
76,77,segment 77,"Он пишет, ууу, ты на Мемфисе? Ну да, слышишь?",ru,0.961766,False,
77,78,segment 78,ещё раз стиль походки багнулся думаешь?,ru,0.997837,False,
78,79,segment 79,окей щас да не говорил в стриме не не говорил и не раз мужики вы чё,ru,0.915494,False,
79,80,segment 80,бумс так так снаряка тебе даю чтобы ты два раза мог с копать они по одной да тут уже нет а снаряка платная??,ru,0.986124,False,
80,81,segment 81,"она же платная зачем мне платная снаряка Как я понял, платная, только смысл, типа, у от этой платной снаряги.",ru,0.987576,False,
81,82,segment 82,"Забей уже тогда. Мне просто еще один разочек отнести, я уже все это...",ru,0.981456,False,
82,83,segment 83,"Кстати, так я так и не понял, Патриоточ, какой мне нужен этот...",ru,0.983657,False,
83,84,segment 84,"Скажи мне, пожалуйста, какой мне нужен кейс для машины.",ru,0.987256,False,
84,85,segment 85,"Женя Аля. Что именно ты? Скажи, пожалуйста, что именно ты. Хочешь, заходи.",ru,0.993640,False,
85,86,segment 86,"Хуйня ваши кейсы. Не-не-не, я хочу именно бричку выбить, мужики.",ru,0.932042,False,
86,87,segment 87,Че мне делать? ну качни третий левел чтобы ты тоже мог пушкой пользоваться ну там второй левел качни я не знаю чтобы ты мог короче пушкой пользоваться а то если ты не сможешь пушку пользоваться ты не сможешь нами файтиться логично логично чисто после работы заходишь работать в гта факты факты ну когда страшная тема женек не гта на самом деле может завлечь вас пиздец потому что вы просто можете себе емс марчалочку найти либо например там какой-нибудь еще киберспортивную женщину прикольную всё и вы с ней,ru,0.989146,False,
87,88,segment 88,здесь и останетесь надолго ну надолги и года потому что здесь многие жизни отдают ну в хорошем плане они же сами вот блять вот сука я бы ему нахуй прям вот клянусь если бы вот я бы в реальной жизни бы также бы вот сейчас бы шёл бы мне у ёбища вот также бежал и очки были бы биты у него на лице я вам клянусь у него бы очки были бы биты наебали потому что ну тупорилы я клянусь вам подожди так доп нет у меня стоит быстрая слышишь походку меня стоит быстрой,ru,0.994931,False,
88,89,segment 89,"и идет и идет быстро она завлекает тех, но это еще кто?",ru,0.992475,False,
89,90,segment 90,Евгения Мактан Тамаю а не мне в этот при...,ru,0.990789,False,
90,91,segment 91,"а как мне выйти из нее потом? быстро, потому что я расстрелял факты, факты как ты вообще на шахту попал?",ru,0.997126,False,
91,92,segment 92,"мужики, просто пошел по заданиям заставили работать на шахту вывезли вывезли через телефон А у меня, чтоб ты понимал, телефон у меня только планшет, я ни телефона не покупал, ни сим-карты, хуйня вашей женщины...",ru,0.971751,False,
92,93,segment 93,"Ох... Я тут кентов нашел на ВН, мы просто бегали хуярились тазерами по приколу, кафели друг друга.",ru,0.868677,False,
93,94,segment 94,"Блять. А может быть на военку пойти, мужики?",ru,0.978233,False,
94,95,segment 95,"Ну там говорят, что пиздец как д... Ну сука, ну просто...",ru,0.988810,False,
95,96,segment 96,сын... Угу. Ага.,ru,0.545154,True,low_segment_confidence
96,97,segment 97,"Я вот чё думаю, может реально на военку пойти попробовать? Вот так и находит команда в семью.",ru,0.972132,False,
97,98,segment 98,"А все, мужики, мужики, последний раз отношу и иду дальше, потому что я же говорю, меня просто задание, короче, за вебкой, чтобы вы понимали сейчас я покажу как это выглядит, кто вдруг не видел.",ru,0.992861,False,
98,99,segment 99,"Короче, видите, вон задание за вебкой, за баннерами, и так далее просто ну так вышло что оно за этим за всем находится поэтому как бы вы не будете видеть и но я буду иногда вам говорить я иногда буду вам говорить ребята приетли янда жаль что же ты еще дома ее почему это пишет мне модер я не могу понять почему мне пишет этого именно модер алло жени мне мой тебе советы должен каждую неделю кидать отчеты или еще подожди отчёт иди в фемы",ru,0.992767,False,
99,100,segment 100,типа фемы это типа к фембойкам тоже для прошу на текущей цели заданий прийти в два задания актив так подожди вернитесь к путеводителю так подожди мне нужно к путеводителю не я понял почек за рау потому что гвоздик легенды с днем рождения черт так а у меня си у меня не сегодня день рождения алло у меня не сегодня,ru,0.979574,False,
100,101,segment 101,"Чё, пончик, рассказывай, чё у тебя ещё нового произошло интересного.",ru,0.991722,False,
101,102,segment 102,"Подожди, а мне прям далеко идти или нет? Просто если далеко, то надо где-то найти...",ru,0.938020,False,
102,103,segment 103,"Ну как бы, блядь, идти туда пешком, ну не вариант.",ru,0.976981,False,
103,104,segment 104,"Логично, подожди. Опана. Понял, понял, понял, понял, понял.",ru,0.977454,False,
104,105,segment 105,"Мужики, мужики. Бля, может помочь ему? Подожди. А так-то ствол имеется, мужики, может помочь ему?",ru,0.984639,False,
105,106,segment 106,"Может помочь ему зайти в этот вовну? Подожди, если я сейчас зайду вовнутрь, убью чела какой шанс что меня подвезут мать зашла в комнату и сказала блять в туалете невозможно находиться",ru,0.994992,False,
106,107,segment 107,там воняет да он не наш слон он на кипре ну тоже верно кипрский маньяк бля вот взять бы вот немножечко и угнать а она же не заведена что я не посмотрел так ладно подожди мне где взять скутер подожди смотри в госпиталь обязан будешь каждую неделю кидать отчет по своему действиям о вагасах фанках и еще какой-то край ему ордить тебе нихуя не надо будет кидать но вот это теща присылает бы если я буду,ru,0.987603,False,
107,108,segment 108,"бездельничать согласись но как бездельничать буду везет улицу вот это мне больше вот нравится намного причем я бы сказал что больше надо будет так возьми какой-то скутер так мужики его нужно взять себе в отдельном месте каком-то извиняюсь, вы сильно заняты?",ru,0.993401,False,
108,109,segment 109,"ну то вообще да ну сейчас подвезет меня кто-нибудь что я могу ага, понял, полицейский это шокетик кляни нет, нет, нет нет, нет, нет нет, я клянусь я клянусь, я погладить хотел я погладить хотел Да я погладить хотел, я не думал, что НКМ это удар,",ru,0.994082,False,
109,110,segment 110,"блять, в сфыра. Да тихо, тихо, мужики, клянусь, я погладить хотел, я не...",ru,0.967396,False,
110,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",ru,0.710987,True,low_segment_confidence
111,112,segment 112,"Было бы чудесно, мужики. Куда? Оставлю метку.",ru,0.928728,False,
112,113,segment 113,"Видно? Да, да, да. Спасибо большое, тут что-то, блять, идти очень далековато, на самом деле.",ru,0.977788,False,
113,114,segment 114,"Пиздать тебе... Не, выносливаться есть, просто далеко бежать я только начал.",ru,0.990625,False,
114,115,segment 115,А то поняли из шахты еще на другой конец города заставляет бежать.,ru,0.985016,False,

In [6]:
def get_openrouter_api_key() -> str:
    api_key = userdata.get("OPENROUTER_API_KEY")

    if not api_key:
        raise RuntimeError("OPENROUTER_API_KEY is not available in Colab Secrets")

    return api_key


HTTP_SESSION = requests.Session()
HTTP_SESSION.headers.update(
    {
        "Authorization": f"Bearer {get_openrouter_api_key()}",
        "Content-Type": "application/json",
    }
)

TOKEN_AUDIT_SCHEMA = {
    "type": "object",
    "properties": {
        "tokens": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "id": {"type": "integer"},
                    "kind": {
                        "type": "string",
                        "enum": ["language", "neutral", "proper_noun", "unknown"],
                    },
                    "language": {
                        "anyOf": [
                            {"type": "string", "minLength": 2, "maxLength": 8},
                            {"type": "null"},
                        ]
                    },
                },
                "required": ["id", "kind", "language"],
                "additionalProperties": False,
            },
        }
    },
    "required": ["tokens"],
    "additionalProperties": False,
}


def build_token_audit_prompt(text: str, tokens: list[dict[str, Any]]) -> str:
    token_payload = json.dumps(tokens, ensure_ascii=False)

    return f"""
Classify each provided transcript token using its context.

Use exactly one kind per token:
- language: an ordinary lexical token that carries a language
- neutral: numbers, punctuation, symbols, standalone technical markers, or non-linguistic tokens
- proper_noun: names, usernames, brands, game titles, place names, product names, server names, or named entities
- unknown: insufficient evidence to assign a reliable category

For kind=language, return an ISO 639-1 language code when possible.
For every other kind, language must be null.

Classify usage in this utterance, not etymological origin.
Borrowed or assimilated words used as part of the surrounding language should be assigned to that surrounding language.
Do not treat a name or brand as code-switching merely because its spelling originated in another language.
Do not assign a language to numbers.
Do not create, remove, merge, split, or reorder token IDs.

Transcript:
{text}

Tokens:
{token_payload}
""".strip()


def validate_token_audit(
    response_payload: dict[str, Any],
    source_tokens: list[dict[str, Any]],
) -> list[dict[str, Any]]:
    items = response_payload.get("tokens")

    if not isinstance(items, list):
        raise ValueError("Structured response does not contain tokens")

    expected_ids = [item["id"] for item in source_tokens]
    returned_ids = [item.get("id") for item in items]

    if returned_ids != expected_ids:
        raise ValueError("LLM token IDs do not exactly match source token IDs")

    source_by_id = {item["id"]: item["text"] for item in source_tokens}
    validated = []

    for item in items:
        token_id = item["id"]
        kind = str(item["kind"]).strip().lower()
        language = item.get("language")

        if kind == "language":
            if language is None or not str(language).strip():
                raise ValueError(f"Token {token_id} requires a language")
            language = normalize_language(language)
        else:
            language = None

        validated.append(
            {
                "id": token_id,
                "word": source_by_id[token_id],
                "kind": kind,
                "language": language,
            }
        )

    return validated


def audit_tokens_with_llm(
    text: str,
    tokens: list[dict[str, Any]],
) -> dict[str, Any]:
    payload = {
        "model": OPENROUTER_MODEL,
        "messages": [
            {
                "role": "user",
                "content": build_token_audit_prompt(text, tokens),
            }
        ],
        "provider": {"require_parameters": True},
        "response_format": {
            "type": "json_schema",
            "json_schema": {
                "name": "token_language_audit",
                "strict": True,
                "schema": TOKEN_AUDIT_SCHEMA,
            },
        },
        "plugins": [{"id": "response-healing"}],
    }

    last_error = None

    for attempt in range(1, MAX_RETRIES + 1):
        started_at = time.perf_counter()

        try:
            response = HTTP_SESSION.post(
                OPENROUTER_API_URL,
                json=payload,
                timeout=REQUEST_TIMEOUT_SECONDS,
            )
            response.raise_for_status()
            response_json = response.json()
            content = response_json["choices"][0]["message"]["content"]
            parsed = json.loads(content)
            validated = validate_token_audit(parsed, tokens)

            return {
                "tokens": validated,
                "response_id": response_json.get("id"),
                "model": response_json.get("model", OPENROUTER_MODEL),
                "usage": response_json.get("usage", {}),
                "elapsed_seconds": time.perf_counter() - started_at,
            }

        except (
            requests.RequestException,
            KeyError,
            IndexError,
            TypeError,
            ValueError,
            json.JSONDecodeError,
        ) as exc:
            last_error = exc

            if attempt == MAX_RETRIES:
                break

            delay = RETRY_BACKOFF_SECONDS * (2 ** (attempt - 1))
            delay += random.uniform(0, 0.5)
            time.sleep(delay)

    raise RuntimeError(
        f"LLM request failed after {MAX_RETRIES} attempts: {last_error}"
    )

In [7]:
def summarize_audited_tokens(
    audited_tokens: list[dict[str, Any]],
) -> dict[str, Any]:
    language_tokens = [
        item for item in audited_tokens if item["kind"] == "language"
    ]

    excluded_tokens = [
        item for item in audited_tokens if item["kind"] != "language"
    ]

    counts = Counter(item["language"] for item in language_tokens)
    total_language_tokens = sum(counts.values())
    words_by_language = defaultdict(list)

    for item in language_tokens:
        words_by_language[item["language"]].append(item["word"])

    percentages = {
        language: count / total_language_tokens * 100
        for language, count in counts.items()
    } if total_language_tokens else {}

    excluded_by_kind = defaultdict(list)

    for item in excluded_tokens:
        excluded_by_kind[item["kind"]].append(item["word"])

    return {
        "counts": dict(counts),
        "percentages": percentages,
        "words_by_language": dict(words_by_language),
        "excluded_by_kind": dict(excluded_by_kind),
        "language_token_count": total_language_tokens,
    }


def lexical_token_count(tokens: list[dict[str, Any]]) -> int:
    return sum(is_alphabetic_token(item["text"]) for item in tokens)


def run_hybrid_audit(
    screen_dataframe: pd.DataFrame,
    screen_detail_map: dict[str, Any],
    internal_language: str,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, dict[str, Any]]:
    rows = []
    token_rows = []
    request_rows = []
    deep_details = {}

    total_segments = len(screen_dataframe)

    for position, row in enumerate(screen_dataframe.itertuples(index=False), start=1):
        detail = screen_detail_map[row.segment]

        if not row.needs_deep_audit:
            word_count = lexical_token_count(detail["tokens"])
            rows.append(
                {
                    "segment_index": row.segment_index,
                    "segment": row.segment,
                    "text": row.text,
                    "source": "fasttext_clear",
                    "language": row.fasttext_language,
                    "percentage": 100.0,
                    "word_count": word_count,
                    "mismatch_words": "",
                    "excluded_words": "",
                    "fasttext_language": row.fasttext_language,
                    "fasttext_confidence": row.fasttext_confidence,
                    "screening_reason": row.screening_reason,
                }
            )
            continue

        print(f"[{position}/{total_segments}] Deep audit {row.segment}")

        audit = audit_tokens_with_llm(row.text, detail["tokens"])
        summary = summarize_audited_tokens(audit["tokens"])
        deep_details[row.segment] = {
            "audit": audit,
            "summary": summary,
        }

        request_rows.append(
            {
                "segment": row.segment,
                "response_id": audit["response_id"],
                "model": audit["model"],
                "elapsed_seconds": audit["elapsed_seconds"],
                "prompt_tokens": audit["usage"].get("prompt_tokens"),
                "completion_tokens": audit["usage"].get("completion_tokens"),
                "total_tokens": audit["usage"].get("total_tokens"),
            }
        )

        for item in audit["tokens"]:
            token_rows.append(
                {
                    "segment_index": row.segment_index,
                    "segment": row.segment,
                    "text": row.text,
                    **item,
                }
            )

        excluded_words = "; ".join(
            f"{kind}: {', '.join(words)}"
            for kind, words in summary["excluded_by_kind"].items()
            if words
        )

        if not summary["percentages"]:
            rows.append(
                {
                    "segment_index": row.segment_index,
                    "segment": row.segment,
                    "text": row.text,
                    "source": "llm_audit",
                    "language": "unknown",
                    "percentage": 100.0,
                    "word_count": 0,
                    "mismatch_words": "",
                    "excluded_words": excluded_words,
                    "fasttext_language": row.fasttext_language,
                    "fasttext_confidence": row.fasttext_confidence,
                    "screening_reason": row.screening_reason,
                }
            )
            continue

        for language, percentage in summary["percentages"].items():
            words = summary["words_by_language"].get(language, [])
            rows.append(
                {
                    "segment_index": row.segment_index,
                    "segment": row.segment,
                    "text": row.text,
                    "source": "llm_audit",
                    "language": language,
                    "percentage": percentage,
                    "word_count": summary["counts"][language],
                    "mismatch_words": (
                        "" if language == internal_language else ", ".join(words)
                    ),
                    "excluded_words": excluded_words,
                    "fasttext_language": row.fasttext_language,
                    "fasttext_confidence": row.fasttext_confidence,
                    "screening_reason": row.screening_reason,
                }
            )

    result_df = pd.DataFrame(rows)
    token_df = pd.DataFrame(token_rows)
    request_df = pd.DataFrame(request_rows)

    if not result_df.empty:
        result_df["is_internal_language"] = (
            result_df["language"] == internal_language
        )
        result_df["material_mismatch"] = (
            ~result_df["is_internal_language"]
            & (result_df["language"] != "unknown")
            & (result_df["word_count"] >= MIN_MISMATCH_WORDS)
            & (result_df["percentage"] >= MIN_MISMATCH_PERCENTAGE)
        )
        result_df = result_df.sort_values(
            by=[
                "material_mismatch",
                "is_internal_language",
                "percentage",
                "language",
                "segment_index",
            ],
            ascending=[False, True, False, True, True],
        ).reset_index(drop=True)

    return result_df, token_df, request_df, deep_details


result_df, token_df, request_df, deep_details = run_hybrid_audit(
    screen_df,
    screen_details,
    internal_lang,
)

[18/714] Deep audit segment 18
[29/714] Deep audit segment 29
[96/714] Deep audit segment 96
[111/714] Deep audit segment 111
[137/714] Deep audit segment 137
[186/714] Deep audit segment 186
[211/714] Deep audit segment 211
[232/714] Deep audit segment 232
[238/714] Deep audit segment 238
[289/714] Deep audit segment 289
[296/714] Deep audit segment 296
[307/714] Deep audit segment 307
[309/714] Deep audit segment 309
[310/714] Deep audit segment 310
[350/714] Deep audit segment 350
[399/714] Deep audit segment 399
[427/714] Deep audit segment 427
[452/714] Deep audit segment 452
[468/714] Deep audit segment 468
[488/714] Deep audit segment 488
[520/714] Deep audit segment 520
[573/714] Deep audit segment 573
[593/714] Deep audit segment 593
[600/714] Deep audit segment 600
[689/714] Deep audit segment 689
[708/714] Deep audit segment 708

In [8]:
display_df = result_df.copy()

if not display_df.empty:
    display_df["percentage"] = display_df["percentage"].map(
        lambda value: f"{value:.1f}%"
    )
    display_df["fasttext_confidence"] = display_df["fasttext_confidence"].map(
        lambda value: f"{value:.3f}"
    )
    display_df = display_df[
        [
            "segment",
            "text",
            "source",
            "language",
            "percentage",
            "word_count",
            "material_mismatch",
            "mismatch_words",
            "excluded_words",
            "fasttext_language",
            "fasttext_confidence",
            "screening_reason",
        ]
    ]

print("Session ID       :", session_row["gamesession_id"])
print("Internal language:", internal_lang)

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(display_df)

Session ID       : 140595413
Internal language: ru

,segment,text,source,language,percentage,word_count,material_mismatch,mismatch_words,excluded_words,fasttext_language,fasttext_confidence,screening_reason
0,segment 1,кушать готовил очень вкусненько но приходите присаживайся реально надо подождем блин гта да ну на худа хики еще азиатик здорово привет моя киса я если что натурал сразу говорю я с азиатиком не заигрываю никогда я натурал уверенный в себе мужчина йоу я натурал уверенный,fasttext_clear,ru,100.0%,45,False,,,ru,0.972,
1,segment 2,"Вот он какой маленький сидит, сладенький, вкусненький и все, Дэнс.",fasttext_clear,ru,100.0%,10,False,,,ru,0.804,
2,segment 3,"Зря ты так с ним. Ну не знаю, на самом деле 50 на 50, мужики.",fasttext_clear,ru,100.0%,13,False,,,ru,0.961,
3,segment 4,"50 на 50, я бы сказал бы. А у тебя что, дела? Нет, на дорожке?",fasttext_clear,ru,100.0%,13,False,,,ru,0.990,
4,segment 5,"О, нифига себе. А подожди, зачем тебе дорожка? и так худая, я прям...",fasttext_clear,ru,100.0%,13,False,,,ru,0.900,
5,segment 6,"Максимально я бы сказал, что ты худая. Подожди, где я должен был бы возродиться?",fasttext_clear,ru,100.0%,14,False,,,ru,0.999,
6,segment 7,"Скорее всего, где-то здесь. нужно возродиться. Бля, ну если нет, нет, семейный офис.",fasttext_clear,ru,100.0%,14,False,,,ru,0.992,
7,segment 8,"Нет, как будто бы начальник спал. место выхода да мне нужно вместо выхода подожди что ты пишешь хрюндель ты долбоеб хрюндель вот скажи мне честно ты дурачок или что вот если тебе ну не купили гта в детстве ты не попробовал гта это не значит что гта его ну не очень согласись не может быть что гта для тебя полная фигня я вообще никогда не поверю я знаю только одно что тебе нравится гта в целом так Дополнительное",fasttext_clear,ru,100.0%,79,False,,,ru,0.995,
8,segment 9,"до свидания, я хочу поработать у вас 600 долларов на шахте!",fasttext_clear,ru,100.0%,11,False,,,ru,0.944,
9,segment 10,"Здорово мужики, как у вас дела? меня GTA уже несколько лета, ну так заходи, немедленно на memphis, по правому коду плюс w у тебя будет плюс 5 тысячи долларов, плюс у тебя еще будет 7 невипки, не забывай.",fasttext_clear,ru,100.0%,36,False,,,ru,0.953,
10,segment 11,"Так, ладно, зарабатывайте 600 долларов на шахте, а я же вроде бы заработал, нет?",fasttext_clear,ru,100.0%,13,False,,,ru,0.956,
11,segment 12,"Подожди, а что там? Надо побежать, сейчас буду.",fasttext_clear,ru,100.0%,8,False,,,ru,0.995,
12,segment 13,Majestic вперед! ну мужики алгава джестик получается в штрихе плюсядера у мучачи с как дела жду не дождольсь когда пройду 7 дней буду обменивать скины на бабочку ручная роспись вы говнюки вы все сейчас будете с бабочками а мне когда подарите ну придать прит зузи лики ну не уходи у меня у меня потери пока тут но нет что,fasttext_clear,ru,100.0%,59,False,,,ru,0.984,
13,segment 14,"уходить то какая разница то посиди посидим посидим посидим что мужики как у вас дела чем занимались это у меня вон хрюндель уже есть собирать жени го когда я приличу будем играть вместе вообще каждый день готов играть в эту прекрасную игру йоу на мемфисе плюс мы спокойно вступили и можем все вступить в семью к диману и с ними играть я считаю плюс даже если меня что-то не сложится, вы можете с",fasttext_clear,ru,100.0%,76,False,,,ru,0.990,
14,segment 15,ними остаться и играть как бы мне не то что не жалко только лучше для ребят сделаю и все у пани уже бабочка а я помню бабочка имеет теперь мне надо ну я помню что он какую-то да хотел купить себе бабочку это было неплохо не ну конечно хрюндель это исчез и пиздец ну как будто бы и вот хрюндель как будто бы именно злыдня знаете ли,fasttext_clear,ru,100.0%,69,False,,,ru,0.994,
15,segment 16,"Сын прараба, ну, прездорово. Да ничего, сойдёт ты, как горит.",fasttext_clear,ru,100.0%,10,False,,,ru,0.965,
16,segment 17,"А чего у вас-то, когда хикиш, куда пойдёте вы? С вами гребазанами.",fasttext_clear,ru,100.0%,13,False,,,ru,0.962,
17,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",llm_audit,ru,100.0%,15,False,,,ru,0.741,low_segment_confidence
18,segment 19,"Как дела? Всё нормально, кепычи, у тебя как дела? Не, я вроде такого не говорил.",fasttext_clear,ru,100.0%,15,False,,,ru,0.979,
19,segment 20,"Я говорил, как у этого, если что-то устроит, то пойду. Не, ты чего?",fasttext_clear,ru,100.0%,14,False,,,ru,0.996,
20,segment 21,"Ё-у, здорово, Никси, как у тебя дела? У него кровавый Путин в это...",fasttext_clear,ru,100.0%,15,False,,,ru,0.995,
21,segment 22,"О, прикольно, красная такая, я хочу фиолетовую.",fasttext_clear,ru,100.0%,8,False,,,ru,0.965,
22,segment 23,"блин, фиолетовая, я помню, помню как выглядит фиолетовая, она выглядит намного лучше, честно говоря.",fasttext_clear,ru,100.0%,14,False,,,ru,0.982,
23,segment 24,"Она выглядит... Бля, я забыл как поменять, например, раскладку бега, потому что здесь же если поменять походку, то будет намного быстрее идти.",fasttext_clear,ru,100.0%,22,False,,,ru,0.997,
24,segment 25,"Ну ладно, я никуда и не тороплюсь в целом-то на самом деле.",fasttext_clear,ru,100.0%,13,False,,,ru,0.939,
25,segment 26,"Но я на Сан-Дранциско играю и на мемписе. Во, немного, чисто тачка есть и всё, и второй левел лоперса, и промо кодик не забудь вести плюс w у тебя будет на третьем левеле перса вроде да на третьем левеле перса у тебя будет 50 тысяч лишних денег и 7 не премиума f2 на строке там будет да я это я понял просто долго искать я считаю я уже водил промо ошибка ошибка ошибка самая большая ошибка которая ты",fasttext_clear,ru,100.0%,78,False,,,ru,0.958,
26,segment 27,мог сделать ну мы никогда не пойдем и не идем точно я вообще с если чё и бэкнусь блин ну грустно на самом деле что решили больше никакой пока проект вы не идти но если чё приходите на маджестик на этот на мемфис вайнот как говорится ладно я папки поэтому отошел давай все наилучшего а я чё знаю что ты на матч перешел ну йоу йоу женёк на церковь меня вид,fasttext_clear,ru,100.0%,73,False,,,ru,0.988,
27,segment 28,"ходьбы настройки перса подожди вид ходьбы или прям именно дожди ну персонаж наверное ну не ну вот видите здесь просто очень много всего и здесь события как будто бы набор во фракцию фибов я бы сходил на самом деле аукцион контейнеров через но мне денег не хватит вагаса не хочу Я бы пошел либо в МАС, а может реально пойти МАС девочку, фемочку найти себе,",fasttext_clear,ru,100.0%,66,False,,,ru,0.974,
28,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",llm_audit,ru,100.0%,15,False,,,ru,0.966,foreign_window_detected
29,segment 30,"Путь бомжика в ГТА, что Ну не то чтобы путь бомжика, мужики.",fasttext_clear,ru,100.0%,12,False,,,ru,0.999,
30,segment 31,"Плюс у меня пока нет брички, пока у меня нет брички, но у меня есть наш на раз курица для брички, мужики, йоу!",fasttext_clear,ru,100.0%,23,False,,,ru,0.968,
31,segment 32,"Претик сладенький, лучший, вежливый, добрый, красивый, отважный, мужественный, благоподобный, Евгешенька, день 32, дай за попу потрогать, нет, райкош, заходи сюда и потрогаешь, йоу, на мемфисе можно всё, мужики, сами понимаете, и побрить, и за попу потрогать, ну сразу говорю, брить мне не надо, даже в шутку, мужики, брить меня не надо, спасибо, ошибка у фибов мало возможностей и они по дк работать не могут, Здарова патриотич, нууу",fasttext_clear,ru,100.0%,67,False,,,ru,0.981,
32,segment 33,"тогда в емс идем к мурчалочкам Ебанулся емс это вообще рпшная хуйня, не подожди смотри Ай, ну а наху, ох, извини пожалуйста Не то что емс это рпшная штука это факт, но все же почему бы мне не по взаимодейству с женщинами Ты же там взаимодейству женщинами поня, ох Нихуя подожди ты че, не работай гора, начало не надо, не надо, ну вылезни из меня, вылезни",fasttext_clear,ru,100.0%,68,False,,,ru,0.992,
33,segment 34,"f1, а там дальше сам ищи а понял, f1 в потом мужики как говорится, как пригодится дай, дай, дай, дай, завези, завези, завези надо на что-нибудь нажать не надо ебать он просто встал Джейм, ты через что захочешь, через их лаунчер стиль бегана быстро поменяй А там я не могу найти, чём дело райкоши, я не очень нашёл где стиль бега Как прям это всё",fasttext_clear,ru,100.0%,68,False,,,ru,0.989,
34,segment 35,"пишется, типа f2, настройки, ну смотри f2 Ааа, на...",fasttext_clear,ru,100.0%,11,False,,,ru,0.981,
35,segment 36,"Настройки, подожди, настройки Ааа, стиль бега Или как там дальше, подожди Стиль...",fasttext_clear,ru,100.0%,14,False,,,ru,0.972,
36,segment 37,"Ну смотри вот, безопасность, настройки, прицелы, макросы, название клавиш, игровой чат, настройка звука Дополнительно Понимаешь?",fasttext_clear,ru,100.0%,16,False,,,ru,0.986,
37,segment 38,"Быстрее начало идти, или мне кажется? Да мой маленький, не эту штуку, потому что нам нужно 600 долларов.",fasttext_clear,ru,100.0%,17,False,,,ru,0.994,
38,segment 39,"Выбери, Вася. Так, я же выбрал. Подожди.",fasttext_clear,ru,100.0%,7,False,,,ru,0.979,
39,segment 40,"Что, не выбрал? Подожди. Так, настройки дополните.",fasttext_clear,ru,100.0%,7,False,,,ru,0.958,
40,segment 41,"Ну, быстро все. Не-не-не. У меня, короче, за вебкой я все выбрал.",fasttext_clear,ru,100.0%,14,False,,,ru,0.973,
41,segment 42,"Я все выбрал. У меня за вебкой все выбрал. О, ты на матч пришел? Да, мужики.",fasttext_clear,ru,100.0%,16,False,,,ru,0.980,
42,segment 43,"На Majestic, на Memphis можете заходить, если хотите. По промокоду plusw у вас будет плюс пятьдесят тысяч долларов на балансике на третьем левле плюс семь дней випочки вайноут как говорится как быстрее будет а ты не подтвердил так нет я все подтвердил анимации можешь да анимации могу Женя сделай магазин кейса Женя сделай магазин кейса это как то погоди магазин кейса а ты хочешь чтобы я щас какой нибудь кейсик отверл давай а реально мужики может",fasttext_clear,ru,100.0%,77,False,,,ru,0.967,
43,segment 44,какой нибудь может быть машинку выбьем Клянись.,fasttext_clear,ru,100.0%,8,False,,,ru,0.997,
44,segment 45,"-ха-ха! Мужики, может быть Олэнчик дадим?",fasttext_clear,ru,100.0%,7,False,,,ru,0.985,
45,segment 46,Может быть Олэнчик дадим? Такой киберспортивный.,fasttext_clear,ru,100.0%,6,False,,,ru,0.981,
46,segment 47,"Мужики, может быть кибера? А ты купил стартовую петель для персонажа?",fasttext_clear,ru,100.0%,11,False,,,ru,0.990,
47,segment 48,Еще пока нет. Я думаю залудить на машину.,fasttext_clear,ru,100.0%,8,False,,,ru,0.948,
48,segment 49,Да хватит стучать! Купи парочку. Прокачку персонажа купить?,fasttext_clear,ru,100.0%,8,False,,,ru,0.896,
49,segment 50,"Давайте одну машинку Откроем, мужики, одну машинку сейчас.",fasttext_clear,ru,100.0%,8,False,,,ru,0.873,
50,segment 51,"Ой-ой-ой-ой-ой-ой-ой-ой. Сю-ю-ю. Отдай какой-нибудь Gold, пожалуйста.",fasttext_clear,ru,100.0%,16,False,,,ru,0.985,
51,segment 52,"О-о-о-о, вот вот это, вот это, вот это, вот это. Ну, какой лимузин.",fasttext_clear,ru,100.0%,16,False,,,ru,0.996,
52,segment 53,"Подожди, патриот. Ха-ха-ха-ха. Ну, куда мне, подожди, ну, куда мне на нём ездить?",fasttext_clear,ru,100.0%,16,False,,,ru,0.907,
53,segment 54,"Подожди, зря самуюбищный кейс. Подожди, ладно, продаю.",fasttext_clear,ru,100.0%,7,False,,,ru,0.987,
54,segment 55,"А какой мне тогда кейс посоветую, чтобы выбить машину? Потому что я бы хотел бы как бы одну машинку выбить.",fasttext_clear,ru,100.0%,20,False,,,ru,0.999,
55,segment 56,"У меня просто... Боже, это вот тоже...",fasttext_clear,ru,100.0%,8,False,,,ru,0.994,
56,segment 57,"тиши тиши лодим лодим лодим может быть какой посоветуешь ладно патруот чокей окей послушаю тебя какой посоветуешь париря и просто мне бы хотелось машина просто я видел здесь премиум автомобиля выплата мне за эдиты выдаю и после стрима не забудьки нахуй выплаты за эдиты а за три эдита ты сделала три эдита точно сколько я тебе там обещал напомню пожалуйста,",fasttext_clear,ru,100.0%,61,False,,,ru,0.976,
57,segment 58,"просто Короче, рассказываю полгода или год, короче, нет, полгода назад, я помню, что была зима, я Никсику говорю, Никсик, делаешь три видео и я тебе выплачиваю за это.",fasttext_clear,ru,100.0%,28,False,,,ru,0.992,
58,segment 59,"Сколько я не помню, клянусь Через полгода Никсик течение полугода делал три видео, скидывал и говорит 6 что вы понимали я из них выставил только один я как сейчас помню",fasttext_clear,ru,100.0%,29,False,,,ru,0.989,
59,segment 60,а сколько эти нахуй какая нахуй зима я зимой с тобой а сколько эти обещал подожди я даже не помню сколько эти обещал клянусь выпла выплато будет выплато будет просто я не помню сколько напомним мне пожалуйста клянусь я уже забыл что мы с тобой чем-то вообще договаривались пол месяца вы понимаете пол года делала 6 видосов ну ладно 2 месяца нормально вчера рик бабыч у меня на стриме проебал тысячой 4800 нормально эля здорово как дела кто пойдет стримера трогать за,fasttext_clear,ru,100.0%,81,False,,,ru,0.988,
60,segment 61,"попу и брить не надо райкош меня брить 6 видосов 500 рублей нихуя я что-то загнул слышишь ну да выплачу выплачу шесть соток ой пять соток но что это хуя за такие Ну, без про...",fasttext_clear,ru,100.0%,36,False,,,ru,0.993,
61,segment 62,"Не-не, всё нормально, выплачу, выплачу. После стрима.",fasttext_clear,ru,100.0%,9,False,,,ru,0.983,
62,segment 63,"Я уж и забыл, блять. А ты только зайди, ты платишь и её не запросмотришь?",fasttext_clear,ru,100.0%,15,False,,,ru,0.997,
63,segment 64,"Так там мужики, короче, рассказывают. Никсик начала всякие видосики делать, и нам скидывать в чате к ТГ-канала.",fasttext_clear,ru,100.0%,18,False,,,ru,0.977,
64,segment 65,"И я решил её поддержать, такой, сделай мне пару видосиков, я тебе, денюшкой.",fasttext_clear,ru,100.0%,13,False,,,ru,0.986,
65,segment 66,"Но кто знал, что она будет полгода видосов не делать?",fasttext_clear,ru,100.0%,10,False,,,ru,0.992,
66,segment 67,"Клянусь, забыл. Я помню, что я её поддержать хотел, ну, начального, ну, типа, человека, который едет и делает.",fasttext_clear,ru,100.0%,18,False,,,ru,0.997,
67,segment 68,"Она что-то училась в этот момент, и всё. Вот как она, говорит, что и сделала, всё.",fasttext_clear,ru,100.0%,17,False,,,ru,0.997,
68,segment 69,"Вообще, проблем, всё нормально. Ну, блять, не за полгода же.",fasttext_clear,ru,100.0%,10,False,,,ru,0.963,
69,segment 70,"Жень, купи снарягу, то у меня право... Ааа, подожди, прорабы и контракт возьми.",fasttext_clear,ru,100.0%,13,False,,,ru,0.936,
70,segment 71,"Так, а мне нужно ещё два раза отнести, у меня, короче, задание за вебкой.",fasttext_clear,ru,100.0%,14,False,,,ru,0.963,
71,segment 72,"Мужики, меня задание за вебкой, мне нужно заработать 6 соток. Я уже заработал 324, т.е.",fasttext_clear,ru,100.0%,14,False,,,ru,0.990,
72,segment 73,"вот я сейчас отнесу и еще один раз отнесу, и мы идем дальше задания выполнять.",fasttext_clear,ru,100.0%,15,False,,,ru,0.970,
73,segment 74,"Я как понимаю, мне нужно сначала сделать начальные задания, и потом мы просто берем, я не знаю, на второй или на третий день уже, просто беремся, собираемся и едем ту улицу.",fasttext_clear,ru,100.0%,31,False,,,ru,0.982,
74,segment 75,Надо будет машинку и так далее. Ты на Мемфисе?,fasttext_clear,ru,100.0%,9,False,,,ru,0.952,
75,segment 76,"Тот самый долбоеб, которому я напрямую сказал, мы идем на Мемфис.",fasttext_clear,ru,100.0%,11,False,,,ru,0.974,
76,segment 77,"Он пишет, ууу, ты на Мемфисе? Ну да, слышишь?",fasttext_clear,ru,100.0%,9,False,,,ru,0.962,
77,segment 78,ещё раз стиль походки багнулся думаешь?,fasttext_clear,ru,100.0%,6,False,,,ru,0.998,
78,segment 79,окей щас да не говорил в стриме не не говорил и не раз мужики вы чё,fasttext_clear,ru,100.0%,16,False,,,ru,0.915,
79,segment 80,бумс так так снаряка тебе даю чтобы ты два раза мог с копать они по одной да тут уже нет а снаряка платная??,fasttext_clear,ru,100.0%,23,False,,,ru,0.986,
80,segment 81,"она же платная зачем мне платная снаряка Как я понял, платная, только смысл, типа, у от этой платной снаряги.",fasttext_clear,ru,100.0%,19,False,,,ru,0.988,
81,segment 82,"Забей уже тогда. Мне просто еще один разочек отнести, я уже все это...",fasttext_clear,ru,100.0%,14,False,,,ru,0.981,
82,segment 83,"Кстати, так я так и не понял, Патриоточ, какой мне нужен этот...",fasttext_clear,ru,100.0%,14,False,,,ru,0.984,
83,segment 84,"Скажи мне, пожалуйста, какой мне нужен кейс для машины.",fasttext_clear,ru,100.0%,10,False,,,ru,0.987,
84,segment 85,"Женя Аля. Что именно ты? Скажи, пожалуйста, что именно ты. Хочешь, заходи.",fasttext_clear,ru,100.0%,12,False,,,ru,0.994,
85,segment 86,"Хуйня ваши кейсы. Не-не-не, я хочу именно бричку выбить, мужики.",fasttext_clear,ru,100.0%,12,False,,,ru,0.932,
86,segment 87,Че мне делать? ну качни третий левел чтобы ты тоже мог пушкой пользоваться ну там второй левел качни я не знаю чтобы ты мог короче пушкой пользоваться а то если ты не сможешь пушку пользоваться ты не сможешь нами файтиться логично логично чисто после работы заходишь работать в гта факты факты ну когда страшная тема женек не гта на самом деле может завлечь вас пиздец потому что вы просто можете себе емс марчалочку найти либо например там какой-нибудь еще киберспортивную женщину прикольную всё и вы с ней,fasttext_clear,ru,100.0%,89,False,,,ru,0.989,
87,segment 88,здесь и останетесь надолго ну надолги и года потому что здесь многие жизни отдают ну в хорошем плане они же сами вот блять вот сука я бы ему нахуй прям вот клянусь если бы вот я бы в реальной жизни бы также бы вот сейчас бы шёл бы мне у ёбища вот также бежал и очки были бы биты у него на лице я вам клянусь у него бы очки были бы биты наебали потому что ну тупорилы я клянусь вам подожди так доп нет у меня стоит быстрая слышишь походку меня стоит быстрой,fasttext_clear,ru,100.0%,95,False,,,ru,0.995,
88,segment 89,"и идет и идет быстро она завлекает тех, но это еще кто?",fasttext_clear,ru,100.0%,12,False,,,ru,0.992,
89,segment 90,Евгения Мактан Тамаю а не мне в этот при...,fasttext_clear,ru,100.0%,10,False,,,ru,0.991,
90,segment 91,"а как мне выйти из нее потом? быстро, потому что я расстрелял факты, факты как ты вообще на шахту попал?",fasttext_clear,ru,100.0%,21,False,,,ru,0.997,
91,segment 92,"мужики, просто пошел по заданиям заставили работать на шахту вывезли вывезли через телефон А у меня, чтоб ты понимал, телефон у меня только планшет, я ни телефона не покупал, ни сим-карты, хуйня вашей женщины...",fasttext_clear,ru,100.0%,36,False,,,ru,0.972,
92,segment 93,"Ох... Я тут кентов нашел на ВН, мы просто бегали хуярились тазерами по приколу, кафели друг друга.",fasttext_clear,ru,100.0%,18,False,,,ru,0.869,
93,segment 94,"Блять. А может быть на военку пойти, мужики?",fasttext_clear,ru,100.0%,8,False,,,ru,0.978,
94,segment 95,"Ну там говорят, что пиздец как д... Ну сука, ну просто...",fasttext_clear,ru,100.0%,12,False,,,ru,0.989,
95,segment 96,сын... Угу. Ага.,llm_audit,ru,100.0%,4,False,,,ru,0.545,low_segment_confidence
96,segment 97,"Я вот чё думаю, может реально на военку пойти попробовать? Вот так и находит команда в семью.",fasttext_clear,ru,100.0%,17,False,,,ru,0.972,
97,segment 98,"А все, мужики, мужики, последний раз отношу и иду дальше, потому что я же говорю, меня просто задание, короче, за вебкой, чтобы вы понимали сейчас я покажу как это выглядит, кто вдруг не видел.",fasttext_clear,ru,100.0%,34,False,,,ru,0.993,
98,segment 99,"Короче, видите, вон задание за вебкой, за баннерами, и так далее просто ну так вышло что оно за этим за всем находится поэтому как бы вы не будете видеть и но я буду иногда вам говорить я иногда буду вам говорить ребята приетли янда жаль что же ты еще дома ее почему это пишет мне модер я не могу понять почему мне пишет этого именно модер алло жени мне мой тебе советы должен каждую неделю кидать отчеты или еще подожди отчёт иди в фемы",fasttext_clear,ru,100.0%,85,False,,,ru,0.993,
99,segment 100,типа фемы это типа к фембойкам тоже для прошу на текущей цели заданий прийти в два задания актив так подожди вернитесь к путеводителю так подожди мне нужно к путеводителю не я понял почек за рау потому что гвоздик легенды с днем рождения черт так а у меня си у меня не сегодня день рождения алло у меня не сегодня,fasttext_clear,ru,100.0%,60,False,,,ru,0.980,

In [9]:
mismatch_df = result_df.loc[
    ~result_df["is_internal_language"]
    & (result_df["language"] != "unknown")
].copy()

if not mismatch_df.empty:
    mismatch_df["percentage"] = mismatch_df["percentage"].map(
        lambda value: f"{value:.1f}%"
    )
    mismatch_df["fasttext_confidence"] = mismatch_df["fasttext_confidence"].map(
        lambda value: f"{value:.3f}"
    )
    mismatch_df = mismatch_df[
        [
            "segment",
            "text",
            "language",
            "percentage",
            "word_count",
            "material_mismatch",
            "mismatch_words",
            "excluded_words",
            "fasttext_language",
            "fasttext_confidence",
            "screening_reason",
        ]
    ]

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(mismatch_df)

Empty DataFrame
Columns: [segment_index, segment, text, source, language, percentage, word_count, mismatch_words, excluded_words, fasttext_language, fasttext_confidence, screening_reason, is_internal_language, material_mismatch]
Index: []

In [10]:
def build_session_summary(result_dataframe: pd.DataFrame) -> pd.DataFrame:
    valid = result_dataframe.loc[
        result_dataframe["language"] != "unknown"
    ].copy()

    if valid.empty:
        return pd.DataFrame(
            columns=["language", "word_count", "percentage"]
        )

    summary = (
        valid.groupby("language", as_index=False)["word_count"]
        .sum()
        .sort_values("word_count", ascending=False)
        .reset_index(drop=True)
    )

    total = summary["word_count"].sum()
    summary["percentage"] = summary["word_count"] / total * 100 if total else 0.0
    return summary


session_summary_df = build_session_summary(result_df)
session_summary_display_df = session_summary_df.copy()

if not session_summary_display_df.empty:
    session_summary_display_df["percentage"] = session_summary_display_df[
        "percentage"
    ].map(lambda value: f"{value:.1f}%")

with pd.option_context(
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
    "display.max_rows", None,
):
    display(session_summary_display_df)

  language  word_count percentage
0       ru       14666     100.0%

In [11]:
if not token_df.empty:
    with pd.option_context(
        "display.max_columns", None,
        "display.max_colwidth", None,
        "display.width", None,
        "display.max_rows", None,
    ):
        display(token_df)

if not request_df.empty:
    with pd.option_context(
        "display.max_columns", None,
        "display.max_colwidth", None,
        "display.width", None,
        "display.max_rows", None,
    ):
        display(request_df)

,segment_index,segment,text,id,word,kind,language
0,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",0,А,language,ru
1,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",1,кто,language,ru
2,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",2,-то,language,ru
3,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",3,"говорил,",language,ru
4,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",4,я,language,ru
5,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",5,на,language,ru
6,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",6,"матче,",language,ru
7,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",7,да,language,ru
8,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",8,"не,",language,ru
9,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",9,да,language,ru
10,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",10,"не,",language,ru
11,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",11,я,language,ru
12,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",12,такого,language,ru
13,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",13,не,language,ru
14,18,segment 18,"А кто-то говорил, я на матче, да не, да не, я такого не говорил.",14,говорил.,language,ru
15,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",0,которая,language,ru
16,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",1,будет,language,ru
17,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",2,мне,language,ru
18,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",3,мурчать,language,ru
19,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",4,"постоянно,",language,ru
20,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",5,ну?,language,ru
21,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",6,"Подожди,",language,ru
22,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",7,а,language,ru
23,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",8,че,language,ru
24,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",9,я,language,ru
25,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",10,там,language,ru
26,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",11,че,language,ru
27,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",12,-то,language,ru
28,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",13,не,language,ru
29,29,segment 29,"которая будет мне мурчать постоянно, ну? Подожди, а че я там че-то не взял?",14,взял?,language,ru
30,96,segment 96,сын... Угу. Ага.,0,просто...,language,ru
31,96,segment 96,сын... Угу. Ага.,1,сын...,language,ru
32,96,segment 96,сын... Угу. Ага.,2,Угу.,language,ru
33,96,segment 96,сын... Угу. Ага.,3,Ага.,language,ru
34,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",0,"Мужики,",language,ru
35,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",1,здравствуйте.,language,ru
36,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",2,"О,",language,ru
37,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",3,если,language,ru
38,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",4,"можно,",language,ru
39,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",5,если,language,ru
40,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",6,"можно,",language,ru
41,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",7,если,language,ru
42,111,segment 111,"Мужики, здравствуйте. О, если можно, если можно, если можно.",8,можно.,language,ru
43,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",0,"А,",language,ru
44,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",1,фэмилист.,language,ru
45,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",2,слова...,language,ru
46,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",3,От,language,ru
47,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",4,слова,language,ru
48,137,segment 137,"А, фэмилист. слова... От слова фэмилист.",5,фэмилист.,language,ru
49,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",0,но,language,ru
50,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",1,я,language,ru
51,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",2,тоже,language,ru
52,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",3,бы,language,ru
53,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",4,блядь,language,ru
54,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",5,с,language,ru
55,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",6,этим,language,ru
56,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",7,бомжом,language,ru
57,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",8,на,language,ru
58,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",9,скутере,language,ru
59,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",10,бы,language,ru
60,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",11,не,language,ru
61,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",12,общался,language,ru
62,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",13,если,language,ru
63,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",14,бы,language,ru
64,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",15,меня,language,ru
65,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",16,был,language,ru
66,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",17,бы,language,ru
67,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",18,марседес,proper_noun,None
68,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",19,клянусь,language,ru
69,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",20,если,language,ru
70,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",21,бы,language,ru
71,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",22,меня,language,ru
72,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",23,был,language,ru
73,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",24,бы,language,ru
74,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",25,марседес,proper_noun,None
75,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",26,я,language,ru
76,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",27,бы,language,ru
77,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",28,тоже,language,ru
78,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",29,бы,language,ru
79,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",30,не,language,ru
80,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",31,отвечал,language,ru
81,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",32,бы,language,ru
82,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",33,такому,language,ru
83,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",34,хуй,language,ru
84,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",35,сосу,language,ru
85,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",36,рыжий,language,ru
86,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",37,а,language,ru
87,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",38,почему,language,ru
88,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",39,я,language,ru
89,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",40,рыжий,language,ru
90,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",41,ааааааааааааааааааааааааааахахаха�я,unknown,None
91,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",42,слава,language,ru
92,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",43,"богу,",language,ru
93,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",44,что,language,ru
94,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",45,ты,language,ru
95,186,segment 186,"но я тоже бы блядь с этим бомжом на скутере бы не общался если бы меня был бы марседес клянусь если бы меня был бы марседес я бы тоже бы не отвечал бы такому хуй сосу рыжий а почему я рыжий ааааааааааааааааааааааааааахахаха�я слава богу, что ты шлем накинул почему я рыжик?",46,шлем,language,ru

,segment,response_id,model,elapsed_seconds,prompt_tokens,completion_tokens,total_tokens
0,segment 18,gen-1787408738-iyRCRKCrXZlFb5oKJjUz,openai/gpt-5.4,2.503039,489,195,684
1,segment 29,gen-1787408740-dEZpyVq8McHt7H81uHT6,openai/gpt-5.4,2.164592,500,195,695
2,segment 96,gen-1787408742-XAtYp8AnCXGVrWNqlF3H,openai/gpt-5.4,1.449536,341,63,404
3,segment 111,gen-1787408744-obWtpQoOwZXhzESqL8rN,openai/gpt-5.4,2.105518,416,123,539
4,segment 137,gen-1787408746-WlWPQK0lw86uc33CS4iB,openai/gpt-5.4,1.643632,378,87,465
5,segment 186,gen-1787408747-olwgtztURR1DEA6sae9x,openai/gpt-5.4,4.323382,1046,631,1677
6,segment 211,gen-1787408752-Svgyteg6lKp08Nyq5R2i,openai/gpt-5.4,1.427389,373,87,460
7,segment 232,gen-1787408753-W0BB3apeEalgdMaLX4wo,openai/gpt-5.4,3.062924,495,171,666
8,segment 238,gen-1787408756-hvuqyQ181ohU7TzQh8yi,openai/gpt-5.4,1.570371,393,99,492
9,segment 289,gen-1787408758-uemgrVMY8MQF12RrEVXs,openai/gpt-5.4,1.947649,333,51,384
10,segment 296,gen-1787408760-nAd17r5vT2JHJtIRs250,openai/gpt-5.4,1.789022,399,111,510
11,segment 307,gen-1787408761-2YyuoBKrolNrvOUDCh38,openai/gpt-5.4,1.372954,359,77,436
12,segment 309,gen-1787408763-6gEgzhNBeO7STgLbbMpH,openai/gpt-5.4,1.958532,399,99,498
13,segment 310,gen-1787408765-K8g2FydTajD6Y9NHHpHd,openai/gpt-5.4,1.550744,348,67,415
14,segment 350,gen-1787408766-lypM0qZnxDt2zR00o3EP,openai/gpt-5.4,1.981962,393,99,492
15,segment 399,gen-1787408768-6H1LosfOZJ3mtg3I3lKF,openai/gpt-5.4,2.056849,410,123,533
16,segment 427,gen-1787408770-eXu02z5cdSTriJQDcLPJ,openai/gpt-5.4,1.930905,431,137,568
17,segment 452,gen-1787408772-Nvhljj5fIR2PKXpZ0XyZ,openai/gpt-5.4,2.020107,426,139,565
18,segment 468,gen-1787408774-q6VNsTiAf6CTue1PMBwt,openai/gpt-5.4,1.654442,419,123,542
19,segment 488,gen-1787408776-LvR4XRWFVexA1XdBntcJ,openai/gpt-5.4,2.168940,491,171,662
20,segment 520,gen-1787408778-SRsz0ms25anZcuRNgCUx,openai/gpt-5.4,1.698218,384,101,485
21,segment 573,gen-1787408780-VoDcmSVqhxL85tfmIHFt,openai/gpt-5.4,1.467783,381,99,480
22,segment 593,gen-1787408781-yxZz6xSAWxwM6Yq3hqd3,openai/gpt-5.4,1.141503,342,51,393
23,segment 600,gen-1787408782-kH0t0eH6MlrEgyDIu7gK,openai/gpt-5.4,1.490050,361,75,436
24,segment 689,gen-1787408784-1EUfIq2EHV0NlfmYpCW8,openai/gpt-5.4,1.989509,386,99,485
25,segment 708,gen-1787408786-Yy9k4Mr59u4Ke3aqBCEF,openai/gpt-5.4,3.286954,723,339,1062

In [12]:
OUTPUT_DIR = Path("/content/language_audit_output")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

result_df.to_parquet(
    OUTPUT_DIR / f"session_{TARGET_SESSION_ID}_language_audit.parquet",
    index=False,
)

screen_df.to_parquet(
    OUTPUT_DIR / f"session_{TARGET_SESSION_ID}_screening.parquet",
    index=False,
)

if not token_df.empty:
    token_df.to_parquet(
        OUTPUT_DIR / f"session_{TARGET_SESSION_ID}_token_audit.parquet",
        index=False,
    )

if not request_df.empty:
    request_df.to_parquet(
        OUTPUT_DIR / f"session_{TARGET_SESSION_ID}_request_log.parquet",
        index=False,
    )

session_summary_df.to_parquet(
    OUTPUT_DIR / f"session_{TARGET_SESSION_ID}_summary.parquet",
    index=False,
)

print(OUTPUT_DIR)

/content/language_audit_output