In [ ]:
from google.colab import drive
from pathlib import Path
import os
import shutil

import duckdb
import pandas as pd
import pyarrow.parquet as pq

# Remount Google Drive cleanly.
try:
    drive.flush_and_unmount()
except Exception:
    pass

if os.path.exists("/content/drive"):
    shutil.rmtree("/content/drive", ignore_errors=True)

drive.mount(
    "/content/drive",
    force_remount=True,
    timeout_ms=300000,
)

MY_DRIVE = Path("/content/drive/MyDrive")
if not MY_DRIVE.exists():
    raise RuntimeError("MyDrive is not available after mounting.")

DATA_DIR = MY_DRIVE / "Language Detection"
if not DATA_DIR.exists():
    raise FileNotFoundError(f"Folder not found: {DATA_DIR}")

PARQUET_PATH = (
    DATA_DIR
    / "sessions_lang_transcript_2026-08-23_2026-08-24.parquet"
)

if not PARQUET_PATH.is_file():
    available_files = [
        path.name
        for path in DATA_DIR.iterdir()
        if path.is_file()
    ]
    raise FileNotFoundError(
        f"Parquet file not found: {PARQUET_PATH}\n"
        f"Available files: {available_files}"
    )

parquet_file = pq.ParquetFile(PARQUET_PATH)
metadata = parquet_file.metadata

print("File path  :", PARQUET_PATH)
print("File size  :", f"{PARQUET_PATH.stat().st_size / (1024**2):.2f} MB")
print("Rows       :", f"{metadata.num_rows:,}")
print("Row groups :", metadata.num_row_groups)
print("Columns    :", metadata.num_columns)

Mounted at /content/drive
File path  : /content/drive/MyDrive/Language Detection/sessions_lang_transcript_2026-08-23_2026-08-24.parquet
File size  : 469.49 MB
Rows       : 3,469
Row groups : 1
Columns    : 12

In [ ]:
SEGMENT_LIMIT = 25
con = duckdb.connect()


def get_language_review(language_code, segment_limit=SEGMENT_LIMIT):
    """Return the first transcript segments from the latest session for a language."""
    review_df = con.execute(
        f"""
        WITH latest_session AS (
            SELECT
                gamesession_id,
                url,
                TRY_CAST(created_at AS TIMESTAMP) AS created_at,
                lang_detected,
                transcript_segments
            FROM read_parquet('{PARQUET_PATH.as_posix()}')
            WHERE
                lang_detected = ?
                AND transcript_segments IS NOT NULL
            ORDER BY
                TRY_CAST(created_at AS TIMESTAMP) DESC,
                gamesession_id DESC
            LIMIT 1
        ),
        exploded AS (
            SELECT
                gamesession_id,
                url,
                lang_detected,
                generate_subscripts(transcript_segments, 1) AS segment_index,
                UNNEST(transcript_segments) AS segment
            FROM latest_session
        ),
        segments AS (
            SELECT
                gamesession_id,
                url,
                segment_index,
                TRY_CAST(segment.timestamp[1] AS DOUBLE) AS start_seconds,
                TRY_CAST(segment.timestamp[2] AS DOUBLE) AS end_seconds,
                TRIM(segment.text) AS segment_text,
                lang_detected AS language_detected
            FROM exploded
            WHERE
                segment.text IS NOT NULL
                AND TRIM(segment.text) <> ''
        )
        SELECT
            gamesession_id,
            url,
            segment_index,
            printf(
                '%02d:%02d:%02d - %02d:%02d:%02d',
                CAST(FLOOR(start_seconds / 3600) AS INTEGER),
                CAST(FLOOR(start_seconds / 60) % 60 AS INTEGER),
                CAST(FLOOR(start_seconds) % 60 AS INTEGER),
                CAST(FLOOR(end_seconds / 3600) AS INTEGER),
                CAST(FLOOR(end_seconds / 60) % 60 AS INTEGER),
                CAST(FLOOR(end_seconds) % 60 AS INTEGER)
            ) AS segment_timestamp,
            segment_text,
            language_detected
        FROM segments
        WHERE
            start_seconds IS NOT NULL
            AND end_seconds IS NOT NULL
        ORDER BY segment_index ASC
        LIMIT ?
        """,
        [language_code, segment_limit],
    ).df()

    # String dtype is intentional: verdicts can contain notes such as
    # "Correct", "No speech", "Missing word: ...", etc.
    review_df["VERDICT"] = pd.Series(
        pd.NA,
        index=review_df.index,
        dtype="string",
    )
    return review_df


def show_review(review_df):
    with pd.option_context(
        "display.max_rows", None,
        "display.max_columns", None,
        "display.max_colwidth", None,
        "display.width", None,
    ):
        display(review_df)

In [ ]:
english_review = get_language_review("en")

english_manual_review = {
    "00:00:02 - 00:00:02": "No speech",
    "00:00:14 - 00:00:15": "Wrong words: Don't be turning around, shut my door.",
    "00:01:07 - 00:01:08": "Correct",
    "00:02:23 - 00:02:25": "Correct",
    "00:02:46 - 00:02:49": "Correct",
    "00:02:50 - 00:02:54": "Missing words: nothing personal.",
    "00:02:55 - 00:02:59": "Missing word: just.",
    "00:02:59 - 00:03:06": "Wrong words: Okay so, just shout.",
    "00:03:20 - 00:03:26": "Correct",
    "00:03:27 - 00:03:28": "Correct",
    "00:03:44 - 00:03:47": "Correct",
    "00:03:48 - 00:03:55": "Wrong words: the devil's; symptom logged.",
    "00:03:55 - 00:03:58": "Correct",
    "00:04:05 - 00:04:08": "Correct",
    "00:04:08 - 00:04:12": "Correct",
    "00:04:12 - 00:04:16": "Correct",
    "00:04:17 - 00:04:20": "Correct",
    "00:04:21 - 00:04:24": "Missing word: and.",
    "00:04:25 - 00:04:29": "Correct",
    "00:04:29 - 00:04:34": "Extra words: I'm; missing word: but.",
    "00:04:35 - 00:04:38": "Extra word: What's.",
    "00:05:31 - 00:05:34": "Missing words: What's the point.",
    "00:05:43 - 00:05:46": "Correct",
    "00:05:47 - 00:05:52": "Correct",
    "00:05:54 - 00:05:59": "Correct",
}

english_review["VERDICT"] = (
    english_review["segment_timestamp"]
    .map(english_manual_review)
    .astype("string")
)

if english_review["VERDICT"].isna().any():
    missing = english_review.loc[
        english_review["VERDICT"].isna(),
        "segment_timestamp",
    ].tolist()
    raise ValueError(f"Missing English manual review: {missing}")

show_review(english_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268501,https://www.twitch.tv/videos/2854311727,1,00:00:02 - 00:00:02,We'll,en,No speech
1,141268501,https://www.twitch.tv/videos/2854311727,2,00:00:14 - 00:00:15,"Don't be talking, shut my door.",en,"Wrong words: Don't be turning around, shut my door."
2,141268501,https://www.twitch.tv/videos/2854311727,3,00:01:07 - 00:01:08,We'll start it.,en,Correct
3,141268501,https://www.twitch.tv/videos/2854311727,4,00:02:23 - 00:02:25,We'll start with the basics.,en,Correct
4,141268501,https://www.twitch.tv/videos/2854311727,5,00:02:46 - 00:02:49,actually showed up. You guys owe me ten bucks.,en,Correct
5,141268501,https://www.twitch.tv/videos/2854311727,6,00:02:50 - 00:02:54,"personal. It's just, uh, we're stuck in Groundhog Day out here.",en,Missing words: nothing personal.
6,141268501,https://www.twitch.tv/videos/2854311727,7,00:02:55 - 00:02:59,"trying to, you know, not go crazy..",en,Missing word: just.
7,141268501,https://www.twitch.tv/videos/2854311727,8,00:02:59 - 00:03:06,"Okay, it's simple really, shout next and the guys will let the survivor in.",en,"Wrong words: Okay so, just shout."
8,141268501,https://www.twitch.tv/videos/2854311727,9,00:03:20 - 00:03:26,"Next survivor. First, do a simple inspection.",en,Correct
9,141268501,https://www.twitch.tv/videos/2854311727,10,00:03:27 - 00:03:28,Take the flashlight from the table.,en,Correct
10,141268501,https://www.twitch.tv/videos/2854311727,11,00:03:44 - 00:03:47,Take your time. Match what you see against the symptom chart.,en,Correct
11,141268501,https://www.twitch.tv/videos/2854311727,12,00:03:48 - 00:03:55,devil's in the details. Identify the particular ailment and click symptom locked.,en,Wrong words: the devil's; symptom logged.
12,141268501,https://www.twitch.tv/videos/2854311727,13,00:03:55 - 00:03:58,"If you mark most symptoms correctly, you'll get a reward.",en,Correct
13,141268501,https://www.twitch.tv/videos/2854311727,14,00:04:05 - 00:04:08,"Once you've recorded the symptoms, time to decide their fate.",en,Correct
14,141268501,https://www.twitch.tv/videos/2854311727,15,00:04:08 - 00:04:12,Let's switch to the distribution tab. You are in a quarantine zone.,en,Correct
15,141268501,https://www.twitch.tv/videos/2854311727,16,00:04:12 - 00:04:16,Stay calm and wait for your turn. Remove your outer clothing.,en,Correct
16,141268501,https://www.twitch.tv/videos/2854311727,17,00:04:17 - 00:04:20,Still not sure. No worries. Just send them into quarantine.,en,Correct
17,141268501,https://www.twitch.tv/videos/2854311727,18,00:04:21 - 00:04:24,"Let them sit for a few days, the virus will reveal itself.",en,Missing word: and.
18,141268501,https://www.twitch.tv/videos/2854311727,19,00:04:25 - 00:04:29,Like a friend of mine used to say. Can't piss in the gas tank.,en,Correct
19,141268501,https://www.twitch.tv/videos/2854311727,20,00:04:29 - 00:04:34,"I'm not sure what he meant exactly, your choice may have consequences for the whole camp.",en,Extra words: I'm; missing word: but.
20,141268501,https://www.twitch.tv/videos/2854311727,21,00:04:35 - 00:04:38,If you let the wrong one in. What's,en,Extra word: What's.
21,141268501,https://www.twitch.tv/videos/2854311727,22,00:05:31 - 00:05:34,the point of all this? We're all dead already.,en,Missing words: What's the point.
22,141268501,https://www.twitch.tv/videos/2854311727,23,00:05:43 - 00:05:46,In four days we will be evacuating the survivor's block.,en,Correct
23,141268501,https://www.twitch.tv/videos/2854311727,24,00:05:47 - 00:05:52,The top brass will be very upset with us if we don't move a adequate number of healthy people.,en,Correct
24,141268501,https://www.twitch.tv/videos/2854311727,25,00:05:54 - 00:05:59,Carefully examine the survivors in the line and send the unaffected on to the block.,en,Correct

In [11]:
import duckdb
import pandas as pd

LANGUAGE = "en"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

english_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM eligible
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


english_segments["segment_timestamp"] = (
    english_segments["segment_start"].map(format_timestamp)
    + " - "
    + english_segments["segment_end"].map(format_timestamp)
)

english_segments["VERDICT"] = ""

english_segments = english_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(english_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268501,https://www.twitch.tv/videos/2854311727,2,00:00:14 - 00:00:15,"Don't be talking, shut my door.",en,
1,141268501,https://www.twitch.tv/videos/2854311727,4,00:02:23 - 00:02:25,We'll start with the basics.,en,
2,141268501,https://www.twitch.tv/videos/2854311727,5,00:02:46 - 00:02:49,actually showed up. You guys owe me ten bucks.,en,
3,141268501,https://www.twitch.tv/videos/2854311727,6,00:02:50 - 00:02:54,"personal. It's just, uh, we're stuck in Groundhog Day out here.",en,
4,141268501,https://www.twitch.tv/videos/2854311727,7,00:02:55 - 00:02:59,"trying to, you know, not go crazy..",en,
5,141268501,https://www.twitch.tv/videos/2854311727,8,00:02:59 - 00:03:06,"Okay, it's simple really, shout next and the guys will let the survivor in.",en,
6,141268501,https://www.twitch.tv/videos/2854311727,9,00:03:20 - 00:03:26,"Next survivor. First, do a simple inspection.",en,
7,141268501,https://www.twitch.tv/videos/2854311727,10,00:03:27 - 00:03:28,Take the flashlight from the table.,en,
8,141268501,https://www.twitch.tv/videos/2854311727,11,00:03:44 - 00:03:47,Take your time. Match what you see against the symptom chart.,en,
9,141268501,https://www.twitch.tv/videos/2854311727,12,00:03:48 - 00:03:55,devil's in the details. Identify the particular ailment and click symptom locked.,en,
10,141268501,https://www.twitch.tv/videos/2854311727,13,00:03:55 - 00:03:58,"If you mark most symptoms correctly, you'll get a reward.",en,
11,141268501,https://www.twitch.tv/videos/2854311727,14,00:04:05 - 00:04:08,"Once you've recorded the symptoms, time to decide their fate.",en,
12,141268501,https://www.twitch.tv/videos/2854311727,15,00:04:08 - 00:04:12,Let's switch to the distribution tab. You are in a quarantine zone.,en,
13,141268501,https://www.twitch.tv/videos/2854311727,16,00:04:12 - 00:04:16,Stay calm and wait for your turn. Remove your outer clothing.,en,
14,141268501,https://www.twitch.tv/videos/2854311727,17,00:04:17 - 00:04:20,Still not sure. No worries. Just send them into quarantine.,en,
15,141268501,https://www.twitch.tv/videos/2854311727,18,00:04:21 - 00:04:24,"Let them sit for a few days, the virus will reveal itself.",en,
16,141268501,https://www.twitch.tv/videos/2854311727,19,00:04:25 - 00:04:29,Like a friend of mine used to say. Can't piss in the gas tank.,en,
17,141268501,https://www.twitch.tv/videos/2854311727,20,00:04:29 - 00:04:34,"I'm not sure what he meant exactly, your choice may have consequences for the whole camp.",en,
18,141268501,https://www.twitch.tv/videos/2854311727,21,00:04:35 - 00:04:38,If you let the wrong one in. What's,en,
19,141268501,https://www.twitch.tv/videos/2854311727,22,00:05:31 - 00:05:34,the point of all this? We're all dead already.,en,
20,141268501,https://www.twitch.tv/videos/2854311727,23,00:05:43 - 00:05:46,In four days we will be evacuating the survivor's block.,en,
21,141268501,https://www.twitch.tv/videos/2854311727,24,00:05:47 - 00:05:52,The top brass will be very upset with us if we don't move a adequate number of healthy people.,en,
22,141268501,https://www.twitch.tv/videos/2854311727,25,00:05:54 - 00:05:59,Carefully examine the survivors in the line and send the unaffected on to the block.,en,
23,141268501,https://www.twitch.tv/videos/2854311727,26,00:06:21 - 00:06:27,What's the point? Don't make me wait.,en,
24,141268501,https://www.twitch.tv/videos/2854311727,27,00:06:30 - 00:06:33,"Please, we hurry? I think we were followed.",en,

In [ ]:
german_review = get_language_review("de")

# Fill verdicts after manual listening. Examples:
# german_review.loc[0, "VERDICT"] = "Correct"
# german_review.loc[1, "VERDICT"] = "Missing word: ..."
# german_review.loc[2, "VERDICT"] = "Wrong words: ..."
# german_review.loc[3, "VERDICT"] = "Extra word: ..."
# german_review.loc[4, "VERDICT"] = "No speech"

show_review(german_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141192575,https://www.twitch.tv/videos/2852368077,1,00:00:07 - 00:00:10,"Der kann mich gar nicht erwischt, nie im Leben.",de,<NA>
1,141192575,https://www.twitch.tv/videos/2852368077,2,00:00:14 - 00:00:15,ich hab's gerade gesehen.,de,<NA>
2,141192575,https://www.twitch.tv/videos/2852368077,3,00:00:25 - 00:00:27,"Eigentlich hat das Gebäude, als wir offiziell in der Zwiebel waren.",de,<NA>
3,141192575,https://www.twitch.tv/videos/2852368077,4,00:00:46 - 00:00:53,"Ich seh' halt nicht, keine Ahnung, wo der ist.",de,<NA>
4,141192575,https://www.twitch.tv/videos/2852368077,5,00:00:59 - 00:01:04,"Irgendwo Richtung Turm drin, irgendwo da hinten, so ein bisschen weiter links.",de,<NA>
5,141192575,https://www.twitch.tv/videos/2852368077,6,00:01:08 - 00:01:16,"einen haben wir am Tachel, einer ist noch unten drin ja ja da snipet er die Lachen",de,<NA>
6,141192575,https://www.twitch.tv/videos/2852368077,7,00:01:19 - 00:01:28,"traurige ja gib mir ein Bredi ja ein richtiger Lack jetzt habe ich gepisst das, ich hätte dich geholt",de,<NA>
7,141192575,https://www.twitch.tv/videos/2852368077,8,00:01:30 - 00:01:41,"ich weiß nicht, hier haben die die selber gibt's das das war das, was du deinen eigenen Strömen liebst warte mal ich schau mal Das ist jetzt Beste.",de,<NA>
8,141192575,https://www.twitch.tv/videos/2852368077,9,00:01:42 - 00:01:43,Hinter uns.,de,<NA>
9,141192575,https://www.twitch.tv/videos/2852368077,10,00:02:06 - 00:02:13,"Die hat ja noch einer, jetzt können sie Tank und Psych nochmal.",de,<NA>
10,141192575,https://www.twitch.tv/videos/2852368077,11,00:02:14 - 00:02:18,"Oh nein, ja er snipet immer noch wo da oben.",de,<NA>
11,141192575,https://www.twitch.tv/videos/2852368077,12,00:02:21 - 00:02:27,"Kommt der Bresi auf mich? Was bist du nur für ein Hundesohn, echt?",de,<NA>
12,141192575,https://www.twitch.tv/videos/2852368077,13,00:02:38 - 00:02:44,"Der schaut bei dir aus, bitte. Ich bin hier.",de,<NA>
13,141192575,https://www.twitch.tv/videos/2852368077,14,00:02:44 - 00:02:47,"Hier, vor überall. Im Turm und so.",de,<NA>
14,141192575,https://www.twitch.tv/videos/2852368077,15,00:02:48 - 00:02:51,"Ah und eines ist aus der Kirche oben, da war es auch safe. Kein Kind, der den Dinger hat.",de,<NA>
15,141192575,https://www.twitch.tv/videos/2852368077,16,00:02:53 - 00:02:55,"Müssen wir schauen, dass wir es gleich hier so nachher kriegen.",de,<NA>
16,141192575,https://www.twitch.tv/videos/2852368077,17,00:03:12 - 00:03:20,"Na! Ja, aber die warten nicht gut. Aber was soll ich machen? Ich halte einen von oben und würde ihn vom Schub fallen.",de,<NA>
17,141192575,https://www.twitch.tv/videos/2852368077,18,00:03:20 - 00:03:21,werde ihn nicht oft ausschüssen.,de,<NA>
18,141192575,https://www.twitch.tv/videos/2852368077,19,00:03:42 - 00:03:47,Jetzt ist es dir frei.,de,<NA>
19,141192575,https://www.twitch.tv/videos/2852368077,20,00:03:49 - 00:03:53,Ich nix zu tun. So ein Pisser echt. Der da da oben umeinander.,de,<NA>
20,141192575,https://www.twitch.tv/videos/2852368077,21,00:04:05 - 00:04:10,Es dürfte also irgendwie zu irgendwas kommen. Wenn wir kurz beieinander sind.,de,<NA>
21,141192575,https://www.twitch.tv/videos/2852368077,22,00:04:12 - 00:04:18,"Einer hat nix mehr, der sitzt bei, das hat's unten, das hat's oben scheiße versucht, dass ich aufbekommen.",de,<NA>
22,141192575,https://www.twitch.tv/videos/2852368077,23,00:04:18 - 00:04:24,"das ja das, ja, hab jetzt versucht zum Ovi-Snipern, aber ich hab den scheiß Sniper unten.",de,<NA>
23,141192575,https://www.twitch.tv/videos/2852368077,24,00:04:25 - 00:04:29,"Ja, das war klar, das ist nicht mehr scharf jetzt, ich hab, mein, das hat's unten drin.",de,<NA>
24,141192575,https://www.twitch.tv/videos/2852368077,25,00:04:30 - 00:04:33,"Deswegen hab ich da schon zwei geholt, aber ja, hab ich nicht mitgekriegt.",de,<NA>

In [ ]:
russian_review = get_language_review("ru")

# Fill verdicts after manual listening. Examples:
# russian_review.loc[0, "VERDICT"] = "Correct"
# russian_review.loc[1, "VERDICT"] = "Missing word: ..."
# russian_review.loc[2, "VERDICT"] = "Wrong words: ..."
# russian_review.loc[3, "VERDICT"] = "Extra word: ..."
# russian_review.loc[4, "VERDICT"] = "No speech"

show_review(russian_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,1,00:00:09 - 00:00:39,ДИНАМИЧНАЯ,ru,<NA>
1,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,2,00:01:00 - 00:01:30,"ДИНАМИЧНАЯ Ooh-ooh, kiss my shit, kiss my",ru,<NA>
2,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,3,00:01:30 - 00:01:44,"shit I heard you were talking shit And you didn't think that I would hear it People hear you talking, like",ru,<NA>
3,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,4,00:03:18 - 00:03:20,в,ru,<NA>
4,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,5,00:03:20 - 00:03:50,ДИНАМИЧНАЯ,ru,<NA>
5,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,6,00:03:50 - 00:03:54,"Так я не понимаю, нахуй он сначала девочек за бодашкой врубил?",ru,<NA>
6,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,7,00:03:57 - 00:04:04,"Чад, всем дарова, всем... Ты что, реально врубил, придурок? Блять, ты ебла нахуй, нахуй ты меня трахаешь, ебанашка Ростян, он реально врубил, Ростян?",ru,<NA>
7,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,8,00:04:04 - 00:04:26,"Да, я врубил Да Короче, дарова, Чад, привет, всем Ну вот, так вам скажу, нас сегодня распаковка анимешных фигурок, анимешных фигурок из магазина popo-man или popo-ma popo-me-me-me вот",ru,<NA>
8,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,9,00:04:28 - 00:04:56,"а, оффот? пишут, пишут, оффот, не надо стримить всё, тогда оффо, нахуй, чад, спасибо, всем пока короче, взяли конструктивного компотика, ну, такого рационального правильного, вкусного собрались в небольшой компании рациональных людей это окей Юра окей вот Юра вот Леша вот",ru,<NA>
9,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,10,00:04:57 - 00:05:26,Рациональный Леша нас сегодня Леша нас сегодня диджей Леша диджей и Растян с танком Растян с танком я тебя могу вот что будет так что то попьем пивка распакуем игрушки и ляжем спать вот все не знаю кто спать сегодня денечек такой не сбылся,ru,<NA>
10,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,11,00:05:26 - 00:05:36,спирит проебали блять моя ставка проебала блять сколько 30 6 тысяч 136 тысяч,ru,<NA>
11,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,12,00:05:39 - 00:05:44,"Да, Санька, Санька, займись, Саша, займись.",ru,<NA>
12,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,13,00:05:44 - 00:05:48,"Вот, потихоньку кое-что, пивасик сейчас поглушим и распакуем.",ru,<NA>
13,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,14,00:05:49 - 00:05:54,"Ну, пожалуй, я думаю сейчас надо самое главное это обсудить...",ru,<NA>
14,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,15,00:05:54 - 00:05:59,"Бля, давайте может столик поставим, чтобы можно... Обсудить, что ты сказал в моем тиктоке за предку?",ru,<NA>
15,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,16,00:06:00 - 00:06:05,"Мы можем сейчас обсудить игру, прошлую игру.",ru,<NA>
16,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,17,00:06:05 - 00:06:13,"А чемодан на хуя? Эту камеру слабо стоять не надо ходить, Ээээ из-за кадра поставь Вот, там будем сидеть Нет?",ru,<NA>
17,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,18,00:06:13 - 00:06:19,"Или пусть не так-то старей стоит? Не, ну всё это туда ладно, подологично Как это называется?",ru,<NA>
18,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,19,00:06:20 - 00:06:28,"Соджу Соджу Нормально или в руках будем держать? Не, туда Вместо одного держать в руках Чё, короче, вот тут посидите",ru,<NA>
19,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,20,00:06:31 - 00:06:44,"Блядь, Лёшка нахуй Ну ты вообще блядь диджей ебучий, блядь, Лёш Ну ты вообще Какой засрали нет не бать все тебе респект кидают тут тебе все все все респект кидают",ru,<NA>
20,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,21,00:06:47 - 00:07:03,"Тут тебе все все тут тебе все кидают респекта блядь жесткий Все я поставил я поставил камеру так чтобы танка тоже было видно Смотрите нормальную музыку Ха-ха-ха Напишите как видно меня, нормально?",ru,<NA>
21,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,22,00:07:03 - 00:07:20,"Вот руку поднимаю Видно нормально там? Давайте пока въебём Вот как въебём А, выпить Господи, ебаные завозы Дура, вообще как въебутая Давай, давай сейчас въебём",ru,<NA>
22,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,23,00:07:22 - 00:07:27,"Постопаливай Не, не, не Стой!",ru,<NA>
23,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,24,00:07:27 - 00:07:28,"Около зло, пацана!",ru,<NA>
24,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,25,00:07:37 - 00:07:42,Тут даже я разъят! Чем глоток выпил?,ru,<NA>

In [ ]:
french_review = get_language_review("fr")

# Fill verdicts after manual listening. Examples:
# french_review.loc[0, "VERDICT"] = "Correct"
# french_review.loc[1, "VERDICT"] = "Missing word: ..."
# french_review.loc[2, "VERDICT"] = "Wrong words: ..."
# french_review.loc[3, "VERDICT"] = "Extra word: ..."
# french_review.loc[4, "VERDICT"] = "No speech"

show_review(french_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141267561,https://www.twitch.tv/videos/2854116559,1,00:00:29 - 00:00:29,serai là-bas,fr,<NA>
1,141267561,https://www.twitch.tv/videos/2854116559,2,00:00:52 - 00:00:55,What you guys doing ?,fr,<NA>
2,141267561,https://www.twitch.tv/videos/2854116559,3,00:01:24 - 00:01:25,Mais quoi,fr,<NA>
3,141267561,https://www.twitch.tv/videos/2854116559,4,00:01:42 - 00:01:43,? Je serai,fr,<NA>
4,141267561,https://www.twitch.tv/videos/2854116559,5,00:02:15 - 00:02:16,là-bas,fr,<NA>
5,141267561,https://www.twitch.tv/videos/2854116559,6,00:02:38 - 00:02:41,What you guys doing ?,fr,<NA>
6,141267561,https://www.twitch.tv/videos/2854116559,7,00:03:06 - 00:03:14,"Allez mec Attendez Yo Damien, t le premier ?",fr,<NA>
7,141267561,https://www.twitch.tv/videos/2854116559,8,00:03:14 - 00:03:24,"Ouais sur tiktak t le premier, même sur Twitch je pense En tout cas le premier message Euh, y'en perd pas de temps Aujourd'hui on essaie d'avancer putain de capa de merde Comme ça c'est fait, il nous manquera quoi ?",fr,<NA>
8,141267561,https://www.twitch.tv/videos/2854116559,9,00:03:24 - 00:03:34,"Là, il'on y s'extraire avec l'autre un, ça nous donnera la peluche, et après il manquera juste l'achantique, et problème de l'achantique, c que je sais pas comment je vais le pour la trouver, mais on va tenter, on va tenter.",fr,<NA>
9,141267561,https://www.twitch.tv/videos/2854116559,10,00:03:34 - 00:03:38,"Yo Pilouf,'as va ou quoi ? Comment va le Pilouf ?",fr,<NA>
10,141267561,https://www.twitch.tv/videos/2854116559,11,00:03:39 - 00:03:44,"Allez, ça part comme ça les gars. Un second. Ça raconte quoi Pilouf ?",fr,<NA>
11,141267561,https://www.twitch.tv/videos/2854116559,12,00:03:44 - 00:03:48,"J'espère que tu vas bien Damien. Ah d'ailleurs, je voulais te faire un truc.",fr,<NA>
12,141267561,https://www.twitch.tv/videos/2854116559,13,00:04:25 - 00:04:35,"Ah bah tranquille mon Pilouf. J'peux pas t'entendre, j'suis au taf, moi un pouce avec un grand sourire pour me dire bonjour La petit pouce Putain, travailler un dimanche, terrible",fr,<NA>
13,141267561,https://www.twitch.tv/videos/2854116559,14,00:04:50 - 00:04:54,"Mais putain, Pilouf alors Pilouf tu reprends lundi, enfin demain les cours",fr,<NA>
14,141267561,https://www.twitch.tv/videos/2854116559,15,00:05:08 - 00:05:15,"Non la semaine pro, putain ok, j'pensais que vous repreniez, mais comment ça se fait La France ils reprennent pas demain ?",fr,<NA>
15,141267561,https://www.twitch.tv/videos/2854116559,16,00:05:15 - 00:05:19,"Du hommade, ça va ou combat ? Ça ou cobbg ?",fr,<NA>
16,141267561,https://www.twitch.tv/videos/2854116559,17,00:05:19 - 00:05:28,Attendez vais juste checker un truc Mais je pensais que vous les français vous repreniez déjà demain,fr,<NA>
17,141267561,https://www.twitch.tv/videos/2854116559,18,00:05:30 - 00:05:32,Je vais voir si ça ça marche,fr,<NA>
18,141267561,https://www.twitch.tv/videos/2854116559,19,00:05:45 - 00:05:56,Ah nique sa mère je vais juste checker un truc mette à pied Allez go Merci pour le follow mon petit mat Ah c'est mon frère 1 septembre en Putain Putain mais là on déglandeur jusqu'à...,fr,<NA>
19,141267561,https://www.twitch.tv/videos/2854116559,20,00:05:56 - 00:06:15,Oh mais les la game va être très chiante hein parce que c ici mon extract C'est ici mon extract les gars putain Je dois attendre 20 minutes avant que le train arrive Je tuer les rogues je vais aller me faire les rogues et je vais goûter un peu la zone.,fr,<NA>
20,141267561,https://www.twitch.tv/videos/2854116559,21,00:06:17 - 00:06:26,"êtes vraiment dégueulasses, pile ouf vous les français, et c'est pour toute la France le 1er septembre ou vous vous avez par zone A baissé là,'autrui de con là.",fr,<NA>
21,141267561,https://www.twitch.tv/videos/2854116559,22,00:06:27 - 00:06:33,"Je jamais comment ça marche, j'attends que le train arrive les gars, ouais toute la France ok.",fr,<NA>
22,141267561,https://www.twitch.tv/videos/2854116559,23,00:06:36 - 00:06:41,"C'est terrible là, parce que je peux me faire fumer à tout moment. Attendez.",fr,<NA>
23,141267561,https://www.twitch.tv/videos/2854116559,24,00:06:49 - 00:06:52,"Waouh, tu vois ? Terrible.",fr,<NA>
24,141267561,https://www.twitch.tv/videos/2854116559,25,00:06:58 - 00:06:59,Écoute mon malade.,fr,<NA>

In [ ]:
spanish_review = get_language_review("es")

# Fill verdicts after manual listening. Examples:
# spanish_review.loc[0, "VERDICT"] = "Correct"
# spanish_review.loc[1, "VERDICT"] = "Missing word: ..."
# spanish_review.loc[2, "VERDICT"] = "Wrong words: ..."
# spanish_review.loc[3, "VERDICT"] = "Extra word: ..."
# spanish_review.loc[4, "VERDICT"] = "No speech"

show_review(spanish_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268448,https://www.twitch.tv/videos/2853628924,1,00:03:03 - 00:03:14,hola hola que tal gente silla estamos aquí otra vez un día más vamos al charlando,es,<NA>
1,141268448,https://www.twitch.tv/videos/2853628924,2,00:03:17 - 00:03:47,hello como estáis como estáis ahora estoy bastante cansada pero tengo una cosa aquí estamos aquí cumplimos vale pues hoy vamos a jugar a los dinosaurios que me apetece un ratito aunque sea y ya luego vamos al balo en un ratito hoy no me quedaré mucho porque me apetece estar más en la gama todo esto me hecho una siesta cuando he llegado,es,<NA>
2,141268448,https://www.twitch.tv/videos/2853628924,3,00:03:47 - 00:03:59,de tres horas y claro una mañana que hay que trabajar entonces prefiero irme tempranito que sabemos como acaba de irse tempranito pero bueno lo cuento igual.,es,<NA>
3,141268448,https://www.twitch.tv/videos/2853628924,4,00:04:02 - 00:04:05,eh... Vale. ¿Dónde está? ¿Dónde está?,es,<NA>
4,141268448,https://www.twitch.tv/videos/2853628924,5,00:04:05 - 00:04:06,"Aquí,",es,<NA>
5,141268448,https://www.twitch.tv/videos/2853628924,6,00:04:11 - 00:04:13,"Let's go. Vamos allá, continúen.",es,<NA>
6,141268448,https://www.twitch.tv/videos/2853628924,7,00:04:18 - 00:04:21,"Vale, voy limpiar un momentito rápido el teclado.",es,<NA>
7,141268448,https://www.twitch.tv/videos/2853628924,8,00:04:30 - 00:04:33,Vale. Vale.,es,<NA>
8,141268448,https://www.twitch.tv/videos/2853628924,9,00:04:38 - 00:04:49,"Pero no lo que tenía que hacer, tipo, las dos canastas y los ladrillos de piedra vale,",es,<NA>
9,141268448,https://www.twitch.tv/videos/2853628924,10,00:04:52 - 00:05:03,"ehm, los de piedra y las dos canastas, tengo que hacer nooo, una planta por la puta,",es,<NA>
10,141268448,https://www.twitch.tv/videos/2853628924,11,00:05:08 - 00:05:17,"falta una planta ah ya tengo las dos vale, ok, eh vamos a reunirnos con Bryce",es,<NA>
11,141268448,https://www.twitch.tv/videos/2853628924,12,00:05:35 - 00:05:44,"¿Por qué hay emisiones? ¿Qué más tenían? Aumentar la población, pero eso lo vas diciendo poco a",es,<NA>
12,141268448,https://www.twitch.tv/videos/2853628924,13,00:05:48 - 00:05:54,Vamos... ¡Eh! ¡Estamos en invierno! ¿Por qué por el primavera ya está nevando?,es,<NA>
13,141268448,https://www.twitch.tv/videos/2853628924,14,00:06:04 - 00:06:10,"Enchiendo. ¿Vamos dónde, Bryce?",es,<NA>
14,141268448,https://www.twitch.tv/videos/2853628924,15,00:06:11 - 00:06:12,"Vale, esto de que...",es,<NA>
15,141268448,https://www.twitch.tv/videos/2853628924,16,00:06:18 - 00:06:24,Pero ¿por qué está nevando? una pregunta muy sería,es,<NA>
16,141268448,https://www.twitch.tv/videos/2853628924,17,00:06:30 - 00:06:34,vale vamos para arriba,es,<NA>
17,141268448,https://www.twitch.tv/videos/2853628924,18,00:06:40 - 00:06:56,a la monta de las sierras altas ahora pensé que podía haberte peado ok vale pero me escucho una cosa madre mía,es,<NA>
18,141268448,https://www.twitch.tv/videos/2853628924,19,00:06:59 - 00:07:08,esto que seguir subiendo que locura este buenos días che,es,<NA>
19,141268448,https://www.twitch.tv/videos/2853628924,20,00:07:10 - 00:07:13,creo que no nos habíamos hasta ahora. Soy Mina.,es,<NA>
20,141268448,https://www.twitch.tv/videos/2853628924,21,00:07:14 - 00:07:22,"Mina Fotazas. Este juego me vacila, pero grandes rasgos.",es,<NA>
21,141268448,https://www.twitch.tv/videos/2853628924,22,00:07:23 - 00:07:28,La verdad. El objetivo más rápido de todo el archipiélago.,es,<NA>
22,141268448,https://www.twitch.tv/videos/2853628924,23,00:07:29 - 00:07:33,"Tengo que ser de hablar de mí, pero eso es porque se me da requetiría en mi trabajo. Soy súper sigilosa.",es,<NA>
23,141268448,https://www.twitch.tv/videos/2853628924,24,00:07:33 - 00:07:41,"Me expedizo en fotos analógicas de piezos, espontáneos desmedidos, fated, así decirlo.",es,<NA>
24,141268448,https://www.twitch.tv/videos/2853628924,25,00:07:41 - 00:07:46,"Potentes auténticas para los profanos, la vida real, vaya. Y ahora, si me disculpas, tengo que esperar a ciertos sitios.",es,<NA>

In [ ]:
portuguese_review = get_language_review("pt")

# Fill verdicts after manual listening. Examples:
# portuguese_review.loc[0, "VERDICT"] = "Correct"
# portuguese_review.loc[1, "VERDICT"] = "Missing word: ..."
# portuguese_review.loc[2, "VERDICT"] = "Wrong words: ..."
# portuguese_review.loc[3, "VERDICT"] = "Extra word: ..."
# portuguese_review.loc[4, "VERDICT"] = "No speech"

show_review(portuguese_review)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268410,https://www.twitch.tv/videos/2854267348,1,00:09:52 - 00:09:59,FUERTA DE RAHIM Ta,pt,<NA>
1,141268410,https://www.twitch.tv/videos/2854267348,2,00:10:54 - 00:11:10,de pé E Fui FUERTA RAHIM E ASSISTA FUERTA FAZ FUERTA RAHIM FUERTA RAHIM,pt,<NA>
2,141268410,https://www.twitch.tv/videos/2854267348,3,00:11:13 - 00:11:19,FUERTA RAHIM porta aberta e isso,pt,<NA>
3,141268410,https://www.twitch.tv/videos/2854267348,4,00:11:23 - 00:11:47,ok então estou bebendo um café hoje seria o dia do chill stream mas essa semana eu não joguei a LoL eu queria jogar a LoL eu queria jogar a LoL o chill stream significa que eu decido então se eu quero jogar LoL eu a LoL e vocês pegam no cu aquele eu mais alto talvez,pt,<NA>
4,141268410,https://www.twitch.tv/videos/2854267348,5,00:11:54 - 00:11:57,Como você Como você Galaxi?,pt,<NA>
5,141268410,https://www.twitch.tv/videos/2854267348,6,00:11:58 - 00:12:02,"Você fazendo tudo, você está certo. Como você Pasta?",pt,<NA>
6,141268410,https://www.twitch.tv/videos/2854267348,7,00:12:02 - 00:12:09,"Como você está? Shadow? Tudo bem, garotos? Razy, como você Tchau garotos, tchau a você bem?",pt,<NA>
7,141268410,https://www.twitch.tv/videos/2854267348,8,00:12:14 - 00:12:18,"O Urco desde esta manhã, oh Deus, desta manhã...",pt,<NA>
8,141268410,https://www.twitch.tv/videos/2854267348,9,00:12:18 - 00:12:21,"Eu não estava. E saiu também no meu schedule, não sei se você viu.",pt,<NA>
9,141268410,https://www.twitch.tv/videos/2854267348,10,00:12:22 - 00:12:28,"Que é feito, não mais a Dorari. Mas é a...",pt,<NA>
10,141268410,https://www.twitch.tv/videos/2854267348,11,00:12:28 - 00:12:29,período.,pt,<NA>
11,141268410,https://www.twitch.tv/videos/2854267348,12,00:12:36 - 00:12:44,"Não sei se vocês viram. Período, horário da noite, Não sei se vocês viram.",pt,<NA>
12,141268410,https://www.twitch.tv/videos/2854267348,13,00:12:45 - 00:12:50,"O vocês pensam? Pensam que é muito mais descomodado, ou pode ficar?",pt,<NA>
13,141268410,https://www.twitch.tv/videos/2854267348,14,00:12:51 - 00:12:55,"Em sua opinião. Para mim é melhor, porque menos...",pt,<NA>
14,141268410,https://www.twitch.tv/videos/2854267348,15,00:12:55 - 00:13:01,"Por como eu eu, me ajuda mais com a minha desabilidade, porque eu um pouco desabelhado.",pt,<NA>
15,141268410,https://www.twitch.tv/videos/2854267348,16,00:13:05 - 00:13:08,"Não, ainda tem a resposta! Caramba!",pt,<NA>
16,141268410,https://www.twitch.tv/videos/2854267348,17,00:13:09 - 00:13:13,"Era, porque na passada era a resposta. Eu me esqueci de modificar ela.",pt,<NA>
17,141268410,https://www.twitch.tv/videos/2854267348,18,00:13:13 - 00:13:20,Ah resposta de novo. Porra de Eu me de a resposta por sempre.,pt,<NA>
18,141268410,https://www.twitch.tv/videos/2854267348,19,00:13:20 - 00:13:25,"Mas por sempre, eu já Porque depois eu me identificarei na semana próxima e deixarei aqui.",pt,<NA>
19,141268410,https://www.twitch.tv/videos/2854267348,20,00:13:27 - 00:13:37,"Ai meu Residência Residência, residência Ai meu Deus",pt,<NA>
20,141268410,https://www.twitch.tv/videos/2854267348,21,00:13:40 - 00:13:46,"Apreciamos o que você sabe, eu sei Eu sei, eu sei Eu um pouco estranho",pt,<NA>
21,141268410,https://www.twitch.tv/videos/2854267348,22,00:13:55 - 00:13:58,"Mas com o domingo sério, entende a durada? uma das duas?",pt,<NA>
22,141268410,https://www.twitch.tv/videos/2854267348,23,00:13:58 - 00:14:03,"Não, a durada Porque tipo...",pt,<NA>
23,141268410,https://www.twitch.tv/videos/2854267348,24,00:14:03 - 00:14:13,"Era domingo tarde Mas eu sei como escrever O início da manhã, o início da manhã era a 19h, que eu sei, manhã, na Poderia escrever a manhã,",pt,<NA>
24,141268410,https://www.twitch.tv/videos/2854267348,25,00:14:16 - 00:14:19,Mas sim. sim. Dois stream de fila.,pt,<NA>

In [ ]:
all_reviews = pd.concat(
    [
        english_review,
        german_review,
        russian_review,
        french_review,
        spanish_review,
        portuguese_review,
    ],
    ignore_index=True,
)

show_review(all_reviews)

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268501,https://www.twitch.tv/videos/2854311727,1,00:00:02 - 00:00:02,We'll,en,No speech
1,141268501,https://www.twitch.tv/videos/2854311727,2,00:00:14 - 00:00:15,"Don't be talking, shut my door.",en,"Wrong words: Don't be turning around, shut my door."
2,141268501,https://www.twitch.tv/videos/2854311727,3,00:01:07 - 00:01:08,We'll start it.,en,Correct
3,141268501,https://www.twitch.tv/videos/2854311727,4,00:02:23 - 00:02:25,We'll start with the basics.,en,Correct
4,141268501,https://www.twitch.tv/videos/2854311727,5,00:02:46 - 00:02:49,actually showed up. You guys owe me ten bucks.,en,Correct
5,141268501,https://www.twitch.tv/videos/2854311727,6,00:02:50 - 00:02:54,"personal. It's just, uh, we're stuck in Groundhog Day out here.",en,Missing words: nothing personal.
6,141268501,https://www.twitch.tv/videos/2854311727,7,00:02:55 - 00:02:59,"trying to, you know, not go crazy..",en,Missing word: just.
7,141268501,https://www.twitch.tv/videos/2854311727,8,00:02:59 - 00:03:06,"Okay, it's simple really, shout next and the guys will let the survivor in.",en,"Wrong words: Okay so, just shout."
8,141268501,https://www.twitch.tv/videos/2854311727,9,00:03:20 - 00:03:26,"Next survivor. First, do a simple inspection.",en,Correct
9,141268501,https://www.twitch.tv/videos/2854311727,10,00:03:27 - 00:03:28,Take the flashlight from the table.,en,Correct
10,141268501,https://www.twitch.tv/videos/2854311727,11,00:03:44 - 00:03:47,Take your time. Match what you see against the symptom chart.,en,Correct
11,141268501,https://www.twitch.tv/videos/2854311727,12,00:03:48 - 00:03:55,devil's in the details. Identify the particular ailment and click symptom locked.,en,Wrong words: the devil's; symptom logged.
12,141268501,https://www.twitch.tv/videos/2854311727,13,00:03:55 - 00:03:58,"If you mark most symptoms correctly, you'll get a reward.",en,Correct
13,141268501,https://www.twitch.tv/videos/2854311727,14,00:04:05 - 00:04:08,"Once you've recorded the symptoms, time to decide their fate.",en,Correct
14,141268501,https://www.twitch.tv/videos/2854311727,15,00:04:08 - 00:04:12,Let's switch to the distribution tab. You are in a quarantine zone.,en,Correct
15,141268501,https://www.twitch.tv/videos/2854311727,16,00:04:12 - 00:04:16,Stay calm and wait for your turn. Remove your outer clothing.,en,Correct
16,141268501,https://www.twitch.tv/videos/2854311727,17,00:04:17 - 00:04:20,Still not sure. No worries. Just send them into quarantine.,en,Correct
17,141268501,https://www.twitch.tv/videos/2854311727,18,00:04:21 - 00:04:24,"Let them sit for a few days, the virus will reveal itself.",en,Missing word: and.
18,141268501,https://www.twitch.tv/videos/2854311727,19,00:04:25 - 00:04:29,Like a friend of mine used to say. Can't piss in the gas tank.,en,Correct
19,141268501,https://www.twitch.tv/videos/2854311727,20,00:04:29 - 00:04:34,"I'm not sure what he meant exactly, your choice may have consequences for the whole camp.",en,Extra words: I'm; missing word: but.
20,141268501,https://www.twitch.tv/videos/2854311727,21,00:04:35 - 00:04:38,If you let the wrong one in. What's,en,Extra word: What's.
21,141268501,https://www.twitch.tv/videos/2854311727,22,00:05:31 - 00:05:34,the point of all this? We're all dead already.,en,Missing words: What's the point.
22,141268501,https://www.twitch.tv/videos/2854311727,23,00:05:43 - 00:05:46,In four days we will be evacuating the survivor's block.,en,Correct
23,141268501,https://www.twitch.tv/videos/2854311727,24,00:05:47 - 00:05:52,The top brass will be very upset with us if we don't move a adequate number of healthy people.,en,Correct
24,141268501,https://www.twitch.tv/videos/2854311727,25,00:05:54 - 00:05:59,Carefully examine the survivors in the line and send the unaffected on to the block.,en,Correct
25,141192575,https://www.twitch.tv/videos/2852368077,1,00:00:07 - 00:00:10,"Der kann mich gar nicht erwischt, nie im Leben.",de,<NA>
26,141192575,https://www.twitch.tv/videos/2852368077,2,00:00:14 - 00:00:15,ich hab's gerade gesehen.,de,<NA>
27,141192575,https://www.twitch.tv/videos/2852368077,3,00:00:25 - 00:00:27,"Eigentlich hat das Gebäude, als wir offiziell in der Zwiebel waren.",de,<NA>
28,141192575,https://www.twitch.tv/videos/2852368077,4,00:00:46 - 00:00:53,"Ich seh' halt nicht, keine Ahnung, wo der ist.",de,<NA>
29,141192575,https://www.twitch.tv/videos/2852368077,5,00:00:59 - 00:01:04,"Irgendwo Richtung Turm drin, irgendwo da hinten, so ein bisschen weiter links.",de,<NA>
30,141192575,https://www.twitch.tv/videos/2852368077,6,00:01:08 - 00:01:16,"einen haben wir am Tachel, einer ist noch unten drin ja ja da snipet er die Lachen",de,<NA>
31,141192575,https://www.twitch.tv/videos/2852368077,7,00:01:19 - 00:01:28,"traurige ja gib mir ein Bredi ja ein richtiger Lack jetzt habe ich gepisst das, ich hätte dich geholt",de,<NA>
32,141192575,https://www.twitch.tv/videos/2852368077,8,00:01:30 - 00:01:41,"ich weiß nicht, hier haben die die selber gibt's das das war das, was du deinen eigenen Strömen liebst warte mal ich schau mal Das ist jetzt Beste.",de,<NA>
33,141192575,https://www.twitch.tv/videos/2852368077,9,00:01:42 - 00:01:43,Hinter uns.,de,<NA>
34,141192575,https://www.twitch.tv/videos/2852368077,10,00:02:06 - 00:02:13,"Die hat ja noch einer, jetzt können sie Tank und Psych nochmal.",de,<NA>
35,141192575,https://www.twitch.tv/videos/2852368077,11,00:02:14 - 00:02:18,"Oh nein, ja er snipet immer noch wo da oben.",de,<NA>
36,141192575,https://www.twitch.tv/videos/2852368077,12,00:02:21 - 00:02:27,"Kommt der Bresi auf mich? Was bist du nur für ein Hundesohn, echt?",de,<NA>
37,141192575,https://www.twitch.tv/videos/2852368077,13,00:02:38 - 00:02:44,"Der schaut bei dir aus, bitte. Ich bin hier.",de,<NA>
38,141192575,https://www.twitch.tv/videos/2852368077,14,00:02:44 - 00:02:47,"Hier, vor überall. Im Turm und so.",de,<NA>
39,141192575,https://www.twitch.tv/videos/2852368077,15,00:02:48 - 00:02:51,"Ah und eines ist aus der Kirche oben, da war es auch safe. Kein Kind, der den Dinger hat.",de,<NA>
40,141192575,https://www.twitch.tv/videos/2852368077,16,00:02:53 - 00:02:55,"Müssen wir schauen, dass wir es gleich hier so nachher kriegen.",de,<NA>
41,141192575,https://www.twitch.tv/videos/2852368077,17,00:03:12 - 00:03:20,"Na! Ja, aber die warten nicht gut. Aber was soll ich machen? Ich halte einen von oben und würde ihn vom Schub fallen.",de,<NA>
42,141192575,https://www.twitch.tv/videos/2852368077,18,00:03:20 - 00:03:21,werde ihn nicht oft ausschüssen.,de,<NA>
43,141192575,https://www.twitch.tv/videos/2852368077,19,00:03:42 - 00:03:47,Jetzt ist es dir frei.,de,<NA>
44,141192575,https://www.twitch.tv/videos/2852368077,20,00:03:49 - 00:03:53,Ich nix zu tun. So ein Pisser echt. Der da da oben umeinander.,de,<NA>
45,141192575,https://www.twitch.tv/videos/2852368077,21,00:04:05 - 00:04:10,Es dürfte also irgendwie zu irgendwas kommen. Wenn wir kurz beieinander sind.,de,<NA>
46,141192575,https://www.twitch.tv/videos/2852368077,22,00:04:12 - 00:04:18,"Einer hat nix mehr, der sitzt bei, das hat's unten, das hat's oben scheiße versucht, dass ich aufbekommen.",de,<NA>
47,141192575,https://www.twitch.tv/videos/2852368077,23,00:04:18 - 00:04:24,"das ja das, ja, hab jetzt versucht zum Ovi-Snipern, aber ich hab den scheiß Sniper unten.",de,<NA>
48,141192575,https://www.twitch.tv/videos/2852368077,24,00:04:25 - 00:04:29,"Ja, das war klar, das ist nicht mehr scharf jetzt, ich hab, mein, das hat's unten drin.",de,<NA>
49,141192575,https://www.twitch.tv/videos/2852368077,25,00:04:30 - 00:04:33,"Deswegen hab ich da schon zwei geholt, aber ja, hab ich nicht mitgekriegt.",de,<NA>
50,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,1,00:00:09 - 00:00:39,ДИНАМИЧНАЯ,ru,<NA>
51,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,2,00:01:00 - 00:01:30,"ДИНАМИЧНАЯ Ooh-ooh, kiss my shit, kiss my",ru,<NA>
52,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,3,00:01:30 - 00:01:44,"shit I heard you were talking shit And you didn't think that I would hear it People hear you talking, like",ru,<NA>
53,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,4,00:03:18 - 00:03:20,в,ru,<NA>
54,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,5,00:03:20 - 00:03:50,ДИНАМИЧНАЯ,ru,<NA>
55,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,6,00:03:50 - 00:03:54,"Так я не понимаю, нахуй он сначала девочек за бодашкой врубил?",ru,<NA>
56,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,7,00:03:57 - 00:04:04,"Чад, всем дарова, всем... Ты что, реально врубил, придурок? Блять, ты ебла нахуй, нахуй ты меня трахаешь, ебанашка Ростян, он реально врубил, Ростян?",ru,<NA>
57,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,8,00:04:04 - 00:04:26,"Да, я врубил Да Короче, дарова, Чад, привет, всем Ну вот, так вам скажу, нас сегодня распаковка анимешных фигурок, анимешных фигурок из магазина popo-man или popo-ma popo-me-me-me вот",ru,<NA>
58,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,9,00:04:28 - 00:04:56,"а, оффот? пишут, пишут, оффот, не надо стримить всё, тогда оффо, нахуй, чад, спасибо, всем пока короче, взяли конструктивного компотика, ну, такого рационального правильного, вкусного собрались в небольшой компании рациональных людей это окей Юра окей вот Юра вот Леша вот",ru,<NA>
59,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,10,00:04:57 - 00:05:26,Рациональный Леша нас сегодня Леша нас сегодня диджей Леша диджей и Растян с танком Растян с танком я тебя могу вот что будет так что то попьем пивка распакуем игрушки и ляжем спать вот все не знаю кто спать сегодня денечек такой не сбылся,ru,<NA>
60,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,11,00:05:26 - 00:05:36,спирит проебали блять моя ставка проебала блять сколько 30 6 тысяч 136 тысяч,ru,<NA>
61,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,12,00:05:39 - 00:05:44,"Да, Санька, Санька, займись, Саша, займись.",ru,<NA>
62,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,13,00:05:44 - 00:05:48,"Вот, потихоньку кое-что, пивасик сейчас поглушим и распакуем.",ru,<NA>
63,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,14,00:05:49 - 00:05:54,"Ну, пожалуй, я думаю сейчас надо самое главное это обсудить...",ru,<NA>
64,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,15,00:05:54 - 00:05:59,"Бля, давайте может столик поставим, чтобы можно... Обсудить, что ты сказал в моем тиктоке за предку?",ru,<NA>
65,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,16,00:06:00 - 00:06:05,"Мы можем сейчас обсудить игру, прошлую игру.",ru,<NA>
66,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,17,00:06:05 - 00:06:13,"А чемодан на хуя? Эту камеру слабо стоять не надо ходить, Ээээ из-за кадра поставь Вот, там будем сидеть Нет?",ru,<NA>
67,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,18,00:06:13 - 00:06:19,"Или пусть не так-то старей стоит? Не, ну всё это туда ладно, подологично Как это называется?",ru,<NA>
68,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,19,00:06:20 - 00:06:28,"Соджу Соджу Нормально или в руках будем держать? Не, туда Вместо одного держать в руках Чё, короче, вот тут посидите",ru,<NA>
69,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,20,00:06:31 - 00:06:44,"Блядь, Лёшка нахуй Ну ты вообще блядь диджей ебучий, блядь, Лёш Ну ты вообще Какой засрали нет не бать все тебе респект кидают тут тебе все все все респект кидают",ru,<NA>
70,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,21,00:06:47 - 00:07:03,"Тут тебе все все тут тебе все кидают респекта блядь жесткий Все я поставил я поставил камеру так чтобы танка тоже было видно Смотрите нормальную музыку Ха-ха-ха Напишите как видно меня, нормально?",ru,<NA>
71,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,22,00:07:03 - 00:07:20,"Вот руку поднимаю Видно нормально там? Давайте пока въебём Вот как въебём А, выпить Господи, ебаные завозы Дура, вообще как въебутая Давай, давай сейчас въебём",ru,<NA>
72,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,23,00:07:22 - 00:07:27,"Постопаливай Не, не, не Стой!",ru,<NA>
73,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,24,00:07:27 - 00:07:28,"Около зло, пацана!",ru,<NA>
74,141267623,https://www.twitch.tv/videos/2852396591?platformId=4&userId=856454,25,00:07:37 - 00:07:42,Тут даже я разъят! Чем глоток выпил?,ru,<NA>
75,141267561,https://www.twitch.tv/videos/2854116559,1,00:00:29 - 00:00:29,serai là-bas,fr,<NA>
76,141267561,https://www.twitch.tv/videos/2854116559,2,00:00:52 - 00:00:55,What you guys doing ?,fr,<NA>
77,141267561,https://www.twitch.tv/videos/2854116559,3,00:01:24 - 00:01:25,Mais quoi,fr,<NA>
78,141267561,https://www.twitch.tv/videos/2854116559,4,00:01:42 - 00:01:43,? Je serai,fr,<NA>
79,141267561,https://www.twitch.tv/videos/2854116559,5,00:02:15 - 00:02:16,là-bas,fr,<NA>
80,141267561,https://www.twitch.tv/videos/2854116559,6,00:02:38 - 00:02:41,What you guys doing ?,fr,<NA>
81,141267561,https://www.twitch.tv/videos/2854116559,7,00:03:06 - 00:03:14,"Allez mec Attendez Yo Damien, t le premier ?",fr,<NA>
82,141267561,https://www.twitch.tv/videos/2854116559,8,00:03:14 - 00:03:24,"Ouais sur tiktak t le premier, même sur Twitch je pense En tout cas le premier message Euh, y'en perd pas de temps Aujourd'hui on essaie d'avancer putain de capa de merde Comme ça c'est fait, il nous manquera quoi ?",fr,<NA>
83,141267561,https://www.twitch.tv/videos/2854116559,9,00:03:24 - 00:03:34,"Là, il'on y s'extraire avec l'autre un, ça nous donnera la peluche, et après il manquera juste l'achantique, et problème de l'achantique, c que je sais pas comment je vais le pour la trouver, mais on va tenter, on va tenter.",fr,<NA>
84,141267561,https://www.twitch.tv/videos/2854116559,10,00:03:34 - 00:03:38,"Yo Pilouf,'as va ou quoi ? Comment va le Pilouf ?",fr,<NA>
85,141267561,https://www.twitch.tv/videos/2854116559,11,00:03:39 - 00:03:44,"Allez, ça part comme ça les gars. Un second. Ça raconte quoi Pilouf ?",fr,<NA>
86,141267561,https://www.twitch.tv/videos/2854116559,12,00:03:44 - 00:03:48,"J'espère que tu vas bien Damien. Ah d'ailleurs, je voulais te faire un truc.",fr,<NA>
87,141267561,https://www.twitch.tv/videos/2854116559,13,00:04:25 - 00:04:35,"Ah bah tranquille mon Pilouf. J'peux pas t'entendre, j'suis au taf, moi un pouce avec un grand sourire pour me dire bonjour La petit pouce Putain, travailler un dimanche, terrible",fr,<NA>
88,141267561,https://www.twitch.tv/videos/2854116559,14,00:04:50 - 00:04:54,"Mais putain, Pilouf alors Pilouf tu reprends lundi, enfin demain les cours",fr,<NA>
89,141267561,https://www.twitch.tv/videos/2854116559,15,00:05:08 - 00:05:15,"Non la semaine pro, putain ok, j'pensais que vous repreniez, mais comment ça se fait La France ils reprennent pas demain ?",fr,<NA>
90,141267561,https://www.twitch.tv/videos/2854116559,16,00:05:15 - 00:05:19,"Du hommade, ça va ou combat ? Ça ou cobbg ?",fr,<NA>
91,141267561,https://www.twitch.tv/videos/2854116559,17,00:05:19 - 00:05:28,Attendez vais juste checker un truc Mais je pensais que vous les français vous repreniez déjà demain,fr,<NA>
92,141267561,https://www.twitch.tv/videos/2854116559,18,00:05:30 - 00:05:32,Je vais voir si ça ça marche,fr,<NA>
93,141267561,https://www.twitch.tv/videos/2854116559,19,00:05:45 - 00:05:56,Ah nique sa mère je vais juste checker un truc mette à pied Allez go Merci pour le follow mon petit mat Ah c'est mon frère 1 septembre en Putain Putain mais là on déglandeur jusqu'à...,fr,<NA>
94,141267561,https://www.twitch.tv/videos/2854116559,20,00:05:56 - 00:06:15,Oh mais les la game va être très chiante hein parce que c ici mon extract C'est ici mon extract les gars putain Je dois attendre 20 minutes avant que le train arrive Je tuer les rogues je vais aller me faire les rogues et je vais goûter un peu la zone.,fr,<NA>
95,141267561,https://www.twitch.tv/videos/2854116559,21,00:06:17 - 00:06:26,"êtes vraiment dégueulasses, pile ouf vous les français, et c'est pour toute la France le 1er septembre ou vous vous avez par zone A baissé là,'autrui de con là.",fr,<NA>
96,141267561,https://www.twitch.tv/videos/2854116559,22,00:06:27 - 00:06:33,"Je jamais comment ça marche, j'attends que le train arrive les gars, ouais toute la France ok.",fr,<NA>
97,141267561,https://www.twitch.tv/videos/2854116559,23,00:06:36 - 00:06:41,"C'est terrible là, parce que je peux me faire fumer à tout moment. Attendez.",fr,<NA>
98,141267561,https://www.twitch.tv/videos/2854116559,24,00:06:49 - 00:06:52,"Waouh, tu vois ? Terrible.",fr,<NA>
99,141267561,https://www.twitch.tv/videos/2854116559,25,00:06:58 - 00:06:59,Écoute mon malade.,fr,<NA>
100,141268448,https://www.twitch.tv/videos/2853628924,1,00:03:03 - 00:03:14,hola hola que tal gente silla estamos aquí otra vez un día más vamos al charlando,es,<NA>
101,141268448,https://www.twitch.tv/videos/2853628924,2,00:03:17 - 00:03:47,hello como estáis como estáis ahora estoy bastante cansada pero tengo una cosa aquí estamos aquí cumplimos vale pues hoy vamos a jugar a los dinosaurios que me apetece un ratito aunque sea y ya luego vamos al balo en un ratito hoy no me quedaré mucho porque me apetece estar más en la gama todo esto me hecho una siesta cuando he llegado,es,<NA>
102,141268448,https://www.twitch.tv/videos/2853628924,3,00:03:47 - 00:03:59,de tres horas y claro una mañana que hay que trabajar entonces prefiero irme tempranito que sabemos como acaba de irse tempranito pero bueno lo cuento igual.,es,<NA>
103,141268448,https://www.twitch.tv/videos/2853628924,4,00:04:02 - 00:04:05,eh... Vale. ¿Dónde está? ¿Dónde está?,es,<NA>
104,141268448,https://www.twitch.tv/videos/2853628924,5,00:04:05 - 00:04:06,"Aquí,",es,<NA>
105,141268448,https://www.twitch.tv/videos/2853628924,6,00:04:11 - 00:04:13,"Let's go. Vamos allá, continúen.",es,<NA>
106,141268448,https://www.twitch.tv/videos/2853628924,7,00:04:18 - 00:04:21,"Vale, voy limpiar un momentito rápido el teclado.",es,<NA>
107,141268448,https://www.twitch.tv/videos/2853628924,8,00:04:30 - 00:04:33,Vale. Vale.,es,<NA>
108,141268448,https://www.twitch.tv/videos/2853628924,9,00:04:38 - 00:04:49,"Pero no lo que tenía que hacer, tipo, las dos canastas y los ladrillos de piedra vale,",es,<NA>
109,141268448,https://www.twitch.tv/videos/2853628924,10,00:04:52 - 00:05:03,"ehm, los de piedra y las dos canastas, tengo que hacer nooo, una planta por la puta,",es,<NA>
110,141268448,https://www.twitch.tv/videos/2853628924,11,00:05:08 - 00:05:17,"falta una planta ah ya tengo las dos vale, ok, eh vamos a reunirnos con Bryce",es,<NA>
111,141268448,https://www.twitch.tv/videos/2853628924,12,00:05:35 - 00:05:44,"¿Por qué hay emisiones? ¿Qué más tenían? Aumentar la población, pero eso lo vas diciendo poco a",es,<NA>
112,141268448,https://www.twitch.tv/videos/2853628924,13,00:05:48 - 00:05:54,Vamos... ¡Eh! ¡Estamos en invierno! ¿Por qué por el primavera ya está nevando?,es,<NA>
113,141268448,https://www.twitch.tv/videos/2853628924,14,00:06:04 - 00:06:10,"Enchiendo. ¿Vamos dónde, Bryce?",es,<NA>
114,141268448,https://www.twitch.tv/videos/2853628924,15,00:06:11 - 00:06:12,"Vale, esto de que...",es,<NA>
115,141268448,https://www.twitch.tv/videos/2853628924,16,00:06:18 - 00:06:24,Pero ¿por qué está nevando? una pregunta muy sería,es,<NA>
116,141268448,https://www.twitch.tv/videos/2853628924,17,00:06:30 - 00:06:34,vale vamos para arriba,es,<NA>

In [10]:
import duckdb
import pandas as pd

LANGUAGE = "en"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

english_segments = con.execute(
    f"""
    WITH source AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE lang_detected = '{LANGUAGE}'
          AND transcript_segments IS NOT NULL
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            UNNEST(transcript_segments) AS segment
        FROM source
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            segment.text AS segment_text,
            segment.timestamp[1] AS segment_start,
            segment.timestamp[2] AS segment_end
        FROM exploded
        WHERE segment.text IS NOT NULL
          AND len(segment.words) >= {MIN_WORDS}
    ),
    latest_session AS (
        SELECT gamesession_id
        FROM eligible
        GROUP BY gamesession_id
        ORDER BY MAX(TRY_CAST(created_at AS TIMESTAMP)) DESC, gamesession_id DESC
        LIMIT 1
    ),
    selected AS (
        SELECT
            e.*,
            ROW_NUMBER() OVER (
                ORDER BY segment_start, segment_end
            ) AS segment_index
        FROM eligible e
        JOIN latest_session l USING (gamesession_id)
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        lang_detected AS language_detected
    FROM selected
    ORDER BY segment_index
    LIMIT {SEGMENTS_NEEDED}
    """
).df()

def format_timestamp(seconds):
    seconds = int(seconds)
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

english_segments["segment_timestamp"] = (
    english_segments["segment_start"].map(format_timestamp)
    + " - "
    + english_segments["segment_end"].map(format_timestamp)
)

english_segments["VERDICT"] = ""

english_segments = english_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(english_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268501,https://www.twitch.tv/videos/2854311727,1,00:00:14 - 00:00:15,"Don't be talking, shut my door.",en,
1,141268501,https://www.twitch.tv/videos/2854311727,2,00:02:23 - 00:02:25,We'll start with the basics.,en,
2,141268501,https://www.twitch.tv/videos/2854311727,3,00:02:46 - 00:02:49,actually showed up. You guys owe me ten bucks.,en,
3,141268501,https://www.twitch.tv/videos/2854311727,4,00:02:50 - 00:02:54,"personal. It's just, uh, we're stuck in Groundhog Day out here.",en,
4,141268501,https://www.twitch.tv/videos/2854311727,5,00:02:55 - 00:02:59,"trying to, you know, not go crazy..",en,
5,141268501,https://www.twitch.tv/videos/2854311727,6,00:02:59 - 00:03:06,"Okay, it's simple really, shout next and the guys will let the survivor in.",en,
6,141268501,https://www.twitch.tv/videos/2854311727,7,00:03:20 - 00:03:26,"Next survivor. First, do a simple inspection.",en,
7,141268501,https://www.twitch.tv/videos/2854311727,8,00:03:27 - 00:03:28,Take the flashlight from the table.,en,
8,141268501,https://www.twitch.tv/videos/2854311727,9,00:03:44 - 00:03:47,Take your time. Match what you see against the symptom chart.,en,
9,141268501,https://www.twitch.tv/videos/2854311727,10,00:03:48 - 00:03:55,devil's in the details. Identify the particular ailment and click symptom locked.,en,
10,141268501,https://www.twitch.tv/videos/2854311727,11,00:03:55 - 00:03:58,"If you mark most symptoms correctly, you'll get a reward.",en,
11,141268501,https://www.twitch.tv/videos/2854311727,12,00:04:05 - 00:04:08,"Once you've recorded the symptoms, time to decide their fate.",en,
12,141268501,https://www.twitch.tv/videos/2854311727,13,00:04:08 - 00:04:12,Let's switch to the distribution tab. You are in a quarantine zone.,en,
13,141268501,https://www.twitch.tv/videos/2854311727,14,00:04:12 - 00:04:16,Stay calm and wait for your turn. Remove your outer clothing.,en,
14,141268501,https://www.twitch.tv/videos/2854311727,15,00:04:17 - 00:04:20,Still not sure. No worries. Just send them into quarantine.,en,
15,141268501,https://www.twitch.tv/videos/2854311727,16,00:04:21 - 00:04:24,"Let them sit for a few days, the virus will reveal itself.",en,
16,141268501,https://www.twitch.tv/videos/2854311727,17,00:04:25 - 00:04:29,Like a friend of mine used to say. Can't piss in the gas tank.,en,
17,141268501,https://www.twitch.tv/videos/2854311727,18,00:04:29 - 00:04:34,"I'm not sure what he meant exactly, your choice may have consequences for the whole camp.",en,
18,141268501,https://www.twitch.tv/videos/2854311727,19,00:04:35 - 00:04:38,If you let the wrong one in. What's,en,
19,141268501,https://www.twitch.tv/videos/2854311727,20,00:05:31 - 00:05:34,the point of all this? We're all dead already.,en,
20,141268501,https://www.twitch.tv/videos/2854311727,21,00:05:43 - 00:05:46,In four days we will be evacuating the survivor's block.,en,
21,141268501,https://www.twitch.tv/videos/2854311727,22,00:05:47 - 00:05:52,The top brass will be very upset with us if we don't move a adequate number of healthy people.,en,
22,141268501,https://www.twitch.tv/videos/2854311727,23,00:05:54 - 00:05:59,Carefully examine the survivors in the line and send the unaffected on to the block.,en,
23,141268501,https://www.twitch.tv/videos/2854311727,24,00:06:21 - 00:06:27,What's the point? Don't make me wait.,en,
24,141268501,https://www.twitch.tv/videos/2854311727,25,00:06:30 - 00:06:33,"Please, we hurry? I think we were followed.",en,

In [ ]:
import duckdb
import pandas as pd

LANGUAGE = "en"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

english_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM eligible
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


english_segments["segment_timestamp"] = (
    english_segments["segment_start"].map(format_timestamp)
    + " - "
    + english_segments["segment_end"].map(format_timestamp)
)

english_segments["VERDICT"] = ""

english_segments = english_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(english_segments)

In [12]:
import duckdb
import pandas as pd

LANGUAGE = "de"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

german_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM eligible
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


german_segments["segment_timestamp"] = (
    german_segments["segment_start"].map(format_timestamp)
    + " - "
    + german_segments["segment_end"].map(format_timestamp)
)

german_segments["VERDICT"] = ""

german_segments = german_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(german_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141192575,https://www.twitch.tv/videos/2852368077,1,00:00:07 - 00:00:10,"Der kann mich gar nicht erwischt, nie im Leben.",de,
1,141192575,https://www.twitch.tv/videos/2852368077,2,00:00:14 - 00:00:15,ich hab's gerade gesehen.,de,
2,141192575,https://www.twitch.tv/videos/2852368077,3,00:00:25 - 00:00:27,"Eigentlich hat das Gebäude, als wir offiziell in der Zwiebel waren.",de,
3,141192575,https://www.twitch.tv/videos/2852368077,4,00:00:46 - 00:00:53,"Ich seh' halt nicht, keine Ahnung, wo der ist.",de,
4,141192575,https://www.twitch.tv/videos/2852368077,5,00:00:59 - 00:01:04,"Irgendwo Richtung Turm drin, irgendwo da hinten, so ein bisschen weiter links.",de,
5,141192575,https://www.twitch.tv/videos/2852368077,6,00:01:08 - 00:01:16,"einen haben wir am Tachel, einer ist noch unten drin ja ja da snipet er die Lachen",de,
6,141192575,https://www.twitch.tv/videos/2852368077,7,00:01:19 - 00:01:28,"traurige ja gib mir ein Bredi ja ein richtiger Lack jetzt habe ich gepisst das, ich hätte dich geholt",de,
7,141192575,https://www.twitch.tv/videos/2852368077,8,00:01:30 - 00:01:41,"ich weiß nicht, hier haben die die selber gibt's das das war das, was du deinen eigenen Strömen liebst warte mal ich schau mal Das ist jetzt Beste.",de,
8,141192575,https://www.twitch.tv/videos/2852368077,10,00:02:06 - 00:02:13,"Die hat ja noch einer, jetzt können sie Tank und Psych nochmal.",de,
9,141192575,https://www.twitch.tv/videos/2852368077,11,00:02:14 - 00:02:18,"Oh nein, ja er snipet immer noch wo da oben.",de,
10,141192575,https://www.twitch.tv/videos/2852368077,12,00:02:21 - 00:02:27,"Kommt der Bresi auf mich? Was bist du nur für ein Hundesohn, echt?",de,
11,141192575,https://www.twitch.tv/videos/2852368077,13,00:02:38 - 00:02:44,"Der schaut bei dir aus, bitte. Ich bin hier.",de,
12,141192575,https://www.twitch.tv/videos/2852368077,14,00:02:44 - 00:02:47,"Hier, vor überall. Im Turm und so.",de,
13,141192575,https://www.twitch.tv/videos/2852368077,15,00:02:48 - 00:02:51,"Ah und eines ist aus der Kirche oben, da war es auch safe. Kein Kind, der den Dinger hat.",de,
14,141192575,https://www.twitch.tv/videos/2852368077,16,00:02:53 - 00:02:55,"Müssen wir schauen, dass wir es gleich hier so nachher kriegen.",de,
15,141192575,https://www.twitch.tv/videos/2852368077,17,00:03:12 - 00:03:20,"Na! Ja, aber die warten nicht gut. Aber was soll ich machen? Ich halte einen von oben und würde ihn vom Schub fallen.",de,
16,141192575,https://www.twitch.tv/videos/2852368077,18,00:03:20 - 00:03:21,werde ihn nicht oft ausschüssen.,de,
17,141192575,https://www.twitch.tv/videos/2852368077,19,00:03:42 - 00:03:47,Jetzt ist es dir frei.,de,
18,141192575,https://www.twitch.tv/videos/2852368077,20,00:03:49 - 00:03:53,Ich nix zu tun. So ein Pisser echt. Der da da oben umeinander.,de,
19,141192575,https://www.twitch.tv/videos/2852368077,21,00:04:05 - 00:04:10,Es dürfte also irgendwie zu irgendwas kommen. Wenn wir kurz beieinander sind.,de,
20,141192575,https://www.twitch.tv/videos/2852368077,22,00:04:12 - 00:04:18,"Einer hat nix mehr, der sitzt bei, das hat's unten, das hat's oben scheiße versucht, dass ich aufbekommen.",de,
21,141192575,https://www.twitch.tv/videos/2852368077,23,00:04:18 - 00:04:24,"das ja das, ja, hab jetzt versucht zum Ovi-Snipern, aber ich hab den scheiß Sniper unten.",de,
22,141192575,https://www.twitch.tv/videos/2852368077,24,00:04:25 - 00:04:29,"Ja, das war klar, das ist nicht mehr scharf jetzt, ich hab, mein, das hat's unten drin.",de,
23,141192575,https://www.twitch.tv/videos/2852368077,25,00:04:30 - 00:04:33,"Deswegen hab ich da schon zwei geholt, aber ja, hab ich nicht mitgekriegt.",de,
24,141192575,https://www.twitch.tv/videos/2852368077,26,00:04:33 - 00:04:39,"Ich hab, mein, das kommt jetzt Richtung mir, weißt schon, weil ich schon da war. Aber ist ja geil, macht nix.",de,

In [13]:
import duckdb
import pandas as pd

LANGUAGE = "fr"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

french_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM eligible
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


french_segments["segment_timestamp"] = (
    french_segments["segment_start"].map(format_timestamp)
    + " - "
    + french_segments["segment_end"].map(format_timestamp)
)

french_segments["VERDICT"] = ""

french_segments = french_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(french_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141267561,https://www.twitch.tv/videos/2854116559,2,00:00:52 - 00:00:55,What you guys doing ?,fr,
1,141267561,https://www.twitch.tv/videos/2854116559,6,00:02:38 - 00:02:41,What you guys doing ?,fr,
2,141267561,https://www.twitch.tv/videos/2854116559,7,00:03:06 - 00:03:14,"Allez mec Attendez Yo Damien, t le premier ?",fr,
3,141267561,https://www.twitch.tv/videos/2854116559,8,00:03:14 - 00:03:24,"Ouais sur tiktak t le premier, même sur Twitch je pense En tout cas le premier message Euh, y'en perd pas de temps Aujourd'hui on essaie d'avancer putain de capa de merde Comme ça c'est fait, il nous manquera quoi ?",fr,
4,141267561,https://www.twitch.tv/videos/2854116559,9,00:03:24 - 00:03:34,"Là, il'on y s'extraire avec l'autre un, ça nous donnera la peluche, et après il manquera juste l'achantique, et problème de l'achantique, c que je sais pas comment je vais le pour la trouver, mais on va tenter, on va tenter.",fr,
5,141267561,https://www.twitch.tv/videos/2854116559,10,00:03:34 - 00:03:38,"Yo Pilouf,'as va ou quoi ? Comment va le Pilouf ?",fr,
6,141267561,https://www.twitch.tv/videos/2854116559,11,00:03:39 - 00:03:44,"Allez, ça part comme ça les gars. Un second. Ça raconte quoi Pilouf ?",fr,
7,141267561,https://www.twitch.tv/videos/2854116559,12,00:03:44 - 00:03:48,"J'espère que tu vas bien Damien. Ah d'ailleurs, je voulais te faire un truc.",fr,
8,141267561,https://www.twitch.tv/videos/2854116559,13,00:04:25 - 00:04:35,"Ah bah tranquille mon Pilouf. J'peux pas t'entendre, j'suis au taf, moi un pouce avec un grand sourire pour me dire bonjour La petit pouce Putain, travailler un dimanche, terrible",fr,
9,141267561,https://www.twitch.tv/videos/2854116559,14,00:04:50 - 00:04:54,"Mais putain, Pilouf alors Pilouf tu reprends lundi, enfin demain les cours",fr,
10,141267561,https://www.twitch.tv/videos/2854116559,15,00:05:08 - 00:05:15,"Non la semaine pro, putain ok, j'pensais que vous repreniez, mais comment ça se fait La France ils reprennent pas demain ?",fr,
11,141267561,https://www.twitch.tv/videos/2854116559,16,00:05:15 - 00:05:19,"Du hommade, ça va ou combat ? Ça ou cobbg ?",fr,
12,141267561,https://www.twitch.tv/videos/2854116559,17,00:05:19 - 00:05:28,Attendez vais juste checker un truc Mais je pensais que vous les français vous repreniez déjà demain,fr,
13,141267561,https://www.twitch.tv/videos/2854116559,18,00:05:30 - 00:05:32,Je vais voir si ça ça marche,fr,
14,141267561,https://www.twitch.tv/videos/2854116559,19,00:05:45 - 00:05:56,Ah nique sa mère je vais juste checker un truc mette à pied Allez go Merci pour le follow mon petit mat Ah c'est mon frère 1 septembre en Putain Putain mais là on déglandeur jusqu'à...,fr,
15,141267561,https://www.twitch.tv/videos/2854116559,20,00:05:56 - 00:06:15,Oh mais les la game va être très chiante hein parce que c ici mon extract C'est ici mon extract les gars putain Je dois attendre 20 minutes avant que le train arrive Je tuer les rogues je vais aller me faire les rogues et je vais goûter un peu la zone.,fr,
16,141267561,https://www.twitch.tv/videos/2854116559,21,00:06:17 - 00:06:26,"êtes vraiment dégueulasses, pile ouf vous les français, et c'est pour toute la France le 1er septembre ou vous vous avez par zone A baissé là,'autrui de con là.",fr,
17,141267561,https://www.twitch.tv/videos/2854116559,22,00:06:27 - 00:06:33,"Je jamais comment ça marche, j'attends que le train arrive les gars, ouais toute la France ok.",fr,
18,141267561,https://www.twitch.tv/videos/2854116559,23,00:06:36 - 00:06:41,"C'est terrible là, parce que je peux me faire fumer à tout moment. Attendez.",fr,
19,141267561,https://www.twitch.tv/videos/2854116559,24,00:06:49 - 00:06:52,"Waouh, tu vois ? Terrible.",fr,
20,141267561,https://www.twitch.tv/videos/2854116559,26,00:07:05 - 00:07:08,Il combien d'heures de jeu ? 7000. 7000 hommes mon petit mate.,fr,
21,141267561,https://www.twitch.tv/videos/2854116559,27,00:07:11 - 00:07:17,"En gros chat, si je m'extrais ici, bon ça me donnera une couronne initiale mais c pas ça, ça me donnera l'ourson.",fr,
22,141267561,https://www.twitch.tv/videos/2854116559,28,00:07:17 - 00:07:20,"Et après il manquera que le, regardez, que la hache antique.",fr,
23,141267561,https://www.twitch.tv/videos/2854116559,29,00:07:21 - 00:07:32,que la chantique et a la capa bon après il juste prendre la voiture et tout les zones c que pour les vacances pas grande ok putain mais le 3 septembre c dingue de reprendre le 3 septembre,fr,
24,141267561,https://www.twitch.tv/videos/2854116559,30,00:07:47 - 00:07:55,d'ailleurs faut que'envoie un mille Matt t'es déjà passé sur Twitch toi non?,fr,

In [14]:
import duckdb
import pandas as pd

LANGUAGE = "fr"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

french_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    ),
    deduplicated AS (
        SELECT *
        FROM eligible
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY LOWER(TRIM(segment_text))
            ORDER BY segment_index ASC
        ) = 1
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM deduplicated
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


french_segments["segment_timestamp"] = (
    french_segments["segment_start"].map(format_timestamp)
    + " - "
    + french_segments["segment_end"].map(format_timestamp)
)

french_segments["VERDICT"] = ""

french_segments = french_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(french_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141267561,https://www.twitch.tv/videos/2854116559,2,00:00:52 - 00:00:55,What you guys doing ?,fr,
1,141267561,https://www.twitch.tv/videos/2854116559,7,00:03:06 - 00:03:14,"Allez mec Attendez Yo Damien, t le premier ?",fr,
2,141267561,https://www.twitch.tv/videos/2854116559,8,00:03:14 - 00:03:24,"Ouais sur tiktak t le premier, même sur Twitch je pense En tout cas le premier message Euh, y'en perd pas de temps Aujourd'hui on essaie d'avancer putain de capa de merde Comme ça c'est fait, il nous manquera quoi ?",fr,
3,141267561,https://www.twitch.tv/videos/2854116559,9,00:03:24 - 00:03:34,"Là, il'on y s'extraire avec l'autre un, ça nous donnera la peluche, et après il manquera juste l'achantique, et problème de l'achantique, c que je sais pas comment je vais le pour la trouver, mais on va tenter, on va tenter.",fr,
4,141267561,https://www.twitch.tv/videos/2854116559,10,00:03:34 - 00:03:38,"Yo Pilouf,'as va ou quoi ? Comment va le Pilouf ?",fr,
5,141267561,https://www.twitch.tv/videos/2854116559,11,00:03:39 - 00:03:44,"Allez, ça part comme ça les gars. Un second. Ça raconte quoi Pilouf ?",fr,
6,141267561,https://www.twitch.tv/videos/2854116559,12,00:03:44 - 00:03:48,"J'espère que tu vas bien Damien. Ah d'ailleurs, je voulais te faire un truc.",fr,
7,141267561,https://www.twitch.tv/videos/2854116559,13,00:04:25 - 00:04:35,"Ah bah tranquille mon Pilouf. J'peux pas t'entendre, j'suis au taf, moi un pouce avec un grand sourire pour me dire bonjour La petit pouce Putain, travailler un dimanche, terrible",fr,
8,141267561,https://www.twitch.tv/videos/2854116559,14,00:04:50 - 00:04:54,"Mais putain, Pilouf alors Pilouf tu reprends lundi, enfin demain les cours",fr,
9,141267561,https://www.twitch.tv/videos/2854116559,15,00:05:08 - 00:05:15,"Non la semaine pro, putain ok, j'pensais que vous repreniez, mais comment ça se fait La France ils reprennent pas demain ?",fr,
10,141267561,https://www.twitch.tv/videos/2854116559,16,00:05:15 - 00:05:19,"Du hommade, ça va ou combat ? Ça ou cobbg ?",fr,
11,141267561,https://www.twitch.tv/videos/2854116559,17,00:05:19 - 00:05:28,Attendez vais juste checker un truc Mais je pensais que vous les français vous repreniez déjà demain,fr,
12,141267561,https://www.twitch.tv/videos/2854116559,18,00:05:30 - 00:05:32,Je vais voir si ça ça marche,fr,
13,141267561,https://www.twitch.tv/videos/2854116559,19,00:05:45 - 00:05:56,Ah nique sa mère je vais juste checker un truc mette à pied Allez go Merci pour le follow mon petit mat Ah c'est mon frère 1 septembre en Putain Putain mais là on déglandeur jusqu'à...,fr,
14,141267561,https://www.twitch.tv/videos/2854116559,20,00:05:56 - 00:06:15,Oh mais les la game va être très chiante hein parce que c ici mon extract C'est ici mon extract les gars putain Je dois attendre 20 minutes avant que le train arrive Je tuer les rogues je vais aller me faire les rogues et je vais goûter un peu la zone.,fr,
15,141267561,https://www.twitch.tv/videos/2854116559,21,00:06:17 - 00:06:26,"êtes vraiment dégueulasses, pile ouf vous les français, et c'est pour toute la France le 1er septembre ou vous vous avez par zone A baissé là,'autrui de con là.",fr,
16,141267561,https://www.twitch.tv/videos/2854116559,22,00:06:27 - 00:06:33,"Je jamais comment ça marche, j'attends que le train arrive les gars, ouais toute la France ok.",fr,
17,141267561,https://www.twitch.tv/videos/2854116559,23,00:06:36 - 00:06:41,"C'est terrible là, parce que je peux me faire fumer à tout moment. Attendez.",fr,
18,141267561,https://www.twitch.tv/videos/2854116559,24,00:06:49 - 00:06:52,"Waouh, tu vois ? Terrible.",fr,
19,141267561,https://www.twitch.tv/videos/2854116559,26,00:07:05 - 00:07:08,Il combien d'heures de jeu ? 7000. 7000 hommes mon petit mate.,fr,
20,141267561,https://www.twitch.tv/videos/2854116559,27,00:07:11 - 00:07:17,"En gros chat, si je m'extrais ici, bon ça me donnera une couronne initiale mais c pas ça, ça me donnera l'ourson.",fr,
21,141267561,https://www.twitch.tv/videos/2854116559,28,00:07:17 - 00:07:20,"Et après il manquera que le, regardez, que la hache antique.",fr,
22,141267561,https://www.twitch.tv/videos/2854116559,29,00:07:21 - 00:07:32,que la chantique et a la capa bon après il juste prendre la voiture et tout les zones c que pour les vacances pas grande ok putain mais le 3 septembre c dingue de reprendre le 3 septembre,fr,
23,141267561,https://www.twitch.tv/videos/2854116559,30,00:07:47 - 00:07:55,d'ailleurs faut que'envoie un mille Matt t'es déjà passé sur Twitch toi non?,fr,
24,141267561,https://www.twitch.tv/videos/2854116559,31,00:07:55 - 00:07:57,comme surtout il comme ça il me dit un truc,fr,

In [15]:
import duckdb
import pandas as pd

LANGUAGE = "pt"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

portuguese_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    ),
    deduplicated AS (
        SELECT *
        FROM eligible
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY LOWER(TRIM(segment_text))
            ORDER BY segment_index ASC
        ) = 1
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM deduplicated
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


portuguese_segments["segment_timestamp"] = (
    portuguese_segments["segment_start"].map(format_timestamp)
    + " - "
    + portuguese_segments["segment_end"].map(format_timestamp)
)

portuguese_segments["VERDICT"] = ""

portuguese_segments = portuguese_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(portuguese_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268410,https://www.twitch.tv/videos/2854267348,1,00:09:52 - 00:09:59,FUERTA DE RAHIM Ta,pt,
1,141268410,https://www.twitch.tv/videos/2854267348,2,00:10:54 - 00:11:10,de pé E Fui FUERTA RAHIM E ASSISTA FUERTA FAZ FUERTA RAHIM FUERTA RAHIM,pt,
2,141268410,https://www.twitch.tv/videos/2854267348,3,00:11:13 - 00:11:19,FUERTA RAHIM porta aberta e isso,pt,
3,141268410,https://www.twitch.tv/videos/2854267348,4,00:11:23 - 00:11:47,ok então estou bebendo um café hoje seria o dia do chill stream mas essa semana eu não joguei a LoL eu queria jogar a LoL eu queria jogar a LoL o chill stream significa que eu decido então se eu quero jogar LoL eu a LoL e vocês pegam no cu aquele eu mais alto talvez,pt,
4,141268410,https://www.twitch.tv/videos/2854267348,5,00:11:54 - 00:11:57,Como você Como você Galaxi?,pt,
5,141268410,https://www.twitch.tv/videos/2854267348,6,00:11:58 - 00:12:02,"Você fazendo tudo, você está certo. Como você Pasta?",pt,
6,141268410,https://www.twitch.tv/videos/2854267348,7,00:12:02 - 00:12:09,"Como você está? Shadow? Tudo bem, garotos? Razy, como você Tchau garotos, tchau a você bem?",pt,
7,141268410,https://www.twitch.tv/videos/2854267348,8,00:12:14 - 00:12:18,"O Urco desde esta manhã, oh Deus, desta manhã...",pt,
8,141268410,https://www.twitch.tv/videos/2854267348,9,00:12:18 - 00:12:21,"Eu não estava. E saiu também no meu schedule, não sei se você viu.",pt,
9,141268410,https://www.twitch.tv/videos/2854267348,10,00:12:22 - 00:12:28,"Que é feito, não mais a Dorari. Mas é a...",pt,
10,141268410,https://www.twitch.tv/videos/2854267348,12,00:12:36 - 00:12:44,"Não sei se vocês viram. Período, horário da noite, Não sei se vocês viram.",pt,
11,141268410,https://www.twitch.tv/videos/2854267348,13,00:12:45 - 00:12:50,"O vocês pensam? Pensam que é muito mais descomodado, ou pode ficar?",pt,
12,141268410,https://www.twitch.tv/videos/2854267348,14,00:12:51 - 00:12:55,"Em sua opinião. Para mim é melhor, porque menos...",pt,
13,141268410,https://www.twitch.tv/videos/2854267348,15,00:12:55 - 00:13:01,"Por como eu eu, me ajuda mais com a minha desabilidade, porque eu um pouco desabelhado.",pt,
14,141268410,https://www.twitch.tv/videos/2854267348,16,00:13:05 - 00:13:08,"Não, ainda tem a resposta! Caramba!",pt,
15,141268410,https://www.twitch.tv/videos/2854267348,17,00:13:09 - 00:13:13,"Era, porque na passada era a resposta. Eu me esqueci de modificar ela.",pt,
16,141268410,https://www.twitch.tv/videos/2854267348,18,00:13:13 - 00:13:20,Ah resposta de novo. Porra de Eu me de a resposta por sempre.,pt,
17,141268410,https://www.twitch.tv/videos/2854267348,19,00:13:20 - 00:13:25,"Mas por sempre, eu já Porque depois eu me identificarei na semana próxima e deixarei aqui.",pt,
18,141268410,https://www.twitch.tv/videos/2854267348,20,00:13:27 - 00:13:37,"Ai meu Residência Residência, residência Ai meu Deus",pt,
19,141268410,https://www.twitch.tv/videos/2854267348,21,00:13:40 - 00:13:46,"Apreciamos o que você sabe, eu sei Eu sei, eu sei Eu um pouco estranho",pt,
20,141268410,https://www.twitch.tv/videos/2854267348,22,00:13:55 - 00:13:58,"Mas com o domingo sério, entende a durada? uma das duas?",pt,
21,141268410,https://www.twitch.tv/videos/2854267348,23,00:13:58 - 00:14:03,"Não, a durada Porque tipo...",pt,
22,141268410,https://www.twitch.tv/videos/2854267348,24,00:14:03 - 00:14:13,"Era domingo tarde Mas eu sei como escrever O início da manhã, o início da manhã era a 19h, que eu sei, manhã, na Poderia escrever a manhã,",pt,
23,141268410,https://www.twitch.tv/videos/2854267348,25,00:14:16 - 00:14:19,Mas sim. sim. Dois stream de fila.,pt,
24,141268410,https://www.twitch.tv/videos/2854267348,26,00:14:20 - 00:14:24,"Bem, é a domenical. Ah, você diz por dois dias de fila.",pt,

In [16]:
import duckdb
import pandas as pd

LANGUAGE = "es"
SEGMENTS_NEEDED = 25
MIN_WORDS = 4

con = duckdb.connect()

spanish_segments = con.execute(
    f"""
    WITH latest_session AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            transcript_segments
        FROM read_parquet('{PARQUET_PATH.as_posix()}')
        WHERE
            lang_detected = '{LANGUAGE}'
            AND transcript_segments IS NOT NULL
        ORDER BY
            TRY_CAST(created_at AS TIMESTAMP) DESC,
            gamesession_id DESC
        LIMIT 1
    ),
    exploded AS (
        SELECT
            gamesession_id,
            url,
            model_type,
            created_at,
            lang_detected,
            lang_probability,
            generate_subscripts(transcript_segments, 1) AS segment_index,
            UNNEST(transcript_segments) AS segment
        FROM latest_session
    ),
    eligible AS (
        SELECT
            gamesession_id,
            url,
            segment_index,
            TRY_CAST(segment.timestamp[1] AS DOUBLE) AS segment_start,
            TRY_CAST(segment.timestamp[2] AS DOUBLE) AS segment_end,
            TRIM(segment.text) AS segment_text,
            lang_detected AS language_detected
        FROM exploded
        WHERE
            segment.text IS NOT NULL
            AND TRIM(segment.text) <> ''
            AND len(segment.words) >= {MIN_WORDS}
    ),
    deduplicated AS (
        SELECT *
        FROM eligible
        QUALIFY ROW_NUMBER() OVER (
            PARTITION BY LOWER(TRIM(segment_text))
            ORDER BY segment_index ASC
        ) = 1
    )
    SELECT
        gamesession_id,
        url,
        segment_index,
        segment_start,
        segment_end,
        segment_text,
        language_detected
    FROM deduplicated
    WHERE
        segment_start IS NOT NULL
        AND segment_end IS NOT NULL
    ORDER BY segment_index ASC
    LIMIT {SEGMENTS_NEEDED}
    """
).df()


def format_timestamp(seconds):
    total_seconds = int(float(seconds))
    hours, remainder = divmod(total_seconds, 3600)
    minutes, seconds = divmod(remainder, 60)

    return f"{hours:02d}:{minutes:02d}:{seconds:02d}"


spanish_segments["segment_timestamp"] = (
    spanish_segments["segment_start"].map(format_timestamp)
    + " - "
    + spanish_segments["segment_end"].map(format_timestamp)
)

spanish_segments["VERDICT"] = ""

spanish_segments = spanish_segments[
    [
        "gamesession_id",
        "url",
        "segment_index",
        "segment_timestamp",
        "segment_text",
        "language_detected",
        "VERDICT",
    ]
]

with pd.option_context(
    "display.max_rows", None,
    "display.max_columns", None,
    "display.max_colwidth", None,
    "display.width", None,
):
    display(spanish_segments)

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

,gamesession_id,url,segment_index,segment_timestamp,segment_text,language_detected,VERDICT
0,141268448,https://www.twitch.tv/videos/2853628924,1,00:03:03 - 00:03:14,hola hola que tal gente silla estamos aquí otra vez un día más vamos al charlando,es,
1,141268448,https://www.twitch.tv/videos/2853628924,2,00:03:17 - 00:03:47,hello como estáis como estáis ahora estoy bastante cansada pero tengo una cosa aquí estamos aquí cumplimos vale pues hoy vamos a jugar a los dinosaurios que me apetece un ratito aunque sea y ya luego vamos al balo en un ratito hoy no me quedaré mucho porque me apetece estar más en la gama todo esto me hecho una siesta cuando he llegado,es,
2,141268448,https://www.twitch.tv/videos/2853628924,3,00:03:47 - 00:03:59,de tres horas y claro una mañana que hay que trabajar entonces prefiero irme tempranito que sabemos como acaba de irse tempranito pero bueno lo cuento igual.,es,
3,141268448,https://www.twitch.tv/videos/2853628924,4,00:04:02 - 00:04:05,eh... Vale. ¿Dónde está? ¿Dónde está?,es,
4,141268448,https://www.twitch.tv/videos/2853628924,6,00:04:11 - 00:04:13,"Let's go. Vamos allá, continúen.",es,
5,141268448,https://www.twitch.tv/videos/2853628924,7,00:04:18 - 00:04:21,"Vale, voy limpiar un momentito rápido el teclado.",es,
6,141268448,https://www.twitch.tv/videos/2853628924,9,00:04:38 - 00:04:49,"Pero no lo que tenía que hacer, tipo, las dos canastas y los ladrillos de piedra vale,",es,
7,141268448,https://www.twitch.tv/videos/2853628924,10,00:04:52 - 00:05:03,"ehm, los de piedra y las dos canastas, tengo que hacer nooo, una planta por la puta,",es,
8,141268448,https://www.twitch.tv/videos/2853628924,11,00:05:08 - 00:05:17,"falta una planta ah ya tengo las dos vale, ok, eh vamos a reunirnos con Bryce",es,
9,141268448,https://www.twitch.tv/videos/2853628924,12,00:05:35 - 00:05:44,"¿Por qué hay emisiones? ¿Qué más tenían? Aumentar la población, pero eso lo vas diciendo poco a",es,
10,141268448,https://www.twitch.tv/videos/2853628924,13,00:05:48 - 00:05:54,Vamos... ¡Eh! ¡Estamos en invierno! ¿Por qué por el primavera ya está nevando?,es,
11,141268448,https://www.twitch.tv/videos/2853628924,14,00:06:04 - 00:06:10,"Enchiendo. ¿Vamos dónde, Bryce?",es,
12,141268448,https://www.twitch.tv/videos/2853628924,15,00:06:11 - 00:06:12,"Vale, esto de que...",es,
13,141268448,https://www.twitch.tv/videos/2853628924,16,00:06:18 - 00:06:24,Pero ¿por qué está nevando? una pregunta muy sería,es,
14,141268448,https://www.twitch.tv/videos/2853628924,17,00:06:30 - 00:06:34,vale vamos para arriba,es,
15,141268448,https://www.twitch.tv/videos/2853628924,18,00:06:40 - 00:06:56,a la monta de las sierras altas ahora pensé que podía haberte peado ok vale pero me escucho una cosa madre mía,es,
16,141268448,https://www.twitch.tv/videos/2853628924,19,00:06:59 - 00:07:08,esto que seguir subiendo que locura este buenos días che,es,
17,141268448,https://www.twitch.tv/videos/2853628924,20,00:07:10 - 00:07:13,creo que no nos habíamos hasta ahora. Soy Mina.,es,
18,141268448,https://www.twitch.tv/videos/2853628924,21,00:07:14 - 00:07:22,"Mina Fotazas. Este juego me vacila, pero grandes rasgos.",es,
19,141268448,https://www.twitch.tv/videos/2853628924,22,00:07:23 - 00:07:28,La verdad. El objetivo más rápido de todo el archipiélago.,es,
20,141268448,https://www.twitch.tv/videos/2853628924,23,00:07:29 - 00:07:33,"Tengo que ser de hablar de mí, pero eso es porque se me da requetiría en mi trabajo. Soy súper sigilosa.",es,
21,141268448,https://www.twitch.tv/videos/2853628924,24,00:07:33 - 00:07:41,"Me expedizo en fotos analógicas de piezos, espontáneos desmedidos, fated, así decirlo.",es,
22,141268448,https://www.twitch.tv/videos/2853628924,25,00:07:41 - 00:07:46,"Potentes auténticas para los profanos, la vida real, vaya. Y ahora, si me disculpas, tengo que esperar a ciertos sitios.",es,
23,141268448,https://www.twitch.tv/videos/2853628924,26,00:07:46 - 00:07:51,"Esta isla está lista para la cosecha. No olvides llamar a tíos a algún contratiempo, ché.",es,
24,141268448,https://www.twitch.tv/videos/2853628924,27,00:07:53 - 00:08:01,"Coño 18. Ok, vamos a hablar con Bryce.",es,